import type { Question } from "./data";

// ── Math: Fractions ───────────────────────────────────────────────────────────

export const FRACTION_QUESTIONS: Question[] = [
  { id:"mf1", topic:"Simplify", question:"Simplify 12/16", choices:["3/4","4/5","2/3","6/8"], answer:"3/4", solution:"GCF of 12 and 16 is 4. 12÷4=3, 16÷4=4 → 3/4." },
  { id:"mf2", topic:"Simplify", question:"Simplify 6/9", choices:["1/2","2/3","3/4","4/6"], answer:"2/3", solution:"GCF of 6 and 9 is 3. 6÷3=2, 9÷3=3 → 2/3." },
  { id:"mf3", topic:"Simplify", question:"Simplify 15/25", choices:["3/5","5/8","2/5","3/4"], answer:"3/5", solution:"GCF of 15 and 25 is 5. 15÷5=3, 25÷5=5 → 3/5." },
  { id:"mf4", topic:"Add & Subtract", question:"1/3 + 1/4 = ?", choices:["7/12","2/7","1/6","2/12"], answer:"7/12", solution:"LCD=12. 4/12 + 3/12 = 7/12." },
  { id:"mf5", topic:"Add & Subtract", question:"2/5 + 1/3 = ?", choices:["11/15","3/8","1/2","3/15"], answer:"11/15", solution:"LCD=15. 6/15 + 5/15 = 11/15." },
  { id:"mf6", topic:"Add & Subtract", question:"3/4 − 1/3 = ?", choices:["5/12","2/3","1/4","7/12"], answer:"5/12", solution:"LCD=12. 9/12 − 4/12 = 5/12." },
  { id:"mf7", topic:"Add & Subtract", question:"1/2 + 1/3 + 1/6 = ?", choices:["1","5/6","2/3","7/6"], answer:"1", solution:"LCD=6. 3/6 + 2/6 + 1/6 = 6/6 = 1." },
  { id:"mf8", topic:"Multiply & Divide", question:"2/3 × 3/4 = ?", choices:["1/2","5/7","2/4","6/7"], answer:"1/2", solution:"2×3=6, 3×4=12. 6/12 = 1/2." },
  { id:"mf9", topic:"Multiply & Divide", question:"3/5 × 5/6 = ?", choices:["1/2","2/3","1/3","15/11"], answer:"1/2", solution:"3×5=15, 5×6=30. 15/30 = 1/2." },
  { id:"mf10", topic:"Multiply & Divide", question:"2/3 ÷ 4 = ?", choices:["1/6","8/3","2/12","1/2"], answer:"1/6", solution:"2/3 × 1/4 = 2/12 = 1/6." },
  { id:"mf11", topic:"Multiply & Divide", question:"3/4 ÷ 3/8 = ?", choices:["2","9/32","1/2","8/9"], answer:"2", solution:"Flip and multiply: 3/4 × 8/3 = 24/12 = 2." },
  { id:"mf12", topic:"Fractions & Decimals", question:"What is 3/4 as a decimal?", choices:["0.75","0.7","0.34","0.8"], answer:"0.75", solution:"3 ÷ 4 = 0.75." },
  { id:"mf13", topic:"Fractions & Decimals", question:"What is 2/5 as a decimal?", choices:["0.4","0.25","0.5","0.45"], answer:"0.4", solution:"2 ÷ 5 = 0.4." },
  { id:"mf14", topic:"Fractions & Decimals", question:"What is 0.6 as a fraction in simplest form?", choices:["3/5","6/10","3/4","2/3"], answer:"3/5", solution:"0.6 = 6/10. GCF=2 → 3/5." },
  { id:"mf15", topic:"Fractions & Decimals", question:"What is 0.125 as a fraction?", choices:["1/8","1/4","5/8","1/12"], answer:"1/8", solution:"0.125 = 125/1000 ÷ 125 = 1/8." },
  { id:"mf16", topic:"Percentages", question:"What is 25% as a fraction in simplest form?", choices:["1/4","25/100","1/5","1/3"], answer:"1/4", solution:"25% = 25/100. GCF=25 → 1/4." },
  { id:"mf17", topic:"Percentages", question:"What is 0.35 as a percentage?", choices:["35%","3.5%","350%","0.35%"], answer:"35%", solution:"0.35 × 100 = 35%." },
  { id:"mf18", topic:"Percentages", question:"What is 2/5 as a percentage?", choices:["40%","25%","20%","45%"], answer:"40%", solution:"2/5 = 0.4. 0.4 × 100 = 40%." },
  { id:"mf19", topic:"Comparing", question:"Which fraction is the largest? 3/4, 2/3, 5/8", choices:["3/4","2/3","5/8","They're equal"], answer:"3/4", solution:"3/4=0.75, 2/3≈0.667, 5/8=0.625. Largest is 3/4." },
  { id:"mf20", topic:"Comparing", question:"Which fraction is the smallest? 1/3, 2/7, 3/10", choices:["2/7","1/3","3/10","They're equal"], answer:"2/7", solution:"1/3≈0.333, 2/7≈0.286, 3/10=0.3. Smallest is 2/7." },
  { id:"mf21", topic:"Mixed Numbers", question:"Convert 2 3/4 to an improper fraction.", choices:["11/4","9/4","7/4","13/4"], answer:"11/4", solution:"Multiply the whole number by the denominator and add the numerator: (2×4)+3=11, so 11/4." },
  { id:"mf22", topic:"Mixed Numbers", question:"Convert 17/5 to a mixed number.", choices:["3 2/5","2 7/5","4 1/5","3 3/5"], answer:"3 2/5", solution:"17 ÷ 5 = 3 remainder 2, so 3 2/5." },
  { id:"mf23", topic:"Mixed Numbers", question:"1 1/2 + 2 1/3 = ?", choices:["3 5/6","3 1/2","4 1/6","3 2/5"], answer:"3 5/6", solution:"1+2=3 for whole numbers; 1/2+1/3 = 3/6+2/6 = 5/6. Answer: 3 5/6." },
  { id:"mf24", topic:"Mixed Numbers", question:"4 1/4 − 1 3/4 = ?", choices:["2 1/2","2 2/4","3 1/4","3 1/2"], answer:"2 1/2", solution:"Regroup: 4 1/4 = 3 5/4. Then 3 5/4 − 1 3/4 = 2 2/4 = 2 1/2." },
  { id:"mf25", topic:"Mixed Numbers", question:"2 1/2 × 1 1/3 = ?", choices:["3 1/3","2 5/6","3 1/2","2 2/3"], answer:"3 1/3", solution:"Convert: 5/2 × 4/3 = 20/6 = 10/3 = 3 1/3." },
  { id:"mf26", topic:"Multiply & Divide", question:"3/4 ÷ 1/2 = ?", choices:["3/2","3/8","1 1/2","6/4"], answer:"3/2", solution:"Flip and multiply: 3/4 × 2/1 = 6/4 = 3/2 (or 1 1/2)." },
  { id:"mf27", topic:"Ratios", question:"A class has 12 boys and 18 girls. What is the ratio of boys to girls in simplest form?", choices:["2:3","3:2","2:5","1:2"], answer:"2:3", solution:"GCF of 12 and 18 is 6. 12:18 simplifies to 2:3." },
  { id:"mf28", topic:"Percentages", question:"What is 30% of 90?", choices:["27","30","18","24"], answer:"27", solution:"30% = 0.30. 0.30 × 90 = 27." },
  { id:"mf29", topic:"Percentages", question:"A shirt costs $40 and is on sale for 25% off. What is the sale price?", choices:["$30","$35","$25","$32"], answer:"$30", solution:"25% of $40 = $10 discount. $40 − $10 = $30." },
  { id:"mf30", topic:"Scale Drawings", question:"On a map, 1 inch = 50 miles. Two cities are 3.5 inches apart on the map. How far apart are they really?", choices:["175 miles","150 miles","200 miles","140 miles"], answer:"175 miles", solution:"3.5 × 50 = 175 miles." },
];

// ── Math: Word problems ───────────────────────────────────────────────────────

export const WORD_PROBLEMS: Question[] = [
  { id:"mw1", topic:"Fractions", question:"A recipe uses 2/3 cup of sugar for every 1 cup of flour. How many cups of sugar are needed for 3 cups of flour?", choices:["2 cups","1½ cups","2⅓ cups","1 cup"], answer:"2 cups", solution:"2/3 × 3 = 2 cups." },
  { id:"mw2", topic:"Fractions", question:"Truma has 48 stickers. She gives 3/8 of them to her sister. How many does she have left?", choices:["30","18","32","36"], answer:"30", solution:"48 × 3/8 = 18 given away. 48 − 18 = 30." },
  { id:"mw3", topic:"Fractions", question:"A tank is 2/5 full and contains 24 liters. How many liters does the full tank hold?", choices:["60","48","40","50"], answer:"60", solution:"24 ÷ (2/5) = 24 × 5/2 = 60 liters." },
  { id:"mw4", topic:"Ratios", question:"The ratio of cats to dogs at a shelter is 4:3. There are 28 cats. How many dogs are there?", choices:["21","24","18","28"], answer:"21", solution:"28 ÷ 4 = 7 (one unit). 7 × 3 = 21 dogs." },
  { id:"mw5", topic:"Fractions", question:"A 6-meter ribbon is cut into pieces each 3/4 meter long. How many pieces are there?", choices:["8","6","4½","10"], answer:"8", solution:"6 ÷ (3/4) = 6 × 4/3 = 8 pieces." },
  { id:"mw6", topic:"Percentages", question:"Sarah scored 80% on a test with 35 questions. How many did she get right?", choices:["28","25","30","7"], answer:"28", solution:"35 × 0.80 = 28 correct." },
  { id:"mw7", topic:"Rate & Distance", question:"A car travels 45 km in 30 minutes. How far does it travel in 2 hours at the same speed?", choices:["180 km","90 km","135 km","270 km"], answer:"180 km", solution:"Speed = 45 ÷ 0.5 = 90 km/h. 90 × 2 = 180 km." },
  { id:"mw8", topic:"Fractions", question:"Three friends share a pizza. One eats 1/4, another eats 1/3. What fraction is left for the third?", choices:["5/12","1/3","1/2","7/12"], answer:"5/12", solution:"1/4 + 1/3 = 7/12. Left: 1 − 7/12 = 5/12." },
  { id:"mw9", topic:"Percentages", question:"A store bought items for $180 and sold them for $225. What was the percentage profit?", choices:["25%","20%","30%","45%"], answer:"25%", solution:"Profit = $45. 45/180 × 100 = 25%." },
  { id:"mw10", topic:"Ratios", question:"There are 36 children in a class. 5/9 are girls. How many more girls than boys are there?", choices:["4","8","20","16"], answer:"4", solution:"Girls = 20, boys = 16. 20 − 16 = 4." },
  { id:"mw11", topic:"Ratios", question:"Truma is making lemonade. The recipe calls for lemon juice and water in a ratio of 2:9. She wants to make 33 cups total. How many cups of lemon juice does she need?", choices:["6","9","3","11"], answer:"6", solution:"Total parts = 2+9 = 11. Each part = 33÷11 = 3 cups. Lemon juice = 2×3 = 6 cups." },
  { id:"mw12", topic:"Percentages", question:"A bookstore has 120 books. During a sale, 15% are sold on Friday and 25% of the remaining books are sold on Saturday. How many books are left after Saturday?", choices:["76","68","72","80"], answer:"76", solution:"Friday: 120 × 0.15 = 18 sold, 102 remain. Saturday: 102 × 0.25 = 25.5 → 26 sold. 102 − 26 = 76." },
  { id:"mw13", topic:"Rate & Distance", question:"Maya reads 24 pages in 30 minutes. At this rate, how long will it take her to read a 200-page book? Give your answer in hours and minutes.", choices:["4 hours 10 minutes","3 hours 45 minutes","2 hours 55 minutes","5 hours"], answer:"4 hours 10 minutes", solution:"Rate = 24 pages/30 min = 0.8 pages/min. Time = 200÷0.8 = 250 minutes = 4 hours 10 minutes." },
  { id:"mw14", topic:"Ratios", question:"In a bag of marbles, the ratio of red to blue to green is 3:4:5. There are 60 marbles total. How many green marbles are there?", choices:["25","20","15","30"], answer:"25", solution:"Total parts = 3+4+5 = 12. Each part = 60÷12 = 5. Green = 5×5 = 25." },
  { id:"mw15", topic:"Percentages", question:"A video game normally costs $60. During a holiday sale it is 30% off. Truma has a coupon for an extra 10% off the sale price. How much does she pay?", choices:["$37.80","$36.00","$40.00","$42.00"], answer:"$37.80", solution:"30% off $60 = $42. Then 10% off $42 = $4.20. Final price: $42 − $4.20 = $37.80." },
];

// ── Grammar ───────────────────────────────────────────────────────────────────

export const GRAMMAR_QUESTIONS: Question[] = [
  { id:"g1", topic:"Parts of Speech", question:'What part of speech is "quickly" in "She ran quickly"?', choices:["adjective","noun","adverb","verb"], answer:"adverb", solution:'"Quickly" modifies the verb "ran", that makes it an adverb.' },
  { id:"g2", topic:"Parts of Speech", question:"Which word is a preposition? (run / happy / under / she)", choices:["run","happy","under","she"], answer:"under", solution:'"Under" shows a positional relationship between words, that\'s what prepositions do.' },
  { id:"g3", topic:"Sentence Structure", question:'What is the direct object in "Maria threw the ball"?', choices:["Maria","threw","ball","the"], answer:"ball", solution:"The direct object receives the action. Maria threw what? The ball." },
  { id:"g4", topic:"Literary Devices", question:'A simile compares two things using which words?', choices:["is or was","and or but","like or as","more than"], answer:"like or as", solution:'"Her smile is like sunshine" uses "like", that\'s a simile.' },
  { id:"g5", topic:"Literary Devices", question:"Which sentence uses personification?", choices:["He ran like the wind.","The sky is very blue.","The trees whispered secrets.","She has red hair."], answer:"The trees whispered secrets.", solution:"Trees can't whisper, giving human actions to non-humans is personification." },
  { id:"g6", topic:"Literary Devices", question:"What is alliteration?", choices:["Comparing unlike things","Extreme exaggeration","Repetition of the same beginning sounds","Writing in rhyme"], answer:"Repetition of the same beginning sounds", solution:'"Peter Piper picked...", the repeated "p" sound is alliteration.' },
  { id:"g7", topic:"Sentence Types", question:"Which sentence is a compound sentence?", choices:["She ran fast.","Because she was tired, she slept.","He studied hard, and he passed the test.","Running through the park."], answer:"He studied hard, and he passed the test.", solution:"Two independent clauses joined by 'and', that's a compound sentence." },
  { id:"g8", topic:"Sentence Structure", question:'What is the predicate of "The large black dog barked"?', choices:["large black dog","The large","barked","The large black dog barked"], answer:"barked", solution:"The predicate is the verb or verb phrase telling what the subject does." },
  { id:"g9", topic:"Literary Devices", question:"What is a metaphor?", choices:['Using "like" or "as" to compare',"Saying something IS something else","Repeating beginning sounds","Giving human traits to objects"], answer:"Saying something IS something else", solution:'"Life is a journey", no "like" or "as," just direct comparison.' },
  { id:"g10", topic:"Literary Devices", question:"What is hyperbole?", choices:['A comparison using "like" or "as"',"Giving human traits to objects","Extreme exaggeration for effect","A word that imitates a sound"], answer:"Extreme exaggeration for effect", solution:'"I\'ve told you a million times!", nobody literally said it a million times.' },
  { id:"g11", topic:"Parts of Speech", question:'What part of speech is "and" in a sentence?', choices:["preposition","conjunction","interjection","adverb"], answer:"conjunction", solution:"Conjunctions join words, phrases, or clauses. 'And' does exactly that." },
  { id:"g12", topic:"Sentence Structure", question:'What is the subject of "Under the old bridge lived a troll"?', choices:["Under","old bridge","troll","Under the old bridge"], answer:"troll", solution:"Who or what is the sentence about? The troll, even when the subject comes after the verb." },
  { id:"g13", topic:"Sentence Types", question:'What makes a sentence a "complex sentence"?', choices:["It has two independent clauses","It is very long","It has one independent and one dependent clause","It has no subject"], answer:"It has one independent and one dependent clause", solution:'"Although it rained [dependent], we went outside [independent]" = complex.' },
  { id:"g14", topic:"Parts of Speech", question:"What does a conjunction do?", choices:["Modifies a noun","Shows possession","Connects words, phrases, or clauses","Names a person, place, or thing"], answer:"Connects words, phrases, or clauses", solution:"Conjunctions are connectors, 'and,' 'but,' 'or,' 'because,' 'although.'" },
  { id:"g15", topic:"Literary Devices", question:'Which literary device is used in "The test was so hard it took a thousand hours"?', choices:["Simile","Metaphor","Personification","Hyperbole"], answer:"Hyperbole", solution:'"A thousand hours" is wildly exaggerated, that\'s hyperbole.' },
  { id:"g16", topic:"Conjunctions", question:"Which of these is a subordinating conjunction?", choices:["and","but","although","or"], answer:"although", solution:"Subordinating conjunctions (although, because, while, if) introduce dependent clauses." },
  { id:"g17", topic:"Parts of Speech", question:"What is an interjection?", choices:["A word that modifies a verb","A word that names a person or place","A word that expresses sudden emotion","A word that connects clauses"], answer:"A word that expresses sudden emotion", solution:"Wow! Ouch! Hey!, interjections show sudden feeling and are often followed by an exclamation mark." },
  { id:"g18", topic:"Sentence Structure", question:'In "My friend, a talented artist, won the contest," what is "a talented artist"?', choices:["A participial phrase","An appositive phrase","A prepositional phrase","An adverb clause"], answer:"An appositive phrase", solution:"An appositive phrase renames or explains a nearby noun, here it renames 'my friend.'" },
  { id:"g19", topic:"Sentence Structure", question:"Which sentence contains a participial phrase?", choices:["The cat sat quietly.","Running through the sprinklers, Leah laughed.","She is my best friend.","We ate lunch at noon."], answer:"Running through the sprinklers, Leah laughed.", solution:"'Running through the sprinklers' is a participial phrase, it modifies 'Leah' using a verb form." },
  { id:"g20", topic:"Subject-Verb Agreement", question:'Which sentence is correct?', choices:["The dogs runs fast.","Each of the girls are ready.","Neither of the boys was late.","The team are playing well."], answer:"Neither of the boys was late.", solution:"'Neither' is singular, so it takes a singular verb: 'was,' not 'were.'" },
  { id:"g21", topic:"Pronoun Agreement", question:'Which sentence has correct pronoun-antecedent agreement?', choices:["Everyone brought their lunch.","Each student must bring their own pencil.","The team celebrated their victory.","Every player must know their position."], answer:"Each student must bring their own pencil.", solution:"'Each student' is singular; 'their' is now widely accepted as a singular gender-neutral pronoun in standard usage." },
  { id:"g22", topic:"Voice", question:"Which sentence is written in passive voice?", choices:["The chef cooked the meal.","The dog chased the cat.","The trophy was won by our team.","Truma finished her homework."], answer:"The trophy was won by our team.", solution:"Passive voice has the subject receiving the action (the trophy was won), not performing it." },
  { id:"g23", topic:"Punctuation", question:"Which sentence uses a comma correctly?", choices:["I like apples, and oranges.","After the game, we ate pizza.","She ran, quickly.","He went to the store and, bought milk."], answer:"After the game, we ate pizza.", solution:"A comma follows an introductory phrase or clause, 'After the game' is an introductory phrase." },
  { id:"g24", topic:"Punctuation", question:"When should you use a semicolon?", choices:["Between a list of three items","To join two related independent clauses","After an introductory phrase","Before a quotation"], answer:"To join two related independent clauses", solution:"'She studied hard; she aced the test.' A semicolon links two closely related complete thoughts." },
  { id:"g25", topic:"Punctuation", question:"Which sentence correctly uses a colon?", choices:["I need: milk and bread.","Bring the following: a pencil, paper, and a ruler.","She said: that she was tired.","He went: to the store."], answer:"Bring the following: a pencil, paper, and a ruler.", solution:"A colon introduces a list or explanation after a complete independent clause." },
  { id:"g26", topic:"Sentence Structure", question:"Which sentence has correct parallel structure?", choices:["She likes running, to swim, and dance.","She likes running, swimming, and dancing.","She likes to run, swimming, and to dance.","She likes run, swim, and dancing."], answer:"She likes running, swimming, and dancing.", solution:"Parallel structure means all items in a list use the same grammatical form, here, all -ing gerunds." },
  { id:"g27", topic:"Verb Tenses", question:'What tense is the verb in "By noon, she had finished all her work"?', choices:["Simple past","Present perfect","Past perfect","Future perfect"], answer:"Past perfect", solution:"Past perfect (had + past participle) describes an action completed before another past event." },
  { id:"g28", topic:"Verb Tenses", question:'What tense is used in "He is reading a book about ancient Rome"?', choices:["Simple present","Present progressive","Present perfect","Past progressive"], answer:"Present progressive", solution:"Present progressive (is/am/are + -ing) shows an action happening right now." },
  { id:"g29", topic:"Nouns", question:"Which word is a proper noun?", choices:["city","river","Amazon","mountain"], answer:"Amazon", solution:"Proper nouns name a specific person, place, or thing and are always capitalized, Amazon is a specific river." },
  { id:"g30", topic:"Nouns", question:'Which word is an abstract noun?', choices:["table","courage","river","apple"], answer:"courage", solution:"Abstract nouns name ideas, feelings, or qualities you cannot touch, courage, love, justice, freedom." },
];

// ── Vocabulary / Latin roots ──────────────────────────────────────────────────

export const VOCAB_QUESTIONS: Question[] = [
  { id:"v1", topic:"Root Words", question:'The Latin root "port" appears in "transport." What does "port" mean?', choices:["push","carry","pull","lift"], answer:"carry", solution:"Transport (trans + port) = carry across. Import, export, all involve carrying." },
  { id:"v2", topic:"Root Words", question:'The root "aud" appears in "auditorium." What does "aud" mean?', choices:["see","hear","speak","write"], answer:"hear", solution:"An auditorium is a place where you hear things, concerts, speeches, plays." },
  { id:"v3", topic:"Root Words", question:'"Biography" contains the Greek root "bio." What does "bio" mean?', choices:["book","life","write","study"], answer:"life", solution:"Bio = life. Biology, biome, biosphere, all about living things." },
  { id:"v4", topic:"Prefixes", question:'The prefix "un-" in "unhappy" means:', choices:["very","not","again","before"], answer:"not", solution:'"Un-" negates a word, unhappy, unfair, unknown all mean the opposite.' },
  { id:"v5", topic:"Root Words", question:'"Geography" uses the Greek root "geo." What does "geo" mean?', choices:["earth/land","water","sky","people"], answer:"earth/land", solution:"Geo = earth. Geography, geology, geothermal, all about the earth." },
  { id:"v6", topic:"Suffixes", question:'The suffix "-ology" (as in "biology") means:', choices:["relating to","the study of","full of","without"], answer:"the study of", solution:"Biology = study of life; geology = study of earth; zoology = study of animals." },
  { id:"v7", topic:"Root Words", question:'"Manuscript" contains the Latin root "manu." What does "manu" mean?', choices:["write","book","hand","page"], answer:"hand", solution:"A manuscript was originally written by hand. Manicure, manual, all involve hands." },
  { id:"v8", topic:"Root Words", question:'The root "vis" (as in "visible") means:', choices:["know","see","hear","touch"], answer:"see", solution:"Visible = able to be seen. Television, vision, visit, all relate to seeing." },
  { id:"v9", topic:"Prefixes", question:'"Telephone" contains the Greek prefix "tele." What does "tele" mean?', choices:["talk","far/distant","sound","small"], answer:"far/distant", solution:"Tele = far. Telephone (far sound), telescope (see far), television (see far)." },
  { id:"v10", topic:"Suffixes", question:'The suffix "-tion" turns a verb into:', choices:["a different tense verb","an adjective","a noun","an adverb"], answer:"a noun", solution:'"Connect" → "connection." "Create" → "creation." The -tion ending makes nouns.' },
  { id:"v11", topic:"Root Words", question:'The Latin root "scrib/script" means:', choices:["to write","to read","to speak","to copy"], answer:"to write", solution:"Scribble, describe, scripture, manuscript, all involve writing." },
  { id:"v12", topic:"Prefixes", question:'The prefix "pre-" (as in "preview") means:', choices:["again","before","after","across"], answer:"before", solution:"Preview = see before. Prefix, prequel, prehistoric, all mean 'before.'" },
  { id:"v13", topic:"Root Words", question:'"Microscope" contains the Greek root "micro." What does "micro" mean?', choices:["small","large","far","hidden"], answer:"small", solution:"Microscope = see small. Microphone, microchip, all about small things." },
  { id:"v14", topic:"Root Words", question:'The Latin root "duc/duct" appears in "conductor." What does it mean?', choices:["make","lead/bring","carry","move"], answer:"lead/bring", solution:"Conduct (lead together), educate (lead out), introduce (lead into)." },
  { id:"v15", topic:"Suffixes", question:'The suffix "-less" (as in "helpless") means:', choices:["full of","without","relating to","one who"], answer:"without", solution:"Helpless = without help. Fearless, careless, worthless, all mean 'without.'" },
  { id:"v16", topic:"Root Words", question:'The Latin root "rupt" appears in "interrupt" and "erupt." What does "rupt" mean?', choices:["flow","break","turn","burst open"], answer:"break", solution:"Interrupt = break between; erupt = break out; corrupt = break (morally). 'Rupt' means break." },
  { id:"v17", topic:"Root Words", question:'The root "tract" is found in "tractor" and "attract." What does "tract" mean?', choices:["push","turn","pull or drag","build"], answer:"pull or drag", solution:"A tractor pulls loads; attract = pull toward. Subtract, contract, all involve pulling." },
  { id:"v18", topic:"Root Words", question:'The Latin root "spect" means "to look." Which word does NOT come from "spect"?', choices:["inspect","spectator","spectacular","speculate"], answer:"speculate", solution:"Inspect (look into), spectator (one who looks), spectacular (worth looking at). Speculate comes from speculum (mirror) via a different branch." },
  { id:"v19", topic:"Root Words", question:'"Construction" contains the root "struct." What does "struct" mean?', choices:["destroy","build","draw","measure"], answer:"build", solution:"Construct = build together; structure = something built; instruct = build into the mind." },
  { id:"v20", topic:"Root Words", question:'The root "mis/mit" appears in "mission" and "transmit." What does it mean?', choices:["speak","send","move","go"], answer:"send", solution:"Mission = something sent; transmit = send across; admit = send toward (let in)." },
  { id:"v21", topic:"Root Words", question:'The Latin root "pos" appears in "position" and "deposit." What does "pos" mean?', choices:["carry","say","place","hold"], answer:"place", solution:"Position = a place; deposit = place down; compose = place together." },
  { id:"v22", topic:"Root Words", question:'The Latin root "jud" appears in "judge" and "judicial." What does "jud" mean?', choices:["rule","punish","judge","law"], answer:"judge", solution:"Judicial = relating to judges; adjudicate = to act as judge; prejudice = judging before knowing." },
  { id:"v23", topic:"Root Words", question:'The Latin root "cred" appears in "credit" and "incredible." What does "cred" mean?', choices:["trust/believe","value","know","say"], answer:"trust/believe", solution:"Credible = believable; incredible = not believable; credentials = proof people can believe in you." },
  { id:"v24", topic:"Root Words", question:'The Latin root "grad" appears in "gradual" and "graduate." What does "grad" mean?', choices:["learn","step or go","grow","reach"], answer:"step or go", solution:"Gradual = going step by step; graduate = to step forward to the next level; upgrade = go up a step." },
  { id:"v25", topic:"Root Words", question:'The root "dict" appears in "dictate" and "predict." What does "dict" mean?', choices:["say or speak","write","hear","command"], answer:"say or speak", solution:"Dictate = to say aloud; predict = say before it happens; contradict = say against." },
  { id:"v26", topic:"Context Clues", question:'Read: "The ancient ruins were so dilapidated that no one dared enter." What does "dilapidated" most likely mean?', choices:["beautifully decorated","fallen apart and worn down","recently built","carefully preserved"], answer:"fallen apart and worn down", solution:"The context clue 'no one dared enter' tells us the ruins are dangerously run-down." },
  { id:"v27", topic:"Root Words", question:'The root "vid/vis" appears in "video" and "evident." A piece of "evidence" is something that is:', choices:["spoken about","clearly seen or shown","written down","heard"], answer:"clearly seen or shown", solution:"Evidence comes from Latin 'videre' (to see), evidence is something that makes facts visible and clear." },
  { id:"v28", topic:"Root Words", question:'"Export" and "import" both contain the root "port" (carry). What does "export" mean?', choices:["carry into a country","carry out of a country","carry quickly","carry carefully"], answer:"carry out of a country", solution:"Ex- means 'out of,' so export = carry out of a country. Im- means 'into,' so import = carry in." },
  { id:"v29", topic:"Root Words", question:'Which word comes from the Latin root "aud" (hear)?', choices:["audio","author","autumn","august"], answer:"audio", solution:"Audio = sound you hear. Audible (able to be heard) and audience (those who hear) come from the same root." },
  { id:"v30", topic:"Root Words", question:'The root "scrib/script" appears in "inscription." What is an inscription?', choices:["A loud announcement","Words written on a surface like stone or metal","A story passed down orally","A royal command"], answer:"Words written on a surface like stone or metal", solution:"In- (on) + scrib (write) = written on something. Ancient inscriptions were carved into stone." },
];

// ── History / Geography ───────────────────────────────────────────────────────

export const HISTORY_QUESTIONS: Question[] = [
  { id:"h1", topic:"Egypt", question:"Which ancient civilization built the Great Pyramids at Giza?", choices:["Egypt","Mesopotamia","Greece","Rome"], answer:"Egypt", solution:"The pyramids at Giza were built by ancient Egyptians as tombs for their pharaohs." },
  { id:"h2", topic:"Mesopotamia", question:"The Tigris and Euphrates rivers flow through which ancient region?", choices:["Egypt","Mesopotamia","Greece","Persia"], answer:"Mesopotamia", solution:"Mesopotamia means 'land between the rivers', the Tigris and Euphrates." },
  { id:"h3", topic:"Greece", question:"What city-state was known for its fierce warrior culture?", choices:["Athens","Sparta","Rome","Carthage"], answer:"Sparta", solution:"Spartan boys began military training at age 7. 'Spartan' still means tough and bare." },
  { id:"h4", topic:"Geography", question:"Which continent is the largest by land area?", choices:["Africa","North America","Asia","Europe"], answer:"Asia", solution:"Asia covers about 44.6 million km², about 30% of Earth's total land area." },
  { id:"h5", topic:"Mesopotamia", question:"What writing system did the Sumerians of Mesopotamia develop?", choices:["Hieroglyphics","Cuneiform","The alphabet","Morse code"], answer:"Cuneiform", solution:"Cuneiform (wedge-shaped marks on clay tablets) was the world's first writing system." },
  { id:"h6", topic:"Rome", question:"Julius Caesar was a leader of which ancient civilization?", choices:["Greece","Egypt","Rome","Persia"], answer:"Rome", solution:"Julius Caesar was a Roman general and statesman in the 1st century B.C." },
  { id:"h7", topic:"Geography", question:"What is a peninsula?", choices:["A body of water surrounded by land","Land surrounded by water on three sides","A land bridge between continents","An island"], answer:"Land surrounded by water on three sides", solution:"Italy and Spain are famous peninsulas, land jutting into the sea on three sides." },
  { id:"h8", topic:"Greece", question:"What are the titles of Homer's two famous epic poems?", choices:["The Aeneid and The Odyssey","The Iliad and The Odyssey","The Republic and The Laws","The Iliad and The Symposium"], answer:"The Iliad and The Odyssey", solution:"Homer wrote the Iliad (the Trojan War) and the Odyssey (Odysseus's journey home)." },
  { id:"h9", topic:"Egypt", question:"What writing system did the ancient Egyptians use?", choices:["Cuneiform","Hieroglyphics","The Greek alphabet","Latin script"], answer:"Hieroglyphics", solution:"Hieroglyphics are pictorial symbols, ancient Egyptians carved them on temple walls." },
  { id:"h10", topic:"Geography", question:"Which ocean is the largest?", choices:["Pacific","Atlantic","Indian","Arctic"], answer:"Pacific", solution:"The Pacific Ocean covers about 165 million km², larger than all of Earth's land combined." },
  { id:"h11", topic:"Greece", question:"Ancient Athens was famous for being the birthplace of:", choices:["the Roman Empire","democracy","monotheism","the calendar"], answer:"democracy", solution:"Athens developed one of the first democratic systems of government around 508 B.C." },
  { id:"h12", topic:"Mesopotamia", question:"Which ancient law code was one of the first written sets of laws?", choices:["The Roman Constitution","The Code of Hammurabi","The Magna Carta","The Athenian Laws"], answer:"The Code of Hammurabi", solution:"Hammurabi, king of Babylon (~1750 B.C.), 'an eye for an eye' comes from his code." },
  { id:"h13", topic:"Geography", question:"Which sea is bordered by Europe, Africa, and Asia?", choices:["Red Sea","Mediterranean Sea","Black Sea","Aegean Sea"], answer:"Mediterranean Sea", solution:"The Mediterranean (meaning 'middle of the earth') connects three continents." },
  { id:"h14", topic:"Egypt", question:"The Nile River delta flows into which body of water?", choices:["Red Sea","Mediterranean Sea","Indian Ocean","Aegean Sea"], answer:"Mediterranean Sea", solution:"The Nile flows north through Egypt and empties into the Mediterranean at its delta." },
  { id:"h15", topic:"Rome", question:"What was the most famous arena in ancient Rome, where gladiators fought?", choices:["The Parthenon","The Forum","The Colosseum","The Pantheon"], answer:"The Colosseum", solution:"The Colosseum, built around 70–80 A.D., held up to 80,000 spectators." },
  { id:"h16", topic:"Egypt", question:"What was the title of the all-powerful rulers of ancient Egypt?", choices:["Emperor","Pharaoh","Consul","Sultan"], answer:"Pharaoh", solution:"Pharaohs were considered both kings and living gods, they had total authority over all Egypt." },
  { id:"h17", topic:"Egypt", question:"Ancient Egyptians believed in an afterlife. What did they do to preserve bodies for the afterlife?", choices:["They buried them in clay pots","They cremated them","They mummified them","They placed them in the Nile River"], answer:"They mummified them", solution:"Mummification preserved the body by removing organs and drying the body with salts." },
  { id:"h18", topic:"Egypt", question:"What is the Rosetta Stone famous for?", choices:["It is the oldest pyramid","It helped scholars decode Egyptian hieroglyphics","It was Cleopatra's throne","It marked the source of the Nile River"], answer:"It helped scholars decode Egyptian hieroglyphics", solution:"The Rosetta Stone (196 B.C.) had the same text in three scripts, allowing scholars to crack the hieroglyphic code." },
  { id:"h19", topic:"Greece", question:"Which ancient Greek philosopher was the teacher of Alexander the Great?", choices:["Socrates","Plato","Aristotle","Pythagoras"], answer:"Aristotle", solution:"Aristotle tutored the young Alexander the Great, teaching him philosophy, science, and rhetoric." },
  { id:"h20", topic:"Greece", question:"Where did the ancient Greeks hold their famous athletic competitions every four years?", choices:["Athens","Sparta","Olympia","Delphi"], answer:"Olympia", solution:"The ancient Olympic Games were held at Olympia, Greece, starting around 776 B.C., honoring Zeus." },
  { id:"h21", topic:"Greece", question:"What is a city-state (polis)?", choices:["A city ruled by a king and his army","A self-governing city and the surrounding territory","A colony established in another land","A city built on a hill for defense"], answer:"A self-governing city and the surrounding territory", solution:"Greek city-states like Athens and Sparta were independent, self-governing communities with their own laws." },
  { id:"h22", topic:"Rome", question:"What was the Roman Republic's system of government before it became an empire?", choices:["A monarchy ruled by one king","A democracy where all citizens voted","A republic with elected senators and consuls","A theocracy ruled by priests"], answer:"A republic with elected senators and consuls", solution:"The Roman Republic (509–27 B.C.) was led by elected officials, two consuls and the Senate, not one king." },
  { id:"h23", topic:"Rome", question:"The 'Pax Romana' was a famous period of:", choices:["civil war and chaos","peace and prosperity in the Roman Empire","trade with China","conquest of Egypt"], answer:"peace and prosperity in the Roman Empire", solution:"Pax Romana (27 B.C.–180 A.D.) means 'Roman Peace', about 200 years of stability under Roman rule." },
  { id:"h24", topic:"Rome", question:"Christianity grew quickly in the Roman Empire partly because Rome had built:", choices:["many churches and cathedrals","an excellent road system connecting the empire","a strong navy to spread the religion","large schools teaching Christian ideas"], answer:"an excellent road system connecting the empire", solution:"Roman roads stretched thousands of miles, making it easy for early Christian missionaries to travel and spread their message." },
  { id:"h25", topic:"China", question:"Which ancient Chinese dynasty is most famous for building the Great Wall?", choices:["The Tang Dynasty","The Ming Dynasty","The Han Dynasty","The Shang Dynasty"], answer:"The Ming Dynasty", solution:"While early walls existed, the Great Wall was mostly built and expanded during the Ming Dynasty (1368–1644)." },
  { id:"h26", topic:"China", question:"The Silk Road was primarily a network of:", choices:["roads built only for the Chinese army","rivers connecting China to India","trade routes connecting China to the Mediterranean world","sea lanes for Chinese fishing fleets"], answer:"trade routes connecting China to the Mediterranean world", solution:"The Silk Road carried silk, spices, and ideas between China, Central Asia, Persia, and Rome." },
  { id:"h27", topic:"Mesopotamia", question:"What was a ziggurat?", choices:["An Egyptian tomb shaped like a pyramid","A Mesopotamian stepped temple tower","A Greek market place","A Roman aqueduct"], answer:"A Mesopotamian stepped temple tower", solution:"Ziggurats were massive stepped towers built in Sumerian cities as temples to the gods." },
  { id:"h28", topic:"Alexander the Great", question:"Alexander the Great was king of which ancient kingdom?", choices:["Athens","Persia","Macedonia","Egypt"], answer:"Macedonia", solution:"Alexander III of Macedonia (356–323 B.C.) created one of the largest empires in ancient history." },
  { id:"h29", topic:"Alexander the Great", question:"At its height, Alexander the Great's empire stretched from Greece all the way to:", choices:["China","India","Rome","Britain"], answer:"India", solution:"Alexander's conquests reached as far east as modern-day India and Pakistan before his army refused to go further." },
  { id:"h30", topic:"Rome", question:"Which of the following is a major cause of the fall of the Western Roman Empire?", choices:["A volcanic eruption destroyed Rome","Invasions by Germanic tribes weakened the empire","Rome was conquered by Greece","A plague wiped out all Roman soldiers"], answer:"Invasions by Germanic tribes weakened the empire", solution:"Germanic tribes like the Visigoths repeatedly invaded and eventually sacked Rome; the Western Empire fell in 476 A.D." },
];

// ── Science ───────────────────────────────────────────────────────────────────

export const SCIENCE_QUESTIONS: Question[] = [
  { id:"s1", topic:"Cells", question:"What is the smallest unit of life?", choices:["an atom","a cell","a tissue","an organ"], answer:"a cell", solution:"All living things are made of cells, from bacteria (one cell) to humans (trillions)." },
  { id:"s2", topic:"Cells", question:'Which organelle is called the cell\'s "powerhouse"?', choices:["nucleus","mitochondria","cell membrane","ribosome"], answer:"mitochondria", solution:"Mitochondria convert food into ATP (energy), fuel for everything the cell does." },
  { id:"s3", topic:"Ecosystems", question:"What three things does a plant need for photosynthesis?", choices:["Oxygen, water, and sugar","Soil, water, and minerals","Sunlight, water, and carbon dioxide","Oxygen, sunlight, and minerals"], answer:"Sunlight, water, and carbon dioxide", solution:"Plants combine CO₂ + water using sunlight to make glucose, releasing oxygen." },
  { id:"s4", topic:"Physical Science", question:"What force keeps objects on Earth's surface?", choices:["magnetism","gravity","friction","pressure"], answer:"gravity", solution:"Gravity pulls objects toward Earth's center, it keeps us from floating away." },
  { id:"s5", topic:"Physical Science", question:"Which is a chemical change (not a physical change)?", choices:["crushing a can","burning wood","melting ice","tearing paper"], answer:"burning wood", solution:"Burning wood creates new substances (ash, smoke). The others only change shape or state." },
  { id:"s6", topic:"Earth Science", question:"How many planets are in our solar system?", choices:["7","9","8","10"], answer:"8", solution:"Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune = 8. Pluto was reclassified in 2006." },
  { id:"s7", topic:"Earth Science", question:"Igneous rock forms from:", choices:["compressed sediments","cooled magma or lava","intense heat and pressure","erosion and weathering"], answer:"cooled magma or lava", solution:"Igneous (from Latin 'fire') rock forms when molten rock cools and solidifies." },
  { id:"s8", topic:"Ecosystems", question:"An ecosystem includes:", choices:["only living organisms","a type of climate","a community of organisms and their physical environment","the entire surface of the Earth"], answer:"a community of organisms and their physical environment", solution:"An ecosystem includes all living (biotic) and non-living (abiotic) things in an area." },
  { id:"s9", topic:"Cells", question:"What gas do plants release during photosynthesis?", choices:["carbon dioxide","nitrogen","oxygen","water vapor"], answer:"oxygen", solution:"As a byproduct of making glucose, plants release oxygen, which animals then breathe." },
  { id:"s10", topic:"Earth Science", question:"The water cycle's three main processes are:", choices:["precipitation, condensation, and flooding","evaporation, condensation, and precipitation","evaporation, sublimation, and rain","melting, freezing, and evaporation"], answer:"evaporation, condensation, and precipitation", solution:"Water evaporates → condenses into clouds → falls as precipitation (rain/snow)." },
  { id:"s11", topic:"Earth Science", question:"Which layer of Earth is liquid metal?", choices:["crust","mantle","outer core","inner core"], answer:"outer core", solution:"The outer core is liquid iron and nickel, its movement creates Earth's magnetic field." },
  { id:"s12", topic:"Ecosystems", question:"In a food chain, organisms that make their own food are called:", choices:["producers","consumers","decomposers","predators"], answer:"producers", solution:"Plants are producers, they 'produce' food through photosynthesis." },
  { id:"s13", topic:"Physical Science", question:"What is density?", choices:["How hard something is","Mass per unit volume","How much space something takes up","The weight of an object"], answer:"Mass per unit volume", solution:"Density = mass ÷ volume. Lead is more dense than wood; that's why wood floats." },
  { id:"s14", topic:"Cells", question:"Which organelle controls what enters and exits the cell?", choices:["nucleus","mitochondria","cell membrane","ribosome"], answer:"cell membrane", solution:"The cell membrane is a selectively permeable barrier, it decides what gets in or out." },
  { id:"s15", topic:"Ecosystems", question:"What do decomposers do in an ecosystem?", choices:["Produce food from sunlight","Break down dead matter and recycle nutrients","Hunt and eat other animals","Convert nitrogen in the air"], answer:"Break down dead matter and recycle nutrients", solution:"Decomposers (bacteria, fungi) break down dead plants/animals, returning nutrients to soil." },
  { id:"sc16", topic:"Cells", question:"Which organelle contains the cell's DNA and directs all cell activities?", choices:["mitochondria","ribosome","nucleus","vacuole"], answer:"nucleus", solution:"The nucleus is the cell's control center, it holds DNA and sends instructions for all cell functions." },
  { id:"sc17", topic:"Cells", question:"Which feature does a plant cell have that an animal cell does NOT?", choices:["nucleus","mitochondria","cell membrane","cell wall"], answer:"cell wall", solution:"Plant cells have a rigid cell wall (made of cellulose) outside the membrane that gives them shape and structure. Animal cells do not." },
  { id:"sc18", topic:"Cells", question:"What is the job of the chloroplast in a plant cell?", choices:["To control what enters the cell","To produce energy from food","To capture sunlight for photosynthesis","To store the cell's DNA"], answer:"To capture sunlight for photosynthesis", solution:"Chloroplasts contain chlorophyll, the green pigment that captures sunlight to make glucose." },
  { id:"sc19", topic:"Ecosystems", question:"In a food web, what would most likely happen if all the rabbits in a meadow disappeared?", choices:["The foxes would have more food","The grass would decrease","The foxes would struggle to find food","The deer population would decrease"], answer:"The foxes would struggle to find food", solution:"If rabbits (prey) disappear, the foxes (predators) that depend on them lose a food source and their numbers drop." },
  { id:"sc20", topic:"Ecosystems", question:"Which describes a predator-prey relationship?", choices:["A bee and a flower sharing pollen","A lion hunting a zebra","Two trees competing for sunlight","Bacteria decomposing a dead log"], answer:"A lion hunting a zebra", solution:"A predator (lion) hunts and eats the prey (zebra), this is a classic predator-prey relationship." },
  { id:"sc21", topic:"Physical Science", question:"When liquid water turns into water vapor, this is called:", choices:["condensation","freezing","evaporation","sublimation"], answer:"evaporation", solution:"Evaporation is the phase change from liquid to gas, it happens when water gains enough energy to escape as vapor." },
  { id:"sc22", topic:"Physical Science", question:"Which of the following is a simple machine?", choices:["A bicycle wheel","A car engine","A lever","A computer"], answer:"A lever", solution:"Simple machines include the lever, pulley, inclined plane, wedge, screw, and wheel and axle, a lever is a classic example." },
  { id:"sc23", topic:"Scientific Method", question:"What is a hypothesis?", choices:["The final conclusion of an experiment","A testable prediction or explanation","The materials list for an experiment","A measurement taken during a lab"], answer:"A testable prediction or explanation", solution:"A hypothesis is an educated guess stated in a testable 'if-then' form before an experiment begins." },
  { id:"sc24", topic:"Astronomy", question:"Which planet is known as the 'Red Planet'?", choices:["Jupiter","Venus","Mars","Saturn"], answer:"Mars", solution:"Mars appears reddish because its surface is covered in iron oxide (rust). It's our neighbor just beyond Earth." },
  { id:"sc25", topic:"Astronomy", question:"What causes the phases of the Moon?", choices:["Earth's shadow falling on the Moon","The Moon moving closer and farther from Earth","Different portions of the lit Moon being visible from Earth","Clouds blocking our view of the Moon"], answer:"Different portions of the lit Moon being visible from Earth", solution:"As the Moon orbits Earth, we see different fractions of its sunlit side, that's what creates the phases." },
  { id:"sc26", topic:"Earth Science", question:"Which layer of the atmosphere do we live in and where weather occurs?", choices:["Stratosphere","Thermosphere","Troposphere","Mesosphere"], answer:"Troposphere", solution:"The troposphere is the lowest layer, containing most of the air we breathe and all of Earth's weather." },
  { id:"sc27", topic:"Human Body", question:"What is the primary job of the circulatory system?", choices:["To digest food and absorb nutrients","To transport blood, oxygen, and nutrients throughout the body","To remove carbon dioxide from cells","To control body movements"], answer:"To transport blood, oxygen, and nutrients throughout the body", solution:"The heart pumps blood through blood vessels, delivering oxygen and nutrients to every cell and picking up waste." },
  { id:"sc28", topic:"Human Body", question:"Where does most of the digestion and nutrient absorption happen?", choices:["Stomach","Large intestine","Small intestine","Esophagus"], answer:"Small intestine", solution:"The small intestine is the longest section of the digestive tract, it breaks food down further and absorbs nutrients into the blood." },
  { id:"sc29", topic:"Chemistry", question:"What is a mixture?", choices:["Two or more elements chemically bonded together","A pure substance made of one type of atom","Two or more substances combined but not chemically joined","A liquid that has been boiled"], answer:"Two or more substances combined but not chemically joined", solution:"In a mixture (like salad or salt water) the substances can be separated again, they are not chemically bonded." },
  { id:"sc30", topic:"Chemistry", question:"Which of the following is an element (not a compound or mixture)?", choices:["Water (H₂O)","Salt (NaCl)","Gold (Au)","Air"], answer:"Gold (Au)", solution:"An element is a pure substance made of only one kind of atom. Gold is element 79 on the periodic table." },
];

// ── Bible ─────────────────────────────────────────────────────────────────────

export const BIBLE_QUESTIONS: Question[] = [
  // Gospel & Salvation
  { id:"bi1",  topic:"Gospel",      question:"According to Romans 3:23, who has sinned?",                                  choices:["Only unbelievers","Everyone except Christians","All people","Only people who never try"],       answer:"All people",          solution:"Romans 3:23, 'all have sinned and fall short of the glory of God.' There are no exceptions." },
  { id:"bi2",  topic:"Gospel",      question:"Ephesians 2:8-9 says salvation is NOT based on what?",                       choices:["God's grace","Faith in Christ","Our own works","God's gift"],                                    answer:"Our own works",       solution:"Eph. 2:8-9: 'saved by grace through faith… not of works, so no one may boast.' Salvation is entirely God's gift." },
  { id:"bi3",  topic:"Gospel",      question:"What is justification?",                                                     choices:["Being made morally perfect by effort","Being declared righteous because of Christ's work","Earning God's approval through obedience","Attending church regularly"],  answer:"Being declared righteous because of Christ's work", solution:"Justification is a legal declaration: God counts us righteous because Christ's perfect record is credited to us by faith." },
  { id:"bi4",  topic:"Gospel",      question:"What does 'imputation' mean in the doctrine of salvation?",                  choices:["Being baptized","Memorizing Scripture","Christ's righteousness credited to our account","Obeying the Ten Commandments"], answer:"Christ's righteousness credited to our account", solution:"Our sin is imputed to Christ (He bore the punishment); Christ's righteousness is imputed to us (we receive His standing before God)." },
  { id:"bi5",  topic:"Gospel",      question:"Romans 6:23: 'The wages of sin is death, but the gift of God is…'",          choices:["happiness in this life","forgiveness of some sins","eternal life in Christ Jesus","a second chance to be good"],  answer:"eternal life in Christ Jesus", solution:"Romans 6:23 contrasts what we earn (death) with what God freely gives. Salvation is a gift, not a wage we work for." },
  { id:"bi6",  topic:"Gospel",      question:"What does it mean that Jesus is the 'propitiation' for our sins (1 John 2:2)?", choices:["He was a good example","He absorbed God's just wrath against sin on our behalf","He prayed for our forgiveness","He proved obedience is possible"], answer:"He absorbed God's just wrath against sin on our behalf", solution:"Propitiation means satisfying God's wrath. Christ took the penalty we deserved so God could be both just and justifier (Rom. 3:26)." },
  { id:"bi7",  topic:"Gospel",      question:"According to John 3:3, how can a person see the kingdom of God?",            choices:["By being a good person","By being born again","By being baptized as an infant","By keeping the commandments"], answer:"By being born again", solution:"Jesus told Nicodemus: 'Unless one is born again he cannot see the kingdom of God.' New birth is the Spirit's sovereign work in us." },
  { id:"bi8",  topic:"Gospel",      question:"What is sanctification?",                                                    choices:["Being declared righteous at the moment of salvation","The lifelong process of being made more holy by the Spirit","Earning extra merit with God","Going to church faithfully"], answer:"The lifelong process of being made more holy by the Spirit", solution:"Justification is one-time and complete; sanctification is ongoing. The Spirit progressively conforms believers to Christ's image." },
  // Five Solas
  { id:"bi9",  topic:"Five Solas",  question:"What does 'Sola Scriptura' mean?",                                           choices:["Scripture plus church tradition guides us","Scripture alone is the final authority for faith and practice","Only clergy can interpret the Bible","The Bible was written by the church"], answer:"Scripture alone is the final authority for faith and practice", solution:"Sola Scriptura (Scripture alone) was the formal principle of the Reformation: the Bible is the supreme, self-authenticating authority." },
  { id:"bi10", topic:"Five Solas",  question:"What does 'Sola Fide' mean?",                                                choices:["Faith plus good works justifies us","We are justified by faith alone","Only extraordinary faith saves","Faith is just sincere belief"],  answer:"We are justified by faith alone", solution:"Sola Fide (faith alone) was the material principle of the Reformation, justification is through faith alone, not faith plus works." },
  { id:"bi11", topic:"Five Solas",  question:"What does 'Sola Gratia' mean?",                                              choices:["Salvation by sincere effort","Grace plus the sacraments saves","Salvation is entirely God's undeserved gift","Grace is something we earn over time"], answer:"Salvation is entirely God's undeserved gift", solution:"Sola Gratia (grace alone), salvation originates in God's grace, not human initiative or merit. God gets all the credit." },
  { id:"bi12", topic:"Five Solas",  question:"What does 'Solus Christus' mean?",                                           choices:["Christ and the saints together save us","Christ alone is mediator and Savior","Christ saves us because of our faith","Church membership makes Christ's work effective"], answer:"Christ alone is mediator and Savior", solution:"Solus Christus, Jesus is the one mediator between God and man (1 Tim. 2:5). John 14:6: 'I am the way, the truth, and the life.'" },
  { id:"bi13", topic:"Five Solas",  question:"What does 'Soli Deo Gloria' mean?",                                          choices:["Glory to the saints","God shares glory with faithful believers","Glory to God alone, He gets all the credit","Glory through our achievements"], answer:"Glory to God alone, He gets all the credit", solution:"Soli Deo Gloria, everything, including salvation itself, exists to magnify God's glory alone. We have nothing to boast in." },
  // Old Testament
  { id:"bi14", topic:"Old Testament", question:"What was the result of Adam and Eve's sin in the Garden?",                choices:["They gained perfect wisdom","They became angels","Death and separation from God entered the world","God immediately destroyed the earth"], answer:"Death and separation from God entered the world", solution:"Genesis 3, the Fall brought spiritual death, physical death, and total depravity. All humanity descends from Adam in sin (Rom. 5:12)." },
  { id:"bi15", topic:"Old Testament", question:"What did God promise Abraham that pointed forward to Christ?",             choices:["All nations would be blessed through his offspring","His family would always be wealthy","He would rule the whole earth","His descendants would never face hardship"], answer:"All nations would be blessed through his offspring", solution:"Genesis 12:3, the Abrahamic covenant: through Abraham's seed (ultimately Christ, Gal. 3:16), all nations would be blessed." },
  { id:"bi16", topic:"Old Testament", question:"Why are Old Testament sacrifices called 'types' by theologians?",         choices:["They were typed into books","They were the preferred type of worship","They pointed forward to Christ's sacrifice and were fulfilled by it","They were performed the same type each year"], answer:"They pointed forward to Christ's sacrifice and were fulfilled by it", solution:"A 'type' foreshadows a future 'antitype.' All OT sacrifices pointed to Christ, the final and perfect sacrifice (Hebrews 10)." },
  { id:"bi17", topic:"Old Testament", question:"Isaiah 53 describes a servant who bore our griefs and was pierced for our transgressions. Who?", choices:["King David","The Prophet Isaiah","Moses","Jesus Christ"], answer:"Jesus Christ", solution:"Isaiah 53, written ~700 BC, is a detailed messianic prophecy of Jesus's substitutionary suffering and death for sinners." },
  { id:"bi18", topic:"Old Testament", question:"What was the significance of the Passover lamb's blood on the doorpost?", choices:["It was a symbol of Egyptian power","It was a good luck charm","It protected Israel from the angel of death, a type of Christ","It was sacrificed to earn God's favor"], answer:"It protected Israel from the angel of death, a type of Christ", solution:"Exodus 12, the Passover lamb is a type of Christ. 1 Cor. 5:7: 'Christ, our Passover lamb, has been sacrificed.'" },
  // New Testament
  { id:"bi19", topic:"New Testament", question:"What does the word 'gospel' mean?",                                       choices:["Good behavior","God's requirements","Good news","God's history"], answer:"Good news", solution:"Gospel (Greek: euangelion) = good news, the good news that Christ died for sinners, was buried, and rose again (1 Cor. 15:3-4)." },
  { id:"bi20", topic:"New Testament", question:"Why is the bodily resurrection of Jesus essential to Christianity?",      choices:["It is symbolic, not essential","Without it our faith is useless and we are still in our sins (1 Cor. 15:17)","It only matters for Christ's personal glory","It proved Jesus was a good teacher"], answer:"Without it our faith is useless and we are still in our sins (1 Cor. 15:17)", solution:"Paul argues in 1 Corinthians 15 that the resurrection is the cornerstone. A dead savior cannot justify anyone." },
  // Bible Knowledge
  { id:"bi21", topic:"Scripture",   question:"How many books are in the Protestant Bible?",                               choices:["60","63","66","73"],  answer:"66", solution:"39 Old Testament books + 27 New Testament books = 66. The Roman Catholic Bible adds the Apocrypha (7 books), rejected by Protestants." },
  { id:"bi22", topic:"Scripture",   question:"What are the first five books of the Bible called (written by Moses)?",     choices:["The Gospels","The Epistles","The Pentateuch (Torah)","The Historical Books"], answer:"The Pentateuch (Torah)", solution:"Genesis, Exodus, Leviticus, Numbers, Deuteronomy. Moses wrote the Pentateuch (Greek: five scrolls), also called the Torah." },
  { id:"bi23", topic:"Scripture",   question:"In what language was most of the New Testament originally written?",        choices:["Latin","Hebrew","Aramaic","Koine Greek"], answer:"Koine Greek", solution:"The NT was written in Koine (common) Greek, the everyday language of the Roman Empire in the 1st century." },
  { id:"bi24", topic:"Scripture",   question:"Which Gospel was most likely written first?",                               choices:["Matthew","Mark","Luke","John"], answer:"Mark", solution:"Most scholars hold Markan priority, Mark was written ~AD 65, with Matthew and Luke drawing on it. John wrote last (~AD 90)." },
  { id:"bi25", topic:"Scripture",   question:"What is the shortest verse in the Bible?",                                  choices:["'God is love.'","'Jesus wept.'","'Pray continually.'","'Fear not.'"], answer:"'Jesus wept.'", solution:"John 11:35, 'Jesus wept.' Two words. Jesus wept at Lazarus's tomb, showing His true humanity and compassion." },
  // Reformation
  { id:"bi26", topic:"Reformation", question:"Who nailed 95 Theses to the Wittenberg church door in 1517, sparking the Reformation?", choices:["John Calvin","John Knox","William Tyndale","Martin Luther"], answer:"Martin Luther", solution:"Luther's 95 Theses challenged the sale of indulgences, sparking the Protestant Reformation and the recovery of the gospel." },
  { id:"bi27", topic:"Reformation", question:"Why did William Tyndale translate the Bible into English?",                choices:["To become famous","Because the Pope asked him to","So ordinary people could read God's Word for themselves","To replace the Hebrew and Greek originals"], answer:"So ordinary people could read God's Word for themselves", solution:"Tyndale believed every plowboy should read Scripture. He was martyred in 1536, but his work heavily shaped the King James Bible." },
  { id:"bi28", topic:"Reformation", question:"What is the doctrine of 'total depravity'?",                               choices:["Humans are as evil as possible","Sin has corrupted every part of human nature, so we cannot save ourselves","Only truly wicked people are totally depraved","Christians have no sinful nature remaining"], answer:"Sin has corrupted every part of human nature, so we cannot save ourselves", solution:"Total depravity (TULIP) doesn't mean maximum wickedness, but that sin affects intellect, will, and affections, we can't save ourselves." },
  { id:"bi29", topic:"Reformation", question:"What do the letters TULIP stand for?",                                     choices:["Ten Useful Lessons In Prayer","Total depravity, Unconditional election, Limited atonement, Irresistible grace, Perseverance of saints","The Universal Love In Providence","Traditional Understanding Lives In Practice"], answer:"Total depravity, Unconditional election, Limited atonement, Irresistible grace, Perseverance of saints", solution:"TULIP summarizes the five points of Calvinism from the Synod of Dort (1618-19), emphasizing God's sovereignty in salvation." },
  { id:"bi30", topic:"Reformation", question:"What did Luther mean by 'the priesthood of all believers'?",              choices:["All Christians should be ordained priests","Priests alone govern the church","All believers have direct access to God through Christ, no human mediator required","Christians can ignore church leadership"], answer:"All believers have direct access to God through Christ, no human mediator required", solution:"1 Peter 2:9, believers are a royal priesthood. We need no human priest to approach God; Christ alone is our mediator (1 Tim. 2:5)." },
];

// ── Subject config map ────────────────────────────────────────────────────────

export const SUBJECT_QUESTIONS: Record<string, Question[]> = {
  grammar: GRAMMAR_QUESTIONS,
  vocab: VOCAB_QUESTIONS,
  history: HISTORY_QUESTIONS,
  science: SCIENCE_QUESTIONS,
  bible: BIBLE_QUESTIONS,
};

export const SUBJECT_META: Record<string, {
  label: string;
  description: string;
  xpPerCorrect: number;
  topicsCovered: string[];
}> = {
  grammar: {
    label: "Grammar",
    description: "Parts of speech, sentence types, and literary devices",
    xpPerCorrect: 10,
    topicsCovered: ["Parts of speech", "Sentence structure (subject, predicate, objects)", "Simple, compound, and complex sentences", "Literary devices: simile, metaphor, alliteration, personification, hyperbole", "Subordinating conjunctions, interjections, appositive and participial phrases", "Comma, semicolon, and colon rules; parallel structure; verb tenses; noun types"],
  },
  vocab: {
    label: "Vocabulary",
    description: "Latin and Greek roots, prefixes, and suffixes",
    xpPerCorrect: 10,
    topicsCovered: ["Latin roots: port, aud, manu, vis, scrib, duc, rupt, tract, spect, struct, mis/mit, pos, jud, cred, grad", "Greek roots: bio, geo, micro, tele, dict", "Prefixes: un-, pre-, re-, dis-", "Suffixes: -ology, -tion, -less", "Context clues and word meaning in sentences"],
  },
  history: {
    label: "History",
    description: "Ancient civilizations and world geography",
    xpPerCorrect: 10,
    topicsCovered: ["Ancient Egypt: pyramids, pharaohs, hieroglyphics, mummification, Rosetta Stone", "Mesopotamia: Sumerians, cuneiform, Hammurabi, ziggurats", "Ancient Greece: Athens, Sparta, democracy, Homer, philosophy, Olympics", "Ancient Rome: republic, Julius Caesar, Pax Romana, Colosseum, fall of Rome", "Ancient China: dynasties, Great Wall, Silk Road", "Alexander the Great; spread of Christianity; world geography"],
  },
  science: {
    label: "Science",
    description: "Cells, ecosystems, earth science, physical science, and the human body",
    xpPerCorrect: 10,
    topicsCovered: ["Cells: organelles, plant vs. animal cells, photosynthesis", "Ecosystems: food chains/webs, producers, decomposers, predator-prey", "Earth science: rock cycle, water cycle, atmosphere layers, solar system", "Physical science: states of matter, phase changes, simple machines, density", "Human body: circulatory, digestive, respiratory systems", "Chemistry: elements, compounds, mixtures; scientific method"],
  },
  bible: {
    label: "Bible",
    description: "Gospel, Five Solas, Reformation, Old Testament, and Scripture knowledge",
    xpPerCorrect: 10,
    topicsCovered: ["The Gospel: sin, judgment, grace, justification, imputation, propitiation", "Five Solas: Sola Scriptura, Sola Fide, Sola Gratia, Solus Christus, Soli Deo Gloria", "Old Testament: the Fall, covenant with Abraham, Passover typology, Isaiah 53", "New Testament: the resurrection, the Gospel, sanctification, John 3 and Romans 6", "Bible structure: Pentateuch, Gospels, Epistles; OT/NT languages and authorship", "Reformation: Luther, Tyndale, the priesthood of believers, total depravity, TULIP"],
  },
  prealgebra: {
    label: "Pre-Algebra",
    description: "Variables, equations, ratios, percentages, and order of operations",
    xpPerCorrect: 15,
    topicsCovered: ["Solving one-step and two-step equations", "Order of operations (PEMDAS)", "Ratios and proportions", "Percentages", "Combining like terms", "Evaluating expressions"],
  },
  writing: {
    label: "Writing",
    description: "Essays, rhetoric, composition, and rhetorical devices",
    xpPerCorrect: 15,
    topicsCovered: ["Thesis statements", "Essay structure (intro, body, conclusion)", "Rhetorical devices: anaphora, chiasmus, antithesis", "Show vs. tell", "Precise diction and strong verbs", "Active vs. passive voice", "The writing process"],
  },
};
