/**
 * Scripture references keyed by question ID.
 * Merged into questions at runtime by getRandomQuestions().
 * Format: "Reference, 'short quote'"
 */
export const QUESTION_SCRIPTURES: Record<string, string> = {

  // ── TITUS: BIBLE ─────────────────────────────────────────────────────────
  tb1:  "Mark 1:17, 'Follow me, and I will make you fishers of men.'",
  tb2:  "Mark 1:17, 'Follow me, and I will make you fishers of men.'",
  tb3:  "John 6:9, 'There is a boy here who has five barley loaves and two fish.'",
  tb4:  "Luke 5:6, 'They caught a great number of fish, and their nets were breaking.'",
  tb5:  "Matthew 14:29, 'He said, \"Come.\" So Peter got out of the boat and walked on the water.'",
  tb6:  "Romans 5:8, 'While we were still sinners, Christ died for us.'",
  tb7:  "1 Corinthians 15:20, 'Christ has been raised from the dead.'",
  tb8:  "2 Timothy 3:16, 'All Scripture is breathed out by God.'",
  tb9:  "Luke 15:4, 'Does he not leave the ninety-nine to go after the one that is lost?'",
  tb10: "Romans 3:23, 'All have sinned and fall short of the glory of God.'",
  tb11: "Romans 1:16, 'I am not ashamed of the gospel, for it is the power of God for salvation.'",
  tb12: "Genesis 1:1, 'In the beginning, God created the heavens and the earth.'",
  tb13: "Genesis 6:14, 'Make yourself an ark of gopher wood.'",
  tb14: "2 Timothy 3:16, 'All Scripture is breathed out by God and profitable for teaching.'",
  tb15: "2 Timothy 3:16, 'All Scripture is breathed out by God… that the man of God may be complete.'",
  tb16: "Ephesians 2:8–9, 'By grace you have been saved through faith, this is not your own doing; it is the gift of God.'",

  // ── TITUS: THEOLOGY ──────────────────────────────────────────────────────
  tt1:  "Psalm 19:1, 'The heavens declare the glory of God.'",
  tt2:  "Genesis 1:1, 'In the beginning, God created the heavens and the earth.'",
  tt3:  "Jeremiah 10:10, 'But the Lord is the true God; he is the living God.'",
  tt4:  "John 3:16, 'For God so loved the world that he gave his one and only Son.'",
  tt5:  "Romans 5:8, 'While we were still sinners, Christ died for us.'",
  tt6:  "Ephesians 2:8, 'By grace you have been saved through faith.'",
  tt7:  "Psalm 139:16, 'In your book were written every one of them, the days that were formed for me.'",
  tt8:  "Romans 8:29, 'Those whom he foreknew he also predestined to be conformed to the image of his Son.'",
  tt9:  "John 6:44, 'No one can come to me unless the Father who sent me draws him.'",
  tt10: "Galatians 5:22, 'The fruit of the Spirit is love, joy, peace, patience, kindness…'",
  tt11: "1 Peter 1:2, '…according to the foreknowledge of God the Father.'",
  tt12: "Romans 3:23, 'All have sinned and fall short of the glory of God.'",
  tt13: "Romans 6:23, 'The wages of sin is death, but the free gift of God is eternal life.'",
  tt14: "John 1:14, 'The Word became flesh and dwelt among us.'",
  tt15: "Hebrews 4:15, 'He was tempted in every way, just as we are, yet he did not sin.'",
  tt16: "1 Corinthians 15:3–4, 'Christ died for our sins… he was buried… he was raised on the third day.'",
  tt17: "Matthew 28:18, 'All authority in heaven and on earth has been given to me.'",
  tt18: "John 14:6, 'I am the way, and the truth, and the life.'",
  tt19: "2 Timothy 3:16, 'All Scripture is breathed out by God.'",
  tt20: "Revelation 21:3, 'Behold, the dwelling place of God is with man.'",

  // ── MERCY: THEOLOGY ──────────────────────────────────────────────────────
  mt1:  "Genesis 1:1, 'In the beginning, God created the heavens and the earth.'",
  mt2:  "Psalm 139:14, 'I praise you because I am fearfully and wonderfully made.'",
  mt3:  "John 3:16, 'God so loved the world that he gave his one and only Son.'",
  mt4:  "Romans 5:8, 'While we were still sinners, Christ died for us.'",
  mt5:  "1 John 4:19, 'We love because he first loved us.'",
  mt6:  "Ephesians 2:8, 'By grace you have been saved through faith.'",
  mt7:  "John 10:11, 'I am the good shepherd. The good shepherd lays down his life for the sheep.'",
  mt8:  "Matthew 6:9, 'Our Father in heaven, hallowed be your name.'",
  mt9:  "1 John 1:9, 'If we confess our sins, he is faithful and just to forgive us our sins.'",
  mt10: "Psalm 23:1, 'The Lord is my shepherd; I shall not want.'",
  mt11: "Revelation 21:4, 'He will wipe away every tear from their eyes.'",
  mt12: "Galatians 5:22, 'The fruit of the Spirit is love, joy, peace, patience, kindness…'",

  // ── LOIS: THEOLOGY ───────────────────────────────────────────────────────
  lt1:  "Genesis 1:1, 'In the beginning, God created the heavens and the earth.'",
  lt2:  "John 3:16, 'God so loved the world that he gave his one and only Son.'",
  lt3:  "Mark 10:14, 'Let the children come to me; do not hinder them.'",
  lt4:  "Psalm 56:3, 'When I am afraid, I put my trust in you.'",
  lt5:  "1 John 4:8, 'God is love.'",
  lt6:  "Psalm 147:5, 'Great is our Lord, and abundant in power.'",
  lt7:  "Ephesians 2:8, 'By grace you have been saved through faith.'",
  lt8:  "Matthew 6:9, 'Our Father in heaven, hallowed be your name.'",

  // ── MERCY: BIBLE ─────────────────────────────────────────────────────────
  mb1:  "Genesis 1:1, 'In the beginning, God created the heavens and the earth.'",
  mb2:  "Psalm 139:14, 'I am fearfully and wonderfully made.'",
  mb3:  "John 3:16, 'God so loved the world that he gave his one and only Son.'",
  mb4:  "Matthew 14:19, 'He took the five loaves and the two fish… he blessed and broke the loaves.'",
  mb5:  "Romans 5:8, 'While we were still sinners, Christ died for us.'",
  mb6:  "Luke 2:7, 'She wrapped him in cloths and placed him in a manger.'",
  mb7:  "Mark 10:14, 'Let the children come to me; do not hinder them.'",
  mb8:  "Psalm 23:1, 'The Lord is my shepherd; I shall not want.'",
  mb9:  "Matthew 28:6, 'He is not here; he has risen, just as he said.'",
  mb10: "Galatians 5:22, 'The fruit of the Spirit is love, joy, peace, patience, kindness…'",
  mb11: "Psalm 136:1, 'Give thanks to the Lord, for he is good, his love endures forever.'",
  mb12: "Matthew 7:7, 'Ask, and it will be given to you; seek, and you will find.'",
  mb13: "Luke 15:7, 'There will be more joy in heaven over one sinner who repents.'",
  mb14: "1 John 1:9, 'If we confess our sins, he is faithful and just to forgive us.'",
  mb15: "Genesis 9:13, 'I have set my rainbow in the clouds, and it will be the sign of my covenant.'",

  // ── LOIS: BIBLE ──────────────────────────────────────────────────────────
  lb1:  "Psalm 147:4, 'He determines the number of the stars and calls them each by name.'",
  lb2:  "Genesis 1:25, 'God made the wild animals… and God saw that it was good.'",
  lb3:  "2 Timothy 3:16, 'All Scripture is breathed out by God.'",
  lb4:  "John 3:16, 'For God so loved the world that he gave his one and only Son.'",
  lb5:  "Genesis 6:22, 'Noah did everything just as God commanded him.'",
  lb6:  "Philippians 4:6, 'In every situation, by prayer and petition… present your requests to God.'",
  lb7:  "Mark 10:14, 'Let the children come to me; do not hinder them.'",
  lb8:  "Psalm 104:14, 'He makes grass grow for the cattle, and plants for people to cultivate.'",
  lb9:  "John 20:31, 'These are written so that you may believe that Jesus is the Christ.'",
  lb10: "Mark 10:27, 'All things are possible with God.'",
  lb11: "Psalm 139:13–14, 'You knit me together in my mother's womb… I am fearfully and wonderfully made.'",
  lb12: "Genesis 9:13, 'I have set my rainbow in the clouds as the sign of the covenant.'",
  lb13: "Luke 2:7, 'She wrapped him in cloths and placed him in a manger.'",
  lb14: "Psalm 145:18, 'The Lord is near to all who call on him.'",
  lb15: "Genesis 1:31, 'God saw all that he had made, and it was very good.'",

  // ── TITUS: SCIENCE ───────────────────────────────────────────────────────
  s1:   "Psalm 8:3, 'When I consider your heavens, the work of your fingers, the moon and the stars…'",
  s2:   "Psalm 104:14, 'He makes grass grow for the cattle, and plants for people to cultivate.'",
  s3:   "Psalm 19:1, 'The heavens declare the glory of God; the skies proclaim the work of his hands.'",
  s4:   "Psalm 139:14, 'I praise you because I am fearfully and wonderfully made.'",
  s5:   "Job 26:7, 'He spreads out the northern skies over empty space; he suspends the earth over nothing.'",
  s6:   "Ecclesiastes 1:7, 'All streams flow into the sea, yet the sea is never full.'",
  s7:   "Genesis 1:21, 'God created the great creatures of the sea and every living thing with which the water teems.'",
  s8:   "Genesis 2:7, 'God breathed into his nostrils the breath of life, and the man became a living creature.'",
  s9:   "Psalm 33:6, 'By the word of the Lord the heavens were made, their starry host by the breath of his mouth.'",
  s10:  "Psalm 18:2, 'The Lord is my rock, my fortress and my deliverer.'",
  s11:  "Colossians 1:17, 'In him all things hold together.'",
  s12:  "Genesis 1:30, 'I give every green plant for food to every beast of the earth.'",
  s13:  "Colossians 1:17, 'He is before all things, and in him all things hold together.'",
  s14:  "Psalm 19:1, 'The heavens declare the glory of God; the skies proclaim the work of his hands.'",
  s15:  "2 Corinthians 5:17, 'If anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come.'",
  s16:  "Psalm 19:4–5, 'In the heavens God has pitched a tent for the sun. It is like a bridegroom coming out of his chamber.'",
  s17:  "Acts 17:25, 'He himself gives everyone life and breath and everything else.'",
  s18:  "Psalm 104:16, 'The trees of the Lord are well watered, the cedars of Lebanon that he planted.'",
  s19:  "Genesis 2:7, 'The Lord God formed a man from the dust of the ground and breathed into his nostrils the breath of life.'",
  s20:  "Genesis 1:29, 'God said, \"I give you every seed-bearing plant on the face of the whole earth.\"'",

  // ── TITUS: GRAMMAR ───────────────────────────────────────────────────────
  g1:   "John 1:1, 'In the beginning was the Word, and the Word was with God, and the Word was God.'",
  g2:   "Psalm 150:6, 'Let everything that has breath praise the Lord.'",
  g3:   "Psalm 139:14, 'I am fearfully and wonderfully made.'",
  g4:   "Proverbs 25:11, 'A word fitly spoken is like apples of gold in a setting of silver.'",
  g5:   "Isaiah 40:28, 'The Lord is the everlasting God, the Creator of the ends of the earth.'",
  g6:   "Acts 17:26, 'He made every nation of men, that they should inhabit the whole earth.'",
  g7:   "Ephesians 4:29, 'Let no corrupting talk come out of your mouths, but only such as is good.'",
  g8:   "Lamentations 3:22–23, 'The steadfast love of the Lord never ceases; his mercies never come to an end.'",
  g9:   "Proverbs 19:2, 'It is not good to have zeal without knowledge, nor to be hasty.'",
  g10:  "Proverbs 25:11, 'A word fitly spoken is like apples of gold in a setting of silver.'",
  g11:  "Matthew 7:7, 'Ask, and it will be given to you; seek, and you will find.'",
  g12:  "Proverbs 31:25, 'She is clothed with strength and dignity; she can laugh at the days to come.'",
  g13:  "Psalm 1:3, 'That person is like a tree planted by streams of water, whose leaf does not wither.'",
  g14:  "Romans 12:2, 'Do not be conformed to this world, but be transformed by the renewing of your mind.'",
  g15:  "Ecclesiastes 4:9, 'Two are better than one, because they have a good return for their labor.'",
  g16:  "Proverbs 4:7, 'The beginning of wisdom is this: Get wisdom. Whatever you get, get insight.'",
  g17:  "Proverbs 17:17, 'A friend loves at all times, and a brother is born for a time of adversity.'",
  g18:  "Galatians 5:22, 'The fruit of the Spirit is love, joy, peace, patience, kindness, goodness…'",
  g19:  "Proverbs 12:17, 'An honest witness tells the truth, but a false witness tells lies.'",
  g20:  "Proverbs 14:29, 'Whoever is patient has great understanding, but one who is quick-tempered displays folly.'",

  // ── TITUS: US HISTORY ────────────────────────────────────────────────────
  h1:   "Romans 13:1, 'Let everyone be subject to the governing authorities, for there is no authority except that which God has established.'",
  h2:   "Acts 17:26, 'He made every nation of men, that they should inhabit the whole earth; he determined… the exact places where they should live.'",
  h3:   "Proverbs 14:34, 'Righteousness exalts a nation, but sin condemns any people.'",
  h4:   "Psalm 107:23–24, 'Some went out on the sea in ships… they saw the works of the Lord, his wonderful deeds in the deep.'",
  h5:   "Acts 17:26, 'From one man he made all the nations, that they should inhabit the whole earth.'",
  h6:   "Psalm 22:28, 'Dominion belongs to the Lord and he rules over the nations.'",
  h7:   "Proverbs 11:14, 'For lack of guidance a nation falls, but victory is won through many advisers.'",
  h8:   "Proverbs 22:6, 'Start children off on the way they should go, and even when they are old they will not turn from it.'",
  h9:   "Proverbs 3:27, 'Do not withhold good from those to whom it is due, when it is in your power to act.'",
  h10:  "1 Peter 2:17, 'Honor everyone. Love the brotherhood. Fear God. Honor the emperor.'",
  h11:  "Proverbs 29:14, 'If a king judges the poor with fairness, his throne will be established forever.'",
  h12:  "Romans 13:1, 'There is no authority except that which God has established.'",
  h13:  "Matthew 12:25, 'Every kingdom divided against itself will be ruined.'",
  h14:  "Genesis 1:28, 'Be fruitful and increase in number; fill the earth and subdue it.'",
  h15:  "Proverbs 22:1, 'A good name is more desirable than great riches; to be esteemed is better than silver or gold.'",
  h16:  "Psalm 107:23, 'Some went out on the sea in ships, trading on the mighty waters.'",
  h17:  "Proverbs 8:12, 'I, wisdom, dwell together with prudence; I possess knowledge and discretion.'",
  h18:  "Psalm 107:1, 'Give thanks to the Lord, for he is good; his love endures forever.'",
  h19:  "Romans 13:1, 'Every person is to be in subjection to the governing authorities.'",
  h20:  "Proverbs 20:28, 'Love and faithfulness keep a king safe; through love his throne is made secure.'",

  // ── MERCY: COUNTING ──────────────────────────────────────────────────────
  c1:   "Psalm 147:4, 'He determines the number of the stars and calls them each by name.'",
  c2:   "Psalm 147:4, 'He determines the number of the stars and calls them each by name.'",
  c3:   "Luke 15:4, 'Suppose one of you has a hundred sheep and loses one of them, does he not count them all?'",
  c4:   "Psalm 147:4, 'He determines the number of the stars and calls them each by name.'",
  c5:   "Matthew 10:30, 'Even the very hairs of your head are all numbered.'",
  c6:   "Matthew 10:30, 'Even the very hairs of your head are all numbered.'",
  c7:   "Genesis 1:5, 'God called the light \"day,\" and the darkness he called \"night.\" And there was evening, and there was morning, the first day.'",
  c8:   "Genesis 1:31, 'God saw all that he had made, and it was very good. And there was evening, and there was morning, the sixth day.'",
  c9:   "Psalm 90:12, 'Teach us to number our days, that we may gain a heart of wisdom.'",
  c10:  "Psalm 90:12, 'Teach us to number our days, that we may gain a heart of wisdom.'",
  c11:  "Revelation 7:9, 'A great multitude that no one could count, from every nation, tribe, people and language.'",
  c12:  "Revelation 7:9, 'A great multitude that no one could count, from every nation.'",
  c13:  "Psalm 147:4, 'He determines the number of the stars and calls them each by name.'",
  c14:  "Matthew 18:12, 'If a man owns a hundred sheep, and one of them wanders away, will he not leave the ninety-nine?'",
  c15:  "Psalm 90:12, 'Teach us to number our days, that we may gain a heart of wisdom.'",

  // ── MERCY: ADDITION ──────────────────────────────────────────────────────
  a1:   "Ecclesiastes 4:9, 'Two are better than one, because they have a good return for their labor.'",
  a2:   "Ecclesiastes 4:9, 'Two are better than one, because they have a good return for their labor.'",
  a3:   "Psalm 147:4, 'He determines the number of the stars and calls them each by name.'",
  a4:   "Matthew 10:30, 'Even the very hairs of your head are all numbered.'",
  a5:   "Ecclesiastes 4:9, 'Two are better than one, because they have a good return for their labor.'",
  a6:   "Psalm 90:12, 'Teach us to number our days, that we may gain a heart of wisdom.'",
  a7:   "Matthew 10:30, 'Even the very hairs of your head are all numbered.'",
  a8:   "Psalm 147:4, 'He determines the number of the stars and calls them each by name.'",
  a9:   "Ecclesiastes 4:9, 'Two are better than one, because they have a good return for their labor.'",
  a10:  "Psalm 90:12, 'Teach us to number our days, that we may gain a heart of wisdom.'",

  // ── MERCY: PHONICS ───────────────────────────────────────────────────────
  p1:   "Psalm 119:105, 'Your word is a lamp for my feet, a light on my path.'",
  p2:   "Psalm 119:105, 'Your word is a lamp for my feet, a light on my path.'",
  p3:   "John 1:1, 'In the beginning was the Word, and the Word was with God.'",
  p4:   "Proverbs 4:7, 'The beginning of wisdom is this: Get wisdom; get insight.'",
  p5:   "Psalm 119:11, 'I have hidden your word in my heart that I might not sin against you.'",
  p6:   "2 Timothy 3:16, 'All Scripture is breathed out by God and profitable for teaching.'",
  p7:   "Psalm 119:105, 'Your word is a lamp for my feet, a light on my path.'",
  p8:   "Proverbs 22:6, 'Start children off on the way they should go.'",
  p9:   "John 1:1, 'In the beginning was the Word, and the Word was with God.'",
  p10:  "Psalm 119:11, 'I have hidden your word in my heart that I might not sin against you.'",
  p11:  "2 Timothy 2:15, 'Do your best to present yourself to God as one approved, a worker who handles the word of truth correctly.'",
  p12:  "Psalm 119:105, 'Your word is a lamp for my feet, a light on my path.'",
  p13:  "Proverbs 4:7, 'The beginning of wisdom is this: Get wisdom; get insight.'",
  p14:  "John 1:1, 'In the beginning was the Word, and the Word was with God.'",
  p15:  "Psalm 119:11, 'I have hidden your word in my heart that I might not sin against you.'",

  // ── MERCY: SHAPES & COLORS ───────────────────────────────────────────────
  sh1:  "Psalm 104:24, 'How many are your works, Lord! In wisdom you made them all; the earth is full of your creatures.'",
  sh2:  "Psalm 19:1, 'The heavens declare the glory of God; the skies proclaim the work of his hands.'",
  sh3:  "Genesis 1:31, 'God saw all that he had made, and it was very good.'",
  sh4:  "Psalm 104:24, 'How many are your works, Lord! In wisdom you made them all.'",
  sh5:  "Psalm 139:14, 'I praise you because I am fearfully and wonderfully made.'",
  sh6:  "Genesis 9:13, 'I have set my rainbow in the clouds as a sign of the covenant.'",
  sh7:  "Psalm 104:24, 'How many are your works, Lord! In wisdom you made them all.'",
  sh8:  "Psalm 19:1, 'The heavens declare the glory of God; the skies proclaim the work of his hands.'",
  sh9:  "Genesis 1:31, 'God saw all that he had made, and it was very good.'",
  sh10: "Psalm 104:24, 'In wisdom you made them all; the earth is full of your creatures.'",
  sh11: "Genesis 9:13, 'I have set my rainbow in the clouds as a sign of the covenant.'",
  sh12: "Psalm 139:14, 'I praise you because I am fearfully and wonderfully made.'",
  sh13: "Psalm 19:1, 'The heavens declare the glory of God; the skies proclaim the work of his hands.'",
  sh14: "Genesis 1:31, 'God saw all that he had made, and it was very good.'",
  sh15: "Psalm 104:24, 'How many are your works, Lord! In wisdom you made them all.'",

  // ── LOIS: ABC ────────────────────────────────────────────────────────────
  abc1:  "John 1:1, 'In the beginning was the Word, and the Word was with God.'",
  abc2:  "Psalm 119:105, 'Your word is a lamp for my feet, a light on my path.'",
  abc3:  "John 1:1, 'In the beginning was the Word, and the Word was with God.'",
  abc4:  "Proverbs 22:6, 'Start children off on the way they should go.'",
  abc5:  "John 1:1, 'In the beginning was the Word.'",
  abc6:  "Psalm 119:105, 'Your word is a lamp for my feet, a light on my path.'",
  abc7:  "2 Timothy 3:16, 'All Scripture is breathed out by God.'",
  abc8:  "John 1:1, 'In the beginning was the Word, and the Word was with God.'",
  abc9:  "Psalm 119:11, 'I have hidden your word in my heart.'",
  abc10: "Proverbs 22:6, 'Start children off on the way they should go.'",
  abc11: "John 1:1, 'In the beginning was the Word, and the Word was with God.'",
  abc12: "Psalm 119:105, 'Your word is a lamp for my feet.'",
  abc13: "2 Timothy 3:16, 'All Scripture is breathed out by God.'",
  abc14: "John 1:1, 'In the beginning was the Word, and the Word was with God.'",
  abc15: "Proverbs 22:6, 'Start children off on the way they should go.'",
  abc16: "Psalm 119:105, 'Your word is a lamp for my feet, a light on my path.'",
  abc17: "John 1:1, 'In the beginning was the Word, and the Word was with God.'",
  abc18: "Psalm 119:11, 'I have hidden your word in my heart.'",
  abc19: "John 1:1, 'In the beginning was the Word, and the Word was with God.'",
  abc20: "2 Timothy 3:16, 'All Scripture is breathed out by God and profitable for teaching.'",

  // ── LOIS: NUMBERS ────────────────────────────────────────────────────────
  n1:   "Psalm 147:4, 'He determines the number of the stars and calls them each by name.'",
  n2:   "Matthew 10:30, 'Even the very hairs of your head are all numbered.'",
  n3:   "Genesis 1:5, 'There was evening, and there was morning, the first day.'",
  n4:   "Psalm 147:4, 'He determines the number of the stars and calls them each by name.'",
  n5:   "Matthew 10:30, 'Even the very hairs of your head are all numbered.'",
  n6:   "Genesis 1:31, 'There was evening, and there was morning, the sixth day.'",
  n7:   "Psalm 147:4, 'He determines the number of the stars and calls them each by name.'",
  n8:   "Matthew 10:30, 'Even the very hairs of your head are all numbered.'",
  n9:   "Psalm 90:12, 'Teach us to number our days.'",
  n10:  "Psalm 147:4, 'He determines the number of the stars and calls them each by name.'",

  // ── LOIS: COLORS ─────────────────────────────────────────────────────────
  col1: "Genesis 9:13, 'I have set my rainbow in the clouds as a sign of the covenant.'",
  col2: "Psalm 19:1, 'The heavens declare the glory of God; the skies proclaim the work of his hands.'",
  col3: "Genesis 1:31, 'God saw all that he had made, and it was very good.'",
  col4: "Psalm 104:24, 'How many are your works, Lord! In wisdom you made them all.'",
  col5: "Genesis 9:13, 'I have set my rainbow in the clouds as a sign of the covenant.'",
  col6: "Psalm 19:1, 'The heavens declare the glory of God; the skies proclaim the work of his hands.'",
  col7: "Genesis 1:31, 'God saw all that he had made, and it was very good.'",
  col8: "Psalm 104:24, 'How many are your works, Lord! In wisdom you made them all.'",
  col9: "Genesis 9:13, 'I have set my rainbow in the clouds as a sign of the covenant.'",
  col10:"Psalm 19:1, 'The heavens declare the glory of God.'",

  // ── LOIS: SHAPES ─────────────────────────────────────────────────────────
  "lsh1": "Psalm 104:24, 'How many are your works, Lord! In wisdom you made them all.'",
  "lsh2": "Genesis 1:31, 'God saw all that he had made, and it was very good.'",
  "lsh3": "Psalm 104:24, 'In wisdom you made them all; the earth is full of your creatures.'",
  "lsh4": "Psalm 19:1, 'The heavens declare the glory of God; the skies proclaim the work of his hands.'",
  "lsh5": "Genesis 1:31, 'God saw all that he had made, and it was very good.'",
  "lsh6": "Psalm 104:24, 'How many are your works, Lord! In wisdom you made them all.'",
  "lsh7": "Psalm 19:1, 'The heavens declare the glory of God.'",
  "lsh8": "Genesis 1:31, 'God saw all that he had made, and it was very good.'",

  // ── LITERATURE (wisdom / character) ─────────────────────────────────────
  tl1:  "Proverbs 6:6, 'Go to the ant, you sluggard; consider its ways and be wise!'",
  tl2:  "Galatians 6:9, 'Let us not grow weary of doing good, for in due season we will reap.'",
  tl3:  "Proverbs 17:17, 'A friend loves at all times, and a brother is born for adversity.'",
  tl4:  "Proverbs 12:17, 'An honest witness tells the truth, but a false witness tells lies.'",
  tl5:  "Proverbs 14:29, 'Whoever is patient has great understanding.'",
  tl6:  "Proverbs 26:12, 'Do you see a person wise in their own eyes? There is more hope for a fool than for them.'",
  tl7:  "Proverbs 26:12, 'Do you see a person wise in their own eyes?'",
  tl8:  "Galatians 6:9, 'Let us not grow weary of doing good, for in due season we will reap.'",
  tl9:  "Proverbs 6:6, 'Go to the ant, you sluggard; consider its ways and be wise!'",
  tl10: "Proverbs 17:17, 'A friend loves at all times.'",
  tl11: "Proverbs 19:1, 'Better the poor whose walk is blameless than a fool whose lips are perverse.'",
  tl12: "Proverbs 6:6, 'Go to the ant, you sluggard; consider its ways and be wise!'",
  tl13: "Proverbs 12:17, 'An honest witness tells the truth, but a false witness tells lies.'",
  tl14: "Proverbs 26:12, 'Do you see a person wise in their own eyes?'",
  tl15: "Proverbs 17:17, 'A friend loves at all times, and a brother is born for adversity.'",

  // Mercy literature
  ml1:  "Proverbs 12:17, 'An honest witness tells the truth, but a false witness tells lies.'",
  ml2:  "Galatians 6:9, 'Let us not grow weary of doing good, for in due season we will reap.'",
  ml3:  "Proverbs 17:17, 'A friend loves at all times.'",
  ml4:  "Proverbs 26:12, 'Do you see a person wise in their own eyes?'",
  ml5:  "Proverbs 14:23, 'All hard work brings a profit, but mere talk leads only to poverty.'",
  ml6:  "Proverbs 15:1, 'A gentle answer turns away wrath, but a harsh word stirs up anger.'",
  ml7:  "Proverbs 26:12, 'Do you see a person wise in their own eyes?'",
  ml8:  "Galatians 6:9, 'Let us not grow weary of doing good, for in due season we will reap.'",
  ml9:  "Proverbs 6:6, 'Go to the ant, you sluggard; consider its ways and be wise!'",
  ml10: "Proverbs 17:17, 'A friend loves at all times.'",

  // Lois literature
  ll1:  "Galatians 6:9, 'Let us not grow weary of doing good.'",
  ll2:  "Proverbs 6:6, 'Go to the ant, you sluggard; consider its ways and be wise!'",
  ll3:  "Proverbs 17:17, 'A friend loves at all times.'",
  ll4:  "Proverbs 12:17, 'An honest witness tells the truth.'",
  ll5:  "Philippians 4:11, 'I have learned, in whatever state I am, to be content.'",
};
