import type { Course } from "./types";

// Titus, Dog Training (grammar stage, 3rd grade, age 8). A real, start-to-finish
// program for training LUTHER, the Echols family's wirehaired pointing griffon, to
// hunt dove and quail in West Texas. Taught by Buck, who has trained bird dogs his
// whole life. This is not a pet-tricks course: it follows the actual progression a
// versatile continental pointing breed goes through, from puppy foundations through
// obedience, nose work, bird introduction, pointing and whoa, gun conditioning,
// retrieving and water, West Texas field craft, and finally opening day.
//
// SAFETY: every lesson that involves a firearm, a blank pistol, an e-collar, live
// birds, snakes, or a knife is framed as something Titus does WITH DAD. He is eight.
// The course teaches him to be a real handler, never to work alone with dangerous
// tools. It leans on his gun-safety course rather than repeating it.
//
// These are AI-conductor lessons (no fixed quiz), so Buck teaches each one live,
// and when the authored course is finished the tutor keeps generating fresh dog
// training lessons, so Titus never runs out of things to work on with Luther.
//
// Throughout: dominion is stewardship, not domination (Gen. 1:28), a righteous man
// cares for the needs of his animal (Prov. 12:10), and the patience and gentleness
// a good dog man needs are the same fruit the Spirit grows in a boy.

export const TITUS_DOGTRAINING: Course = {
  kidId: "titus",
  subject: "dogtraining",
  subjectLabel: "Dog Training",
  emoji: "🐕",
  gradeLabel: "3rd Grade",
  stage: "grammar",
  overview:
    "Titus's own program for turning Luther, our wirehaired pointing griffon, into a real West Texas bird dog. Buck walks him through it the way it actually goes: learn your breed, build the bond, lay down obedience that holds in the field, wake up the nose, introduce birds the right way, staunch up a point, condition to the gun with Dad, teach a clean retrieve on land and in water, learn the country (heat, cactus, goatheads, and rattlesnakes), and then hunt doves in September and quail in the winter. Every session is short, kind, and repeated, because that is how a dog learns. When the course is done, Buck keeps making new training sessions, so there is always the next thing to work on with Luther.",
  units: [
    {
      id: "titus-dogtraining-u1",
      title: "Unit 1 · Know Your Dog",
      summary: "What a wirehaired pointing griffon is and what God made him to do.",
      lessons: [
        { id: "titus-dogtraining-u1-l1", title: "Meet the Wirehaired Pointing Griffon", objective: "Describe what kind of dog Luther is and where the breed came from.", teach: "Luther is a wirehaired pointing griffon, sometimes called a Korthals griffon after Eduard Korthals, the man who built the breed in Europe in the 1870s. He wanted one dog that could do everything: hunt the field, point birds, swim cold water, and live gently in the house. That is exactly the dog lying at your feet. Knowing what a dog was made for tells you how to train him.", memoryWork: "Luther is a wirehaired pointing griffon, a versatile bird dog." },
        { id: "titus-dogtraining-u1-l2", title: "What 'Versatile' Means", objective: "Explain that a versatile dog hunts, points, retrieves, and tracks.", teach: "Some dogs only point, and some only retrieve. A versatile breed like the griffon does the whole job: he finds the bird, points it so you can walk in, then fetches it after the shot, on land or out of water, and he can track a wounded bird too. That is a lot to teach, so a griffon is trained in steps over years, never all at once. Patience is the price of a versatile dog.", memoryWork: "A versatile dog finds, points, retrieves, and tracks." },
        { id: "titus-dogtraining-u1-l3", title: "Luther's Coat and Body", objective: "Explain how a griffon's wire coat and build fit his work.", teach: "That harsh, wiry outer coat with soft down under it is armor: it turns thorns, mesquite, and cactus, and it keeps him warm in cold water. His beard and eyebrows shield his face. He is a medium dog, strong but not heavy, built to trot all morning instead of sprinting and quitting. God fits a creature to its work, and you can read Luther's job right off his body.", memoryWork: "The wire coat is armor for brush and cold water." },
        { id: "titus-dogtraining-u1-l4", title: "A Griffon's Temperament", objective: "Describe the griffon temperament and why it matters for training.", teach: "Griffons are famously willing, people-loving dogs who want to work WITH you, not out from under you. That is a gift, and it comes with a warning: they are soft-natured, so harsh handling shuts them down fast. With Luther, quiet praise and calm repetition go further than any correction ever will. A soft dog trains up beautifully in kind hands.", memoryWork: "A griffon is soft-natured; be calm, kind, and clear." },
        { id: "titus-dogtraining-u1-l5", title: "Dominion Is Stewardship", objective: "Explain the biblical reason we train and care for a working dog.", teach: "God gave man dominion over the animals (Gen. 1:28), and dominion means responsible care, not bossing a creature around. Proverbs 12:10 says a righteous man cares about the needs of his animal. Training Luther well IS caring for him: a trained dog gets to hunt, run, and be useful instead of being shut in a kennel. You are not breaking his will; you are giving him a job and a place in the family.", memoryWork: "A righteous man cares for the needs of his animal (Prov. 12:10)." },
      ],
    },
    {
      id: "titus-dogtraining-u2",
      title: "Unit 2 · The Bond and the Handler",
      summary: "Become the kind of handler a dog will hunt for.",
      lessons: [
        { id: "titus-dogtraining-u2-l1", title: "Be the Same Person Every Time", objective: "Explain why consistency is the first rule of training.", teach: "A dog cannot read your mind, only your pattern. If 'here' means come today but is ignored tomorrow, the word means nothing. Say a command once, mean it, and help him do it. Being the same person every single time is the whole foundation, and it is harder than it sounds.", memoryWork: "One word, one meaning, every time." },
        { id: "titus-dogtraining-u2-l2", title: "Short Sessions Win", objective: "Explain why training sessions should be short and end well.", teach: "Five to ten good minutes beats an hour of nagging. A young dog's attention is short, and a tired, confused dog learns the wrong lesson. Do a few clean repetitions, praise him big, and quit while he still wants more. Always end on something he does right.", memoryWork: "Short sessions, quit while he still wants more." },
        { id: "titus-dogtraining-u2-l3", title: "Never Train Angry", objective: "Explain why a handler must control his own temper first.", teach: "The day you are frustrated is the day to put the dog up and walk away. Anger teaches a soft dog to fear your voice, and a fearful dog stops hunting boldly. Buck's rule: fix the handler before you fix the dog. Patience and gentleness are fruit the Spirit grows in you (Gal. 5:22-23), and Luther will feel the difference.", memoryWork: "Never train a dog when you are angry." },
        { id: "titus-dogtraining-u2-l4", title: "His Name Means 'Look at Me'", objective: "Teach a dog to respond to his name as attention, not a command.", teach: "'Luther' should mean one thing: eyes on you, something good is coming. Say his name once in a happy voice, and the instant he looks, praise or treat him. Never use his name to scold him, or the name itself starts to mean trouble. A dog who looks at you is a dog you can teach.", memoryWork: "His name means 'look at me,' never a scolding." },
        { id: "titus-dogtraining-u2-l5", title: "The Crate Is His Room", objective: "Explain how crate training helps a hunting dog.", teach: "A crate is not a jail; to a dog it is a den, a quiet place that is his. A crate-trained dog rides safe in the truck, rests between hunts, and settles down in a strange camp. Feed him in it, toss treats in, and never use it as punishment. A dog who loves his crate travels anywhere.", memoryWork: "A crate is a den, never a punishment." },
        { id: "titus-dogtraining-u2-l6", title: "Feeding, Water, and Daily Care", objective: "List the daily care a hunting dog needs from his boy.", teach: "A bird dog needs good food measured out (not a bowl left full all day), clean water always, brushing to keep that wire coat right, nails kept short, and ears checked and dried out after swims. Do it at the same time each day and it becomes a habit instead of a chore. Faithful in the small things is the whole business (Luke 16:10).", memoryWork: "Measured food, clean water, brush, nails, ears." },
      ],
    },
    {
      id: "titus-dogtraining-u3",
      title: "Unit 3 · Yard Obedience",
      summary: "Sit, here, kennel, place, and heel, taught kindly and cold.",
      lessons: [
        { id: "titus-dogtraining-u3-l1", title: "Sit", objective: "Teach 'sit' with a lure and praise.", teach: "Hold a treat at his nose and lift it slowly back over his head; his hind end drops as his nose follows. The moment his tail hits the ground, say 'sit' and praise. Notice you name it AS he does it, not before he understands it. Ten quick reps, then quit.", memoryWork: "Lure the nose up, name it when he sits." },
        { id: "titus-dogtraining-u3-l2", title: "Here (the Recall)", objective: "Teach a happy, reliable recall.", teach: "'Here' is the command that keeps a dog alive, so it must always be the best word he knows. Crouch down, open your arms, call 'here' once in a bright voice, and throw a party when he arrives. Never call him to you and then scold him, and never call him if you cannot make it happen. If he ignores you, go get him cheerfully, do not repeat the word.", memoryWork: "'Here' is always a party, never a scolding." },
        { id: "titus-dogtraining-u3-l3", title: "The Check Cord", objective: "Explain what a check cord is and why every bird dog trainer uses one.", teach: "A check cord is a long rope, twenty to thirty feet, clipped to his collar so he has freedom but you still have a say. It lets you enforce 'here' gently by reeling him in instead of yelling, and later it lets you steady him on birds. Never jerk it hard on a soft dog; just take up slack and guide. The check cord is how you teach obedience at a distance without a fight.", memoryWork: "A check cord gives freedom and still lets you guide." },
        { id: "titus-dogtraining-u3-l4", title: "Kennel Up", objective: "Teach 'kennel' to load into a crate, truck, or blind.", teach: "Point at the crate, say 'kennel,' toss a treat in, and let him follow it. Soon he loads on the word alone. A dog who kennels on command loads into the truck at dark-thirty and settles in a dove blind without a wrestling match. Small commands save big trouble in the field.", memoryWork: "'Kennel' means load up, right now." },
        { id: "titus-dogtraining-u3-l5", title: "Place", objective: "Teach a dog to go to a spot and stay there.", teach: "Put a low cot, mat, or board down, lead him onto it, say 'place,' and reward him for staying. Build up to a minute, then five, with you walking away. 'Place' is the manners command: it keeps him out of the kitchen, calm at the cookout, and parked where you put him. A dog who can hold still is a dog who can hunt.", memoryWork: "'Place' means go there and stay put." },
        { id: "titus-dogtraining-u3-l6", title: "Heel", objective: "Teach a dog to walk at your side on a loose leash.", teach: "Keep him on your left with the leash loose, and the instant he pulls ahead, stop walking or turn the other way. He learns that pulling gets him nowhere and staying at your knee keeps the walk going. Never let a pulling dog reach where he wants; that rewards the pull. Praise the loose leash, not the tight one.", memoryWork: "Pulling stops the walk; a loose leash keeps it going." },
        { id: "titus-dogtraining-u3-l7", title: "Obedience Has to Hold Outside", objective: "Explain why commands must be proofed in new places.", teach: "A dog who is perfect in the living room may be deaf in a pasture full of grasshoppers, because he learned the command AND the room together. So practice everywhere: the yard, the driveway, the field, with wind and birds and other people around. A command is not learned until it works where it is hard.", memoryWork: "Practice everywhere, or he only obeys at home." },
      ],
    },
    {
      id: "titus-dogtraining-u4",
      title: "Unit 4 · Whoa: The Bird Dog Command",
      summary: "Teach the stop-and-freeze command a pointing dog lives by.",
      lessons: [
        { id: "titus-dogtraining-u4-l1", title: "What 'Whoa' Means", objective: "Explain 'whoa' as stop and stand still, not sit.", teach: "'Whoa' means freeze right where you are, standing, until I release you. It is the single most important command a pointing dog knows, because it is what holds him on a bird and stops him from running into a covey. Never let 'whoa' become 'sit'; a sitting dog cannot point. Buck says 'whoa' is the brake pedal on a bird dog.", memoryWork: "'Whoa' means stop and stand still until released." },
        { id: "titus-dogtraining-u4-l2", title: "Teaching Whoa on the Check Cord", objective: "Introduce whoa calmly with a check cord and a hand.", teach: "Walk him on the cord, say 'whoa' once, stop, and gently steady him with a hand under his belly and one at his chest so he stands still. Hold him a couple of seconds, say 'good,' then release him with a different word like 'okay.' You are teaching a picture: the word, then standing frozen. Repeat a few times a day, never dozens.", memoryWork: "Say it once, then help him hold it." },
        { id: "titus-dogtraining-u4-l3", title: "The Release Word", objective: "Explain why a release word is as important as the command.", teach: "If you never tell a dog when he is done, he decides for himself, and that ruins steadiness. Pick one release word, 'okay' or 'all right,' and use nothing else. Whoa lasts until you release him, and that is what will hold him while you walk in on a covey. The release word is the other half of whoa.", memoryWork: "Whoa holds until the release word comes." },
        { id: "titus-dogtraining-u4-l4", title: "Whoa at a Distance", objective: "Build whoa so it works away from the handler.", teach: "Once he holds beside you, start stepping away while he stands, then whoa him a few steps out on the cord, then across the yard. Always walk TO him to release him, never call him out of a whoa, or you teach him that whoa ends when he feels like it. Distance is built slowly, a step at a time.", memoryWork: "Walk to him to release; never call him out of whoa." },
        { id: "titus-dogtraining-u4-l5", title: "Whoa Saves a Dog's Life", objective: "Explain the safety uses of whoa in the field and at home.", teach: "A dog who stops on one word does not run into a road, a rattlesnake, a cactus flat, or in front of a gun. Buck has stopped dogs on the edge of trouble more times than he can count with that one word. That is why whoa is drilled kindly and constantly until it is automatic. Obedience here is not about control; it is about keeping him alive.", memoryWork: "Whoa keeps a dog out of roads, snakes, and gun trouble." },
      ],
    },
    {
      id: "titus-dogtraining-u5",
      title: "Unit 5 · The Nose",
      summary: "How a dog smells, and how to wake up his hunting drive.",
      lessons: [
        { id: "titus-dogtraining-u5-l1", title: "A Dog Lives in a World of Smell", objective: "Explain that a dog's nose is his main sense.", teach: "A dog has hundreds of millions of scent receptors in his nose, far more than a person's, and a big part of his brain is devoted to smell. He does not see a field the way you do; he reads it, like you read a page. Your job is never to teach him to smell, only to help him use what God already gave him.", memoryWork: "You do not teach a nose; you trust it." },
        { id: "titus-dogtraining-u5-l2", title: "Scent Cone and the Wind", objective: "Explain how bird scent drifts downwind in a cone.", teach: "Scent blows off a bird downwind and spreads out like a cone, narrow at the bird and wide far away. That is why a dog swings back and forth: he is cutting across the wind hunting for the edge of that cone, then follows it in, tighter and tighter, to the bird. Learn to check the wind before you turn him loose. Always work a field so the dog can hunt INTO the wind.", memoryWork: "Scent spreads downwind in a cone; hunt into the wind." },
        { id: "titus-dogtraining-u5-l3", title: "Hunt With Your Nose, Not Your Eyes", objective: "Explain the difference between air-scenting and sight-chasing.", teach: "A young dog will try to hunt with his eyes, chasing anything that moves. A finished bird dog carries his head up, catching scent on the breeze. Encourage nose work by hiding things instead of throwing them where he can see. The nose finds birds; the eyes only find trouble.", memoryWork: "Head up and nose working beats eyes chasing." },
        { id: "titus-dogtraining-u5-l4", title: "Wing on a String", objective: "Use a bird wing on a line to spark natural pointing.", teach: "Tie a dove or quail wing to a string on a fishing rod and flick it along the ground where a puppy can see it. His instinct fires; he freezes, stares, maybe creeps. Let him point it, do not let him catch it, and quit after a few passes. It is a taste, not a meal, and it wakes up the pointing instinct God put in him.", memoryWork: "Let him point the wing; never let him catch it." },
        { id: "titus-dogtraining-u5-l5", title: "Drag a Trail", objective: "Teach basic tracking with a scent drag.", teach: "With Dad, tie a dead bird or a wing to a string and drag it thirty yards through grass, then bring Luther to the start and let him work it out to the bird. He learns to put his nose down and follow a line, which is exactly how a versatile dog recovers a runner later. Keep the first trails short and easy so he wins.", memoryWork: "Short easy trails first, so he always wins." },
        { id: "titus-dogtraining-u5-l6", title: "Let Him Run and Learn the Country", objective: "Explain why free running in cover builds a bird dog.", teach: "Before any polish, a young dog needs miles: turned loose in safe country to run, sort out cover, and learn to use his nose and the wind on his own. A dog kept in a yard until he is trained never learns to hunt. Take him out often, let him be a dog, and only then ask for style. Time in the field is the cheapest training there is.", memoryWork: "No shortcut for miles in the field." },
      ],
    },
    {
      id: "titus-dogtraining-u6",
      title: "Unit 6 · Introducing Birds",
      summary: "The step you cannot rush, done in the right order with Dad.",
      lessons: [
        { id: "titus-dogtraining-u6-l1", title: "Birds Make Bird Dogs", objective: "Explain that live birds, not drills, build a pointing dog.", teach: "You can drill a dog in the yard all year and still not have a bird dog. Contact with live birds is what builds desire, and desire is what makes everything else work. Buck's order is simple: birds first, polish later. Never trade bird contacts for obedience drills at this stage.", memoryWork: "Birds make bird dogs." },
        { id: "titus-dogtraining-u6-l2", title: "First Birds Are Pigeons", objective: "Explain why training starts on pigeons rather than wild quail.", teach: "Pigeons are tough, cheap, and fly strong, and they can be used over and over, so they are the standard first training bird. Wild quail are too precious and too smart to waste on a green dog. Start with pigeons in a launcher or planted in cover, and save real coveys for when he is ready. Protect wild birds; they are not practice.", memoryWork: "Train on pigeons; save wild quail for hunting." },
        { id: "titus-dogtraining-u6-l3", title: "Let the First Points Happen", objective: "Explain why you do not correct a young dog on his first birds.", teach: "On his first planted birds, your only job is to stand back and let it happen: he smells the bird, locks up, maybe breaks and chases, and that is fine right now. Correcting a young dog on birds teaches him that birds mean trouble, and a dog who blinks birds is nearly ruined. Build desire now; steadiness comes later. Say nothing, let him be bold.", memoryWork: "Never correct a young dog on his first birds." },
        { id: "titus-dogtraining-u6-l4", title: "Planting a Bird", objective: "Describe how a training bird is planted so the dog must use his nose.", teach: "With Dad, tuck a pigeon into a clump of grass or set it in a launcher, mark the spot, then bring Luther in from downwind so he catches scent on the breeze instead of walking up on it. Change locations every time or he will start hunting the spot instead of the bird. A dog who hunts the field, not the memory, is honest.", memoryWork: "Always bring the dog in from downwind." },
        { id: "titus-dogtraining-u6-l5", title: "Reading a Point", objective: "Describe what a real point looks like.", teach: "A pointing dog on birds goes rigid: head up or forward, tail high and often stiff, one foot sometimes frozen mid-step, muscles locked, eyes fixed. He is telling you 'the bird is right there.' Learn to see the difference between that hard lock and the loose, sniffing dog who is only interested. Reading your dog is half of hunting behind him.", memoryWork: "Head up, tail high, body locked: that is a point." },
        { id: "titus-dogtraining-u6-l6", title: "Walking In on a Point", objective: "Explain how a handler walks in and flushes the bird.", teach: "When Luther locks up, come in calm and quiet, talk to him low ('good boy, whoa'), and walk in past his nose to flush the bird yourself. Never rush up behind him or he will break. In time he will hold while you walk in, and that hold is the whole point of the dog. Steady hands make a steady dog.", memoryWork: "Walk in calm and past his nose; do not rush him." },
      ],
    },
    {
      id: "titus-dogtraining-u7",
      title: "Unit 7 · Staunch on Point",
      summary: "Turn a flash point into a rock-solid stand.",
      lessons: [
        { id: "titus-dogtraining-u7-l1", title: "From Flash Point to Staunch", objective: "Explain what it means for a dog to be staunch on point.", teach: "A young dog often 'flash points,' locking up for a second and then diving in. Staunch means he holds that point until you get there, however long it takes. You build it by pairing his whoa training with real birds, once desire is solid. Time on point is earned in seconds at first, then minutes.", memoryWork: "Staunch means he holds the point until you arrive." },
        { id: "titus-dogtraining-u7-l2", title: "Whoa on Birds", objective: "Combine whoa with a pointed bird.", teach: "Once he points hard and knows whoa cold in the yard, quietly say 'whoa' as he locks up, and steady him on the check cord if he creeps. Praise the standing, never the creeping. The two skills, whoa and pointing, finally come together here, which is why the yard work mattered. Go slow; a rushed dog gets sticky or scared.", memoryWork: "Yard whoa plus real birds equals a staunch point." },
        { id: "titus-dogtraining-u7-l3", title: "Don't Creep", objective: "Explain why a creeping dog bumps birds and how to stop it.", teach: "A creeping dog inches forward until the covey flushes wild and out of range, which ruins the shot for everybody. The fix is not yelling; it is stopping him early with a quiet 'whoa' and holding him with the cord before he takes step two. Reward the freeze; never let creeping pay off with a flush. Wild birds punish creeping all by themselves.", memoryWork: "Stop the creep at step one, not step ten." },
        { id: "titus-dogtraining-u7-l4", title: "Steady to Wing", objective: "Explain 'steady to wing' and why it matters.", teach: "Steady to wing means the dog holds still even when the bird flushes and flies. It keeps him out from under the guns and lets him watch where the bird falls. Build it after he is staunch: whoa him as the bird flies, and hold the cord so breaking simply cannot happen. A dog who stands when birds fly is a safe dog.", memoryWork: "Steady to wing: he stands even when the bird flies." },
        { id: "titus-dogtraining-u7-l5", title: "Honoring Another Dog", objective: "Explain backing, or honoring another dog's point.", teach: "When one dog points and a second dog freezes behind him without stealing the point, that is called backing, or honoring. It is beautiful manners and it keeps two dogs from wrecking a covey. Teach it by whoaing Luther the instant he sees another dog locked up. Good dogs, like good boys, learn to wait their turn.", memoryWork: "Backing means freezing behind another dog's point." },
      ],
    },
    {
      id: "titus-dogtraining-u8",
      title: "Unit 8 · Gun Conditioning (With Dad)",
      summary: "How to introduce the gun so a dog is never gun-shy.",
      lessons: [
        { id: "titus-dogtraining-u8-l1", title: "The Four Rules Come First", objective: "Connect dog training to the gun safety rules he already knows.", teach: "Before a gun ever comes near Luther, the four safety rules apply: treat every gun as loaded, never point it at anything you do not mean to shoot, keep your finger off the trigger, and know what is beyond your target. Titus does not handle the gun in these lessons; Dad does. Your job is the dog. Safety first, every single time.", memoryWork: "The four gun rules never take a day off." },
        { id: "titus-dogtraining-u8-l2", title: "Never Start With a Shotgun", objective: "Explain the biggest mistake that makes dogs gun-shy.", teach: "The fastest way to ruin a bird dog forever is to fire a shotgun over a puppy who is not ready. Gun-shyness is made by people, and it is very hard to undo. Sound is introduced far away, small, and paired with something the dog already loves. Once, gently, is all it takes to lose a dog.", memoryWork: "Gun-shyness is man-made; never surprise a dog with a shot." },
        { id: "titus-dogtraining-u8-l3", title: "Start Small and Far Away", objective: "Describe the gradual sound-conditioning progression.", teach: "With Dad, start with a small sound at a distance while Luther is excited and eating or chasing a bird: hands clapped, then a cap gun or blank pistol a hundred yards off. If he does not care, move a little closer next session. If he flinches, back way off and slow down. Distance is your dial; turn it slowly.", memoryWork: "Small sound, far away, while he is having fun." },
        { id: "titus-dogtraining-u8-l4", title: "Pair the Bang With the Bird", objective: "Explain why the shot should mean 'a bird is coming'.", teach: "The goal is not a dog who tolerates the noise; it is a dog who hears the bang and looks up hard for a falling bird. So Dad fires as a bird flushes, when Luther is locked on it and thrilled. Sound plus bird plus joy equals a dog who loves gunfire. That is a hunting dog.", memoryWork: "The bang should mean 'look up, a bird is falling.'" },
        { id: "titus-dogtraining-u8-l5", title: "Watch for Trouble Signs", objective: "Recognize early signs of a dog going gun-shy.", teach: "Watch him after every shot: ears pinned, tail tucked, running to the truck, quitting the field, or hunting close and worried all mean back off now. Do not push through it and do not scold him for being scared. Go back to distance and birds and rebuild. Reading your dog honestly is more important than finishing today's plan.", memoryWork: "Tail tucked or heading for the truck means back off." },
        { id: "titus-dogtraining-u8-l6", title: "Hunting Safely Around a Dog", objective: "State the field rules for hunting behind a dog.", teach: "Never swing a gun barrel toward a dog, never shoot at a low bird, and know exactly where the dog is before the safety comes off. A steady, whoa-trained dog makes this far easier, which is one more reason for all that yard work. If you cannot find the dog, you do not take the shot. Ever.", memoryWork: "If you do not know where the dog is, do not shoot." },
      ],
    },
    {
      id: "titus-dogtraining-u9",
      title: "Unit 9 · Retrieving",
      summary: "A clean pick up, carry, and delivery to hand.",
      lessons: [
        { id: "titus-dogtraining-u9-l1", title: "Start Retrieving as Play", objective: "Build a natural retrieve through play in a hallway.", teach: "Start in a hallway where the only way back is to you: toss a rolled sock or a soft toy, cheer when he grabs it, and clap him in. Do not chase him and do not snatch it away, or fetch becomes keep-away. Two or three throws, then stop. Most griffons retrieve naturally if you do not spoil the game.", memoryWork: "Two or three throws in a hallway, then quit." },
        { id: "titus-dogtraining-u9-l2", title: "Hold It", objective: "Teach a dog to hold an object calmly.", teach: "Place a soft dummy in his mouth, cup his chin gently, say 'hold,' and praise for two seconds before taking it. Build up slowly, so he does not chomp, drop, or spit it out. A dog who holds correctly delivers birds without mangling them. Calm mouth, calm dog.", memoryWork: "'Hold' means keep it in your mouth, gently." },
        { id: "titus-dogtraining-u9-l3", title: "Deliver to Hand", objective: "Teach the dog to bring the bird all the way to your hand.", teach: "A retrieve is not finished when he picks the bird up; it is finished when it is in your hand. Take it only on a word like 'give,' and never grab at it. If he drops it short, walk backward so he follows you in with it, then take it and praise. Deliver to hand is the difference between a nice dog and a finished dog.", memoryWork: "The retrieve ends in your hand, not on the ground." },
        { id: "titus-dogtraining-u9-l4", title: "A Soft Mouth", objective: "Explain what a soft mouth is and how to protect it.", teach: "A soft mouth means he carries a bird firmly but never crushes or chews it, so it is fit for the table. Never play tug with a retrieving dummy, and never let him crunch and shake a bird. Trade quietly instead of wrestling things out of his mouth. Guard his mouth the way you guard his nose.", memoryWork: "No tug-of-war with a retrieving dog." },
        { id: "titus-dogtraining-u9-l5", title: "Marking a Fall", objective: "Teach a dog to watch and remember where a bird fell.", teach: "A dog who watches the bird fall can go straight to it, which saves crippled birds from being lost. Throw the dummy where he can see it, make him wait a beat before you send him, and only then release him with his name or 'fetch.' Waiting sharpens the mark instead of scattering it. A good marker recovers birds nobody else finds.", memoryWork: "Watch the fall, wait, then go straight to it." },
        { id: "titus-dogtraining-u9-l6", title: "Blind Retrieves and Runners", objective: "Explain how a dog finds a bird he did not see fall.", teach: "Sometimes a bird sails over a fence line and hits the ground running. That is when the tracking work pays: take Luther to the last place you saw it and let him work the scent line out. A versatile griffon is bred to trail a runner, so trust his nose over your guess. Recovering every bird you shoot is a matter of honor.", memoryWork: "Take him to the fall and let his nose do the work." },
      ],
    },
    {
      id: "titus-dogtraining-u10",
      title: "Unit 10 · Water Work",
      summary: "A griffon is a water dog; teach him to love it.",
      lessons: [
        { id: "titus-dogtraining-u10-l1", title: "Never Throw a Dog In", objective: "Explain how to introduce water so a dog is confident.", teach: "Never throw a dog into water, ever; one bad scare can last a lifetime. Start at a shallow pond edge on a warm day and wade in yourself while he follows, or let him follow an older dog. Let him choose the next step every time. Confidence is built at the water's edge, not in the deep end.", memoryWork: "Never throw a dog in; let him wade to you." },
        { id: "titus-dogtraining-u10-l2", title: "First Swim", objective: "Describe a good first swimming experience.", teach: "When he wades out until his feet lift, he will paddle hard and splashy at first, then smooth out as he figures it out. Keep it short, praise like crazy, and get out before he is tired. A griffon's dense coat and love of water make this easy if you never scare him. Short, happy swims build a water dog.", memoryWork: "Short, happy swims, then out before he tires." },
        { id: "titus-dogtraining-u10-l3", title: "Water Retrieves", objective: "Combine retrieving with swimming.", teach: "Toss a floating dummy just a few feet into the water and build distance over weeks, never all at once. Take the delivery to hand right at the bank so he does not learn to drop the bird in the mud. Water retrieves matter in West Texas anytime you hunt doves around a stock tank. Same rules on water as on land: short, clean, happy.", memoryWork: "Build water distance a few feet at a time." },
        { id: "titus-dogtraining-u10-l4", title: "Water Safety", objective: "List the hazards to check before letting a dog swim.", teach: "Check for steep muddy banks he cannot climb out of, blue-green algae, fishing line and hooks, and cold water that saps a dog fast. In West Texas, a stock tank can be trash-filled or fenced with wire under the surface. Dry his ears out afterward to prevent infection. Look before he leaps, because he will not.", memoryWork: "Check the bank, the water, and dry his ears after." },
      ],
    },
    {
      id: "titus-dogtraining-u11",
      title: "Unit 11 · West Texas Field Craft",
      summary: "Heat, cactus, goatheads, and rattlesnakes: our country is hard on dogs.",
      lessons: [
        { id: "titus-dogtraining-u11-l1", title: "Heat Is the Number One Danger", objective: "Recognize and prevent heat stroke in a hunting dog.", teach: "September dove season in West Texas can run near a hundred degrees, and heat kills more bird dogs than anything else. Hunt early morning and evening, carry far more water than you think you need, and watch for heavy roaring panting, a wide bright red tongue, wobbling, or a dog who stops hunting. If you see that, stop, get him wet and in shade, and get help. Never leave a dog in a truck.", memoryWork: "Hunt early, carry water, and quit before he overheats." },
        { id: "titus-dogtraining-u11-l2", title: "Water in the Field", objective: "Plan water for a dog in dry country.", teach: "Out here you cannot count on finding water, so you carry it: a bottle and a collapsible bowl, and you offer it every fifteen or twenty minutes when it is warm, whether he asks or not. A dog that has to hunt thirsty loses his nose, because scenting takes moisture. Watering the dog comes before watering yourself.", memoryWork: "Offer water every fifteen minutes in the heat." },
        { id: "titus-dogtraining-u11-l3", title: "Cactus, Goatheads, and Mesquite", objective: "Protect a dog's feet and eyes in thorny country.", teach: "Prickly pear, cholla, mesquite thorns, and goathead burrs all hide in the same cover quail love. Check his pads, between his toes, his belly, and his eyes after every run, and carry needle-nose pliers or a comb to pull spines out. Boots help on bad flats. Tough country calls for a careful handler.", memoryWork: "Check pads, toes, belly, and eyes after every run." },
        { id: "titus-dogtraining-u11-l4", title: "Rattlesnakes", objective: "Explain rattlesnake danger and how bird dogs are protected from it.", teach: "West Texas has rattlesnakes, and a curious dog often gets bitten in the face. Dad handles this part: many hunters use rattlesnake avoidance training, keep the vaccine current, know where the nearest vet is, and hunt after the first hard freeze when snakes den up. If a snake buzzes, whoa the dog and back him out. Never let Titus approach a snake for any reason.", memoryWork: "If a snake buzzes, whoa the dog and back away." },
        { id: "titus-dogtraining-u11-l5", title: "Reading Our Country", objective: "Describe West Texas quail cover and where birds hold.", teach: "Out here quail live in sand shinnery oak, mesquite flats, tall bunch grass, and along weedy draws and fence lines, and they need bare ground to walk on and shade to hide under. Learn to look for a mix of cover and openings, not solid brush and not bare pasture. Hunt the edges. A boy who can read cover finds birds even on a slow day.", memoryWork: "Quail want cover, bare ground, and shade together." },
        { id: "titus-dogtraining-u11-l6", title: "Bobwhite and Blue Quail", objective: "Tell bobwhite and scaled quail apart and how each behaves.", teach: "Bobwhites hold tight for a pointing dog and flush in a covey rise, which is what a young dog needs. Scaled quail, the 'blues,' would rather run flat out on the ground than fly, and they will break a green dog's heart by running out from under his point. Learn to trail running blues with the dog moving, and save your praise for the honest work. Different birds, different game.", memoryWork: "Bobwhites hold; blue quail run." },
        { id: "titus-dogtraining-u11-l7", title: "After the Hunt", objective: "Describe the care a dog needs at the end of a hunting day.", teach: "Water him, look him over nose to tail for cuts, thorns, and burrs, check ears and pads, feed him after he has cooled down, and let him rest. Note anything limping or swollen and tell Dad. The hunt is not over when the guns are cased; it is over when the dog is squared away. That is what it means to care for the needs of your animal.", memoryWork: "The hunt ends when the dog is squared away." },
      ],
    },
    {
      id: "titus-dogtraining-u12",
      title: "Unit 12 · Dove Season",
      summary: "September doves: the young dog's first real hunt.",
      lessons: [
        { id: "titus-dogtraining-u12-l1", title: "Why Doves Come First", objective: "Explain why dove season is a good first hunt for a young dog.", teach: "Dove season opens at the start of September, before quail, and doves give a young dog lots of shooting, lots of falls, and lots of easy retrieves in open country. It is the best classroom there is for a dog fresh off gun conditioning. Do not expect pointing; expect retrieving and manners. Every fall is a lesson.", memoryWork: "Doves teach retrieving; quail teach pointing." },
        { id: "titus-dogtraining-u12-l2", title: "Manners in the Blind", objective: "Describe how a dog should behave in a dove field.", teach: "Doves are hunted sitting still near a water tank, grain field, or sunflower patch, so the dog's whole job is to sit or lie quietly at your side until he is sent. This is where 'place' and 'whoa' earn their keep. A dog wandering the field flares birds for everybody. Stillness is the skill of the day.", memoryWork: "In the dove field, stillness is the skill." },
        { id: "titus-dogtraining-u12-l3", title: "Send Him for the Bird", objective: "Explain sending a dog for a downed dove.", teach: "Let him watch the bird fall, hold him a moment so he marks it, then send him with his name or 'fetch.' Take the delivery to hand and praise him warmly. Doves are small and soft, so this is where his soft mouth matters. One clean retrieve at a time.", memoryWork: "Mark it, wait, send him, take it to hand." },
        { id: "titus-dogtraining-u12-l4", title: "Heat and Doves", objective: "Apply heat safety to a September dove hunt.", teach: "Opening-day doves come in the hottest part of the year, so shade the dog, water him constantly, and cut the hunt short before he is spent. A young dog worked to exhaustion in that heat can be hurt or worse. Buck would rather lose an hour of shooting than a good dog. Watch the dog, not the birds.", memoryWork: "In September, watch the dog before the birds." },
        { id: "titus-dogtraining-u12-l5", title: "Rules and Limits", objective: "Explain licenses, bag limits, and legal hours as stewardship.", teach: "Doves have a bag limit, legal shooting hours, and license requirements, and grown-ups also need a migratory bird endorsement in Texas. These rules keep the flocks healthy for years to come, and obeying them honors God and the people He set over us (Rom. 13:1). Know the rules before you go, count your birds, and never fudge. A game hog is no sportsman.", memoryWork: "Know the limit, obey the hours, count every bird." },
      ],
    },
    {
      id: "titus-dogtraining-u13",
      title: "Unit 13 · Quail Season",
      summary: "Winter quail: everything Luther has learned, put together.",
      lessons: [
        { id: "titus-dogtraining-u13-l1", title: "Hunting a Covey", objective: "Describe how a hunt on a covey of quail unfolds.", teach: "Luther quarters into the wind, catches scent, and locks up on point; you walk in past his nose while he holds; the covey roars up all at once; Dad shoots; then Luther is sent to fetch. Every unit of this course shows up in those thirty seconds. That is why you drilled whoa in the yard all summer.", memoryWork: "Point, walk in, flush, shot, retrieve." },
        { id: "titus-dogtraining-u13-l2", title: "Singles After the Rise", objective: "Explain hunting singles after a covey scatters.", teach: "When a covey breaks up, the singles land scattered and hold very tight, which is wonderful pointing work for a dog. Mark where they went, give them a minute, then work the area slowly into the wind. Buck says leave a few birds in every covey so it can rebuild for next year. Never shoot a covey down to nothing.", memoryWork: "Leave birds in every covey for next year." },
        { id: "titus-dogtraining-u13-l3", title: "When Blues Run", objective: "Handle a dog on running scaled quail.", teach: "Scaled quail will trot away under a point and leave your dog standing over nothing, and a young dog gets frustrated. Do not scold him for that; keep him moving with you and let him relocate on his own. Learning to trail running birds without busting them takes a couple of seasons. Patience is the whole trade.", memoryWork: "On running blues, let him relocate; do not scold." },
        { id: "titus-dogtraining-u13-l4", title: "Cold, Wind, and Short Days", objective: "Adjust to winter hunting conditions in West Texas.", teach: "Quail season runs through the cold months, when a hard wind can make scenting difficult and short days cut your time. Wind that is howling scatters scent, so hunt tighter cover and slow down. A griffon's coat handles the cold fine, but check his pads for cracks and ice-hard ground. Read the weather like you read the dog.", memoryWork: "Hard wind scatters scent; slow down and hunt tight cover." },
        { id: "titus-dogtraining-u13-l5", title: "Cleaning Birds and Giving Thanks", objective: "Handle harvested birds well and give God thanks.", teach: "Field-dress birds promptly, keep them cool, and clean them with an adult, cutting away from yourself. Waste none of what you take. Then thank God at the table: the same Lord who feeds the birds of the air (Matt. 6:26) fed your family through a boy, a dog, and a good morning in His field. That is a day worth remembering.", memoryWork: "Waste nothing, and thank God who provided it." },
      ],
    },
    {
      id: "titus-dogtraining-u14",
      title: "Unit 14 · Keeping Luther Sharp",
      summary: "Off season, health, testing, and a lifetime of training.",
      lessons: [
        { id: "titus-dogtraining-u14-l1", title: "Off-Season Work", objective: "Plan training between hunting seasons.", teach: "A bird dog does not keep himself sharp. In the off season, run short yard drills on whoa, here, and hold; take him swimming; and get him on a few pigeons so he does not lose his birds. Fifteen minutes a few times a week keeps everything you built. What you do not maintain, you lose.", memoryWork: "A little work every week keeps a bird dog sharp." },
        { id: "titus-dogtraining-u14-l2", title: "Conditioning", objective: "Explain why a hunting dog needs to be physically fit.", teach: "A soft, out-of-shape dog gets hurt and overheats fast, so start road work and running weeks before opening day, building up slowly. Keep him lean; you should feel ribs easily. A fit dog hunts longer, recovers faster, and lives longer. Conditioning is part of caring for him, not extra credit.", memoryWork: "Get him fit weeks before opening day, not on it." },
        { id: "titus-dogtraining-u14-l3", title: "Vet Care and Health", objective: "List the health care a working dog needs.", teach: "Luther needs current shots, heartworm prevention, flea and tick control, dental care, and a checkup before the season. Working dogs also get cuts, torn pads, and eye scratches that need looking at. Tell Dad about anything limping, swollen, or off in his appetite. Good stewardship includes the vet bill.", memoryWork: "Shots, heartworm, and a checkup before the season." },
        { id: "titus-dogtraining-u14-l4", title: "Keep a Training Journal", objective: "Record training sessions to see real progress.", teach: "After each session write three lines: what you worked on, what he did well, and what to fix next time. Over a season that little notebook shows you patterns you would never remember. It also keeps you honest about whether you are actually training or just playing. Write it down; memory lies.", memoryWork: "Three lines after every session: worked on, did well, fix next." },
        { id: "titus-dogtraining-u14-l5", title: "NAVHDA and Testing", objective: "Explain what a versatile hunting dog test is.", teach: "NAVHDA, the North American Versatile Hunting Dog Association, runs tests where dogs are scored on nose, pointing, tracking, water work, and cooperation. Young dogs run the Natural Ability test before sixteen months old, and it is a great way to see honestly where Luther stands. Testing is not about ribbons; it is a mirror. Ask Dad about a chapter near us.", memoryWork: "NAVHDA Natural Ability is run before sixteen months old." },
        { id: "titus-dogtraining-u14-l6", title: "A Dog Is a Long Work", objective: "Explain that training a bird dog takes years of faithfulness.", teach: "Nobody finishes a bird dog in a summer. A griffon usually takes two or three seasons to really come together, and there will be days when nothing goes right. Keep showing up, keep it short, keep it kind, and let him grow. The boy is being trained here too, in patience, gentleness, and faithfulness, and that is the better half of the work.", memoryWork: "Show up, keep it short, keep it kind, and give it years." },
      ],
    },
  ],
};
