import type { Course } from "./types";

// Titus, 3rd Grade Literature (grammar stage). MCA/Memoria model: 3rd grade is the
// year of great stories well told. Aesop's fables and their morals, D'Aulaires' Greek
// myths, Pilgrim's Progress at a child's level, Narnia, and the classic read-alouds
// (Farmer Boy, Charlotte's Web, Paddington, Mr. Popper's Penguins). Alongside the
// stories, Titus learns the basic tools for talking about a book: character, setting,
// plot, and theme/moral. Grammar-stage goal: memorize morals and key lines, and know
// each story's people, what happens, and what it means. Light outdoors flavor
// throughout. Where a story clearly echoes the gospel we name it plainly; we never
// force a lesson that isn't there.

export const TITUS_LITERATURE: Course = {
  kidId: "titus",
  subject: "literature",
  subjectLabel: "Literature",
  emoji: "📜",
  gradeLabel: "3rd Grade",
  stage: "grammar",
  overview:
    "A full 3rd-grade classical literature year: meet Aesop's fables and say their morals by heart, learn the great Greek myths from D'Aulaires and what they teach, walk with Christian through Pilgrim's Progress, follow Aslan through Narnia, and enjoy the classic read-alouds (Farmer Boy, Charlotte's Web, Paddington, Mr. Popper's Penguins). Along the way Titus picks up the tools of a reader: character, setting, plot, and theme. The grammar-stage goal is a heart full of good stories, their morals memorized, and the beginning of an eye that sees where a story points to Christ.",
  units: [
    {
      id: "titus-literature-u1",
      title: "Unit 1 · The Reader's Toolbox",
      summary: "The four tools for talking about any story: character, setting, plot, theme.",
      lessons: [
        { id: "titus-literature-u1-l1", title: "What Is a Story?", objective: "Explain that a story tells what someone does and what happens because of it.", teach: "A story is a telling of things that happen, usually to somebody, in some order. Every good story has people (or animals, or a tugboat) that we care about, and a problem they have to face. When you read, ask two simple questions: Who is this about, and what happens to them? Those two questions open up every book on the shelf.", memoryWork: "A story tells WHO it is about and WHAT happens to them." },
        { id: "titus-literature-u1-l2", title: "Characters", objective: "Identify the characters in a story and tell who the main one is.", teach: "Characters are the people or creatures a story is about. The main character is the one the story follows most closely, like the hunter you keep your eye on in the field. Some characters are brave, some are foolish, some change from the start of the book to the end. Naming the characters is the first thing a good reader does.", memoryWork: "A character is a person or creature in the story. The main character is the one we follow." },
        { id: "titus-literature-u1-l3", title: "Setting", objective: "Tell where and when a story happens.", teach: "The setting is where and when a story takes place: a New York farm in winter, a barn full of animals, a long muddy road to a shining city. The setting is the world the characters live in, like the woods and water around a fishing hole. Picturing the setting helps the whole story come alive in your mind.", memoryWork: "Setting = WHERE and WHEN the story happens." },
        { id: "titus-literature-u1-l4", title: "Plot", objective: "Retell the beginning, middle, and end of a simple story in order.", teach: "The plot is what happens, in order: a beginning that sets things up, a middle where trouble grows, and an end where it gets settled. A good plot has a problem the character must face and then, at last, an answer to it. When you retell a story, walk through it beginning to middle to end, the way you follow a trail from the truck to the deer stand.", memoryWork: "Plot = beginning, middle, end." },
        { id: "titus-literature-u1-l5", title: "Theme and Moral", objective: "Explain that the theme or moral is the big idea a story teaches.", teach: "The theme, or moral, is the big idea the story leaves you with, the lesson under the story. A fable might teach 'slow and steady wins the race.' A bigger book might teach that pride comes before a fall, or that a real friend lays down his life. As a Christian reader, ask one more question after every story: does this line up with what God says is true? That is how we weigh a story wisely.", memoryWork: "The theme (or moral) is the big idea the story teaches. We always weigh it against God's Word." },
      ],
    },
    {
      id: "titus-literature-u2",
      title: "Unit 2 · Aesop's Fables",
      summary: "Short animal tales with morals to memorize.",
      lessons: [
        { id: "titus-literature-u2-l1", title: "What Is a Fable?", objective: "Explain that a fable is a short story, often with animals, that teaches a moral.", teach: "Aesop was a storyteller long ago, and his fables are short tales, usually about animals who talk and act like people, ending with a moral, a one-line lesson. A fable is small but it packs a punch, like a single well-placed cast. Fables teach us about being wise, honest, humble, and kind by showing foolish creatures learning the hard way.", memoryWork: "A fable is a short story with a moral, often about animals." },
        { id: "titus-literature-u2-l2", title: "The Tortoise and the Hare", objective: "Retell the fable and say its moral.", teach: "A speedy hare mocks a slow tortoise and challenges him to a race. Sure he will win, the hare stops for a nap, while the tortoise plods on without quitting and crosses the line first. The proud, lazy fast one loses to the humble, steady slow one. Faithful, patient work beats flashy bursts that give up, in the field and in life.", memoryWork: "Moral: Slow and steady wins the race." },
        { id: "titus-literature-u2-l3", title: "The Boy Who Cried Wolf", objective: "Retell the fable and say its moral.", teach: "A shepherd boy tricks the village by shouting 'Wolf!' when there is none, laughing as the people come running for nothing. When a real wolf comes and he cries out, no one believes him, and the flock is lost. Lying to get attention costs you the thing you need most: to be believed. God calls His people to be truth-tellers, because a liar is not trusted even when he finally speaks the truth.", memoryWork: "Moral: A liar will not be believed, even when he tells the truth." },
        { id: "titus-literature-u2-l4", title: "The Ant and the Grasshopper", objective: "Retell the fable and say its moral.", teach: "All summer the ant works hard storing food, while the grasshopper sings and plays and stores nothing. When winter comes, the ant is fed and the grasshopper is cold and hungry. There is a time to work and a season to prepare, like putting up meat before a hard winter. Diligence now provides for later; laziness now brings want later.", memoryWork: "Moral: Work while you can, so you are ready for hard times." },
        { id: "titus-literature-u2-l5", title: "The Lion and the Mouse", objective: "Retell the fable and say its moral.", teach: "A great lion catches a tiny mouse but lets him go free. Later the lion is caught in a hunter's net, and the little mouse gnaws the ropes and sets him loose. The mighty lion is saved by the smallest creature he once spared. No kindness is wasted, and no one is too small to help, a truth God delights to prove by using the weak and lowly.", memoryWork: "Moral: A kindness is never wasted; even the small can help the great." },
        { id: "titus-literature-u2-l6", title: "The Fox and the Grapes", objective: "Retell the fable and say its moral.", teach: "A fox spots juicy grapes hanging high, jumps and jumps, and cannot reach them. At last he stalks off sniffing, 'They were probably sour anyway.' When we cannot get what we want, it is easy to pretend we never wanted it, to hide a proud, sulking heart. Aesop calls this out: do not despise a good thing just because you failed to get it.", memoryWork: "Moral: It is easy to despise what you cannot have (sour grapes)." },
      ],
    },
    {
      id: "titus-literature-u3",
      title: "Unit 3 · D'Aulaires' Book of Greek Myths",
      summary: "The great Greek myths and what they teach, read as old stories, not as truth.",
      lessons: [
        { id: "titus-literature-u3-l1", title: "What Is a Myth?", objective: "Explain that myths are old stories the Greeks told, and that we read them as stories, not truth.", teach: "The ancient Greeks made up myths, stories about many gods and heroes, to explain the world before they knew the true God. We read these famous tales because they are woven all through art, language, and other books, and because they show what people believed and longed for. But we read them the way we'd study an old map that got the land wrong: interesting, useful, and not the truth. There is one true God, and the Greek gods are make-believe.", memoryWork: "Myths are old stories the Greeks told. We read them as stories, not as truth. There is one true God." },
        { id: "titus-literature-u3-l2", title: "Prometheus and the Gift of Fire", objective: "Retell the myth and name what it explores.", teach: "In the myth, Prometheus steals fire from the gods and gives it to cold, helpless people, then is punished harshly for it. The Greeks used this tale to explain where mankind's skills came from and to picture sacrifice and suffering for others' good. It shows how people everywhere sensed they needed rescue from above, a longing that points, though the Greeks did not know it, to the true Rescuer who really came.", memoryWork: "Prometheus gave fire to people and suffered for it." },
        { id: "titus-literature-u3-l3", title: "Pandora's Box", objective: "Retell the myth and name what it explores.", teach: "Pandora is given a jar (often called a box) she is told never to open, but curiosity wins and she lifts the lid, letting troubles fly out into the world, with only hope left inside. The Greeks used this story to ask why there is so much trouble and sorrow in the world. The Bible answers the real question: trouble entered through sin in the garden, and our true hope is a Person, Jesus, not a wish left in a jar.", memoryWork: "Pandora opened the forbidden jar and trouble came out. The myth asks where suffering comes from." },
        { id: "titus-literature-u3-l4", title: "King Midas and the Golden Touch", objective: "Retell the myth and say its lesson.", teach: "Greedy King Midas wishes that everything he touches turns to gold, then weeps when his food, his drink, and even his own daughter turn hard and cold. He learns too late that gold cannot feed or hug you. The tale warns against loving money more than people, the same warning Jesus gives when He says you cannot serve both God and riches.", memoryWork: "Lesson: Greed for gold cannot buy what matters most." },
        { id: "titus-literature-u3-l5", title: "Daedalus and Icarus", objective: "Retell the myth and say its lesson.", teach: "The clever craftsman Daedalus builds wax wings so he and his son Icarus can escape a prison island, warning Icarus not to fly too high. Thrilled, Icarus soars toward the sun, the wax melts, and he falls into the sea. The Greeks taught with this story that pride and ignoring wise warnings lead to a fall, an echo of the true proverb that pride goes before destruction.", memoryWork: "Lesson: Pride and ignoring wise warnings lead to a fall." },
        { id: "titus-literature-u3-l6", title: "Heroes: Heracles and Perseus", objective: "Name two Greek heroes and one deed of each.", teach: "The Greeks loved strong heroes. Heracles (Hercules) was famous for his mighty strength and his twelve hard labors, and Perseus was the hero who slew the snake-haired Medusa. These heroes were brave but flawed, and they could not save anyone from sin or death. They show how people have always hungered for a champion, and we know the true and sinless Champion is Christ, who defeated the real enemies of death and evil.", memoryWork: "Heracles = great strength and twelve labors. Perseus = slew Medusa." },
      ],
    },
    {
      id: "titus-literature-u4",
      title: "Unit 4 · The Pilgrim's Progress",
      summary: "John Bunyan's journey of Christian, told at a child's level.",
      lessons: [
        { id: "titus-literature-u4-l1", title: "Christian's Heavy Burden", objective: "Explain that Christian carries a burden of sin and sets out to be free of it.", teach: "John Bunyan wrote The Pilgrim's Progress as a picture story: a man named Christian lives in the City of Destruction with a great heavy burden strapped to his back, which stands for the weight of his sin. He reads in a book that his city will be destroyed, and terrified, he cries, 'What must I do to be saved?' A man named Evangelist points him to a narrow gate and a shining light, and Christian begins his journey. This is a picture of every sinner who feels the weight of sin and starts to seek the Savior.", memoryWork: "Christian's burden is his sin. He cries, 'What must I do to be saved?'" },
        { id: "titus-literature-u4-l2", title: "The Burden Falls at the Cross", objective: "Retell the moment Christian's burden rolls away at the Cross and explain what it means.", teach: "Christian keeps on until he comes to a hill with a Cross on it. The moment he sees the Cross, the heavy burden loosens from his shoulders, tumbles down, rolls into an open tomb, and is gone forever, and Christian leaps for joy and weeps. This is the very heart of the book and of the gospel: our sin is lifted not by our own trying but by Christ, who took it on the Cross. We do not carry our burden to heaven; we lose it at the Cross.", memoryWork: "At the Cross Christian's burden fell off and rolled away. Christ takes away our sin." },
        { id: "titus-literature-u4-l3", title: "Vanity Fair", objective: "Explain what Vanity Fair is and why Christian will not buy its goods.", teach: "Farther on, Christian and his friend Faithful must pass through Vanity Fair, a loud, glittering marketplace selling every worldly pleasure, honor, and treasure to pull travelers off the path. Christian will not buy its goods; he says he seeks only the truth, and the angry crowd mocks and imprisons the pilgrims. Vanity Fair is a picture of the world tempting us to trade heaven for glittering things that do not last. Faithful stays faithful even to death, showing that some things are worth more than life itself.", memoryWork: "Vanity Fair sells the world's goods. The pilgrim will not trade heaven for them." },
        { id: "titus-literature-u4-l4", title: "The Celestial City", objective: "Explain that the Celestial City is the pilgrim's true home, a picture of heaven.", teach: "Christian's whole journey aims at one place: the Celestial City, a shining city on a hill, which stands for heaven where God dwells. At the very end he must cross a deep river (a picture of death) with no bridge, and he is afraid, but he keeps trusting and reaches the far shore, where the gates open and the trumpets sound. The story teaches that the Christian life is a journey home, hard along the way but ending in glory, because the King Himself brings His pilgrims safely in.", memoryWork: "The Celestial City is the pilgrim's true home, a picture of heaven." },
      ],
    },
    {
      id: "titus-literature-u5",
      title: "Unit 5 · Narnia, The Lion, the Witch and the Wardrobe",
      summary: "C.S. Lewis's story, and how Aslan points us to Christ.",
      lessons: [
        { id: "titus-literature-u5-l1", title: "Through the Wardrobe", objective: "Name the four Pevensie children and how they enter Narnia.", teach: "C.S. Lewis wrote The Lion, the Witch and the Wardrobe about four children, Peter, Susan, Edmund, and Lucy, sent to a big old house in the country. Little Lucy climbs into a wardrobe and steps out into Narnia, a snowy land of talking animals held under the spell of an evil White Witch, where it is 'always winter and never Christmas.' A whole new world opens through an ordinary door, the way a wardrobe or a tree line can hide something wonderful just beyond.", memoryWork: "The four children: Peter, Susan, Edmund, and Lucy. Lucy finds Narnia first." },
        { id: "titus-literature-u5-l2", title: "Edmund's Betrayal", objective: "Explain how Edmund is tempted and betrays his family.", teach: "The White Witch tempts Edmund with enchanted Turkish Delight candy and false promises of power, and he greedily betrays his brother and sisters to her. His sin is real and it puts everyone in danger, and by the deep law of Narnia, a traitor's life belongs to the Witch. Edmund shows us how sin starts small and sweet and then enslaves, and how we cannot free ourselves once we are caught.", memoryWork: "Edmund betrays his family for the Witch's candy. Sin looks sweet but enslaves." },
        { id: "titus-literature-u5-l3", title: "Aslan Gives His Life", objective: "Retell how Aslan dies in Edmund's place and rises again.", teach: "Aslan, the great and good Lion who is the true King of Narnia, offers to die in Edmund's place. On the Stone Table the Witch kills him while his friends weep, but at dawn the Table cracks and Aslan is alive again, for a 'deeper magic' says that when a willing, innocent one dies for a traitor, death itself starts working backwards. Lewis is not writing about a nice lion by accident: Aslan lays down his life for a guilty one and rises, just as Jesus died for sinners and rose. Aslan is a picture that points us to Christ.", memoryWork: "Aslan dies in Edmund's place and rises again. He points us to Jesus, who died for sinners and rose." },
        { id: "titus-literature-u5-l4", title: "Winter Breaks, Spring Comes", objective: "Explain how Aslan's return brings the end of the Witch's winter.", teach: "As Aslan comes on the move, the snow melts, streams run, flowers push up, and Father Christmas arrives at last: the Witch's long winter is breaking. Aslan breathes life back into the stone statues she had frozen, and in the final battle her evil reign is ended. When the true King is present, death and winter cannot hold; new life comes. This pictures the good news that Christ the King turns death to life and will one day make all things new.", memoryWork: "When Aslan returns, the Witch's winter melts into spring. The true King brings life." },
      ],
    },
    {
      id: "titus-literature-u6",
      title: "Unit 6 · Classic Read-Alouds",
      summary: "Farmer Boy, Charlotte's Web, Paddington, and Mr. Popper's Penguins.",
      lessons: [
        { id: "titus-literature-u6-l1", title: "Farmer Boy, Almanzo's Year", objective: "Name the main character and the setting, and tell what the book shows about hard work.", teach: "Farmer Boy, by Laura Ingalls Wilder, follows nine-year-old Almanzo Wilder growing up on a New York farm long ago. The book is full of chores, chopping wood, plowing, raising a calf, hauling, from before dawn, plus enormous farm meals and the dream of owning a colt. It shows a boy learning steady work, patience, and responsibility outdoors, the same lessons any hunter or farmer learns close to the land. The theme is that honest, faithful labor grows a boy into a dependable man.", memoryWork: "Farmer Boy is about Almanzo Wilder on a New York farm. Theme: honest hard work builds character." },
        { id: "titus-literature-u6-l2", title: "Charlotte's Web, A Friend Lays Down Her Life", objective: "Name the main characters and explain the theme of sacrificial friendship.", teach: "In E.B. White's Charlotte's Web, a runt pig named Wilbur is saved by a girl named Fern and then befriended by Charlotte, a wise grey spider in the barn. To save Wilbur from being slaughtered, Charlotte spins words like 'SOME PIG' into her web to make him famous, spending her very strength to rescue her friend, and at the end she gives her life having saved his. The great theme is a friend who lays down her life for another, which is the very love Jesus praised: 'Greater love has no one than this, that someone lay down his life for his friends.'", memoryWork: "Charlotte the spider gives her life to save Wilbur. Theme: laying down your life for a friend." },
        { id: "titus-literature-u6-l3", title: "Paddington, A Stranger Welcomed", objective: "Name the main character and setting and tell the book's warm-hearted theme.", teach: "A Bear Called Paddington, by Michael Bond, tells of a polite little bear from Peru found at a London train station with a note reading 'Please look after this bear.' The Brown family takes him in, names him Paddington, and puts up with his good-hearted but disaster-prone adventures. The theme is kindness and welcome, taking in a stranger and treating him as family, which echoes the Bible's call to show hospitality and love to the outsider.", memoryWork: "Paddington is a lost bear the Browns take in. Theme: kindness and welcoming a stranger." },
        { id: "titus-literature-u6-l4", title: "Mr. Popper's Penguins, Delight and Responsibility", objective: "Name the main character and the funny problem, and tell the book's lesson.", teach: "In Mr. Popper's Penguins, by Richard and Florence Atwater, a dreamy house painter who loves the polar regions is mailed a penguin, which soon becomes a whole troupe of penguins living in his house. The funny trouble is that caring for them costs more and more, and Mr. Popper must decide what is best for the penguins even when it means giving them up. Under the laughter is a real lesson: delight is a gift, but love means taking responsibility for what is in your care and doing what is truly best for it.", memoryWork: "Mr. Popper's house fills with penguins. Theme: love means responsibility for what's in your care." },
        { id: "titus-literature-u6-l5", title: "Year Review, Stories and Their Morals", objective: "Recall a favorite story from the year and state its moral, using the reader's toolbox.", teach: "This year Titus met fables, myths, pilgrims, a lion, a spider, and a bear. A good reader can now take any of them and name the character, the setting, the plot, and the theme, and then weigh that theme against God's Word. The best stories do more than entertain; they show us truth, and the very best of them, like the burden falling at the Cross or Aslan rising or Charlotte's sacrifice, point us straight to Jesus. Keep reading good books, and keep asking what they teach.", memoryWork: "For any story: name the character, setting, plot, and theme, then weigh it against God's Word." },
      ],
    },
  ],
};
