import type { Course } from "./types";

// Titus, 3rd Grade Science (grammar stage). Classical-Christian "study of the world
// God made": heavy on memorized classification facts (mammal orders, animal groups,
// body systems, states of matter). The grammar-stage goal is a stocked mind full of
// the names and orders of creation, so Titus can SEE the design and order God built
// into the world (Psalm 19:1; Genesis 1). Hunting/fishing/outdoors scenarios throughout.
// Confessional Reformed Baptist: creation reflects the Creator; evolution is not taught
// as fact. Follows the titus-math.ts template for depth and tone.

export const TITUS_SCIENCE: Course = {
  kidId: "titus",
  subject: "science",
  subjectLabel: "Science",
  emoji: "🔬",
  gradeLabel: "3rd Grade",
  stage: "grammar",
  overview:
    "A full 3rd-grade year studying the world God made. Start by classifying living things (the animal kingdom, the mammal orders, birds, reptiles, amphibians, fish, and insects), then learn life cycles, food chains, and habitats. Study plants and how they grow, the basics of the human body, weather and the seasons, the three states of matter, and simple earth and space. The grammar-stage goal is a mind stocked with the names and orders of creation, so Titus can see the design and order the Creator built into everything (Psalm 19:1).",
  units: [
    {
      id: "titus-science-u1",
      title: "Unit 1 · Living Things & Classification",
      summary: "Sort the animal kingdom: mammals and their orders, birds, reptiles, amphibians, fish, and insects.",
      lessons: [
        { id: "titus-science-u1-l1", title: "Living or Not Living?", objective: "Tell living things from non-living things using the marks of life.", teach: "Scientists sort the world into living and non-living. Living things grow, need food and water, breathe or take in air, and make more of their own kind. A whitetail deer is living: it grows, eats, and has fawns. A rock is not living: it just sits there. God made living things able to reproduce 'after their kind' (Genesis 1), and they always stay that kind.", memoryWork: "Living things grow, need food and water, and make more of their own kind." },
        { id: "titus-science-u1-l2", title: "The Big Groups of Animals", objective: "Name the main groups: mammals, birds, reptiles, amphibians, fish, and insects.", teach: "God made a huge variety of animals, and we sort them into groups by what they have in common. The main groups are mammals, birds, reptiles, amphibians, fish, and insects. A key first split is vertebrates (animals with a backbone, like deer, hawks, and bass) versus invertebrates (no backbone, like insects and worms). Knowing the groups helps you name any critter you meet in the field.", memoryWork: "Six animal groups: mammals, birds, reptiles, amphibians, fish, insects." },
        { id: "titus-science-u1-l3", title: "Mammals", objective: "List the marks of a mammal.", teach: "Mammals are warm-blooded animals with hair or fur that feed their babies milk. A doe is a mammal: she has hair, breathes air with lungs, and nurses her fawn. Almost all mammals are born live instead of hatching from eggs. Deer, bears, foxes, rabbits, and even people are mammals.", memoryWork: "Mammals have hair, breathe air with lungs, are warm-blooded, and feed their babies milk." },
        { id: "titus-science-u1-l4", title: "The Mammal Orders", objective: "Name common mammal orders and an animal in each.", teach: "Mammals are sorted further into orders by their design. Carnivores are meat-eaters with sharp teeth (bobcat, wolf); rodents have gnawing front teeth (squirrel, beaver); primates have hands that grip (monkey, humans); cetaceans live in water (whale, dolphin); and chiroptera are the flying mammals (bats). Learning the orders is like learning the branches on a family tree God designed.", memoryWork: "Mammal orders: carnivores (bobcat), rodents (squirrel), primates (monkey), cetaceans (whale), chiroptera (bat)." },
        { id: "titus-science-u1-l5", title: "Birds, Reptiles & Amphibians", objective: "Give the marks of birds, reptiles, and amphibians.", teach: "Birds are warm-blooded, have feathers and beaks, and lay eggs; a wild turkey is a bird. Reptiles are cold-blooded with dry scales and lay eggs on land; a rattlesnake or turtle is a reptile. Amphibians are cold-blooded, have moist skin, and live part of their life in water and part on land; a frog is an amphibian. Feathers, scales, and moist skin are the quick way to tell them apart.", memoryWork: "Birds have feathers; reptiles have dry scales; amphibians have moist skin." },
        { id: "titus-science-u1-l6", title: "Fish & Insects", objective: "Give the marks of fish and insects.", teach: "Fish are cold-blooded, live in water, breathe with gills, and have fins and scales; a largemouth bass is a fish. Insects are the biggest animal group of all: they have six legs, three body parts (head, thorax, abdomen), and most have wings. A grasshopper is an insect. Remember: a spider is NOT an insect, because it has eight legs.", memoryWork: "Fish breathe with gills and have fins. Insects have six legs and three body parts." },
      ],
    },
    {
      id: "titus-science-u2",
      title: "Unit 2 · Life Cycles, Food Chains & Habitats",
      summary: "How living things grow, who eats whom, and where each creature lives.",
      lessons: [
        { id: "titus-science-u2-l1", title: "Life Cycles", objective: "Describe the life cycle of an animal from birth to adult.", teach: "Every living thing has a life cycle: it is born or hatched, it grows, it becomes an adult, and it makes young of its own kind. A whitetail is born a fawn, grows into a doe or buck, and has fawns of its own. God set this cycle in motion at creation, and each kind keeps producing its own kind.", memoryWork: "A life cycle: born or hatched, grow, become an adult, make young of the same kind." },
        { id: "titus-science-u2-l2", title: "Metamorphosis", objective: "Explain how some animals change form as they grow.", teach: "Some animals go through metamorphosis, a big change in body form. A butterfly starts as an egg, becomes a caterpillar, forms a chrysalis, then comes out a butterfly. A frog starts as an egg, becomes a tadpole with a tail and gills, then grows legs and lungs to become a frog. It is one of the clearest pictures of God's careful design.", memoryWork: "Butterfly life cycle: egg, caterpillar, chrysalis, butterfly." },
        { id: "titus-science-u2-l3", title: "Food Chains", objective: "Build a simple food chain from producer to predator.", teach: "A food chain shows who eats whom, and it always starts with the sun. Plants (producers) make food from sunlight; a grasshopper (herbivore) eats the plant; a frog eats the grasshopper; a hawk (predator) eats the frog. Energy passes up the chain link by link. Every food chain begins with the sun and green plants.", memoryWork: "Food chain: sun to plant to plant-eater to meat-eater." },
        { id: "titus-science-u2-l4", title: "Predator & Prey", objective: "Tell predators from prey and name what each eats.", teach: "A predator hunts and eats other animals; its prey is the animal it eats. A bobcat is a predator; the rabbit is its prey. Herbivores eat only plants (deer, rabbits), carnivores eat only meat (wolves, hawks), and omnivores eat both (bears, people). Knowing what an animal eats tells you a lot about how it lives and hunts.", memoryWork: "Herbivores eat plants; carnivores eat meat; omnivores eat both." },
        { id: "titus-science-u2-l5", title: "Habitats", objective: "Match animals to their habitats and explain what a habitat provides.", teach: "A habitat is the place an animal lives, and it gives four things: food, water, shelter, and space. A bass lives in a lake habitat; a deer lives in a forest habitat; a lizard lives in a desert habitat. God fit each creature to its home, giving it exactly what it needs to live there.", memoryWork: "A habitat gives an animal food, water, shelter, and space." },
      ],
    },
    {
      id: "titus-science-u3",
      title: "Unit 3 · Plants & How They Grow",
      summary: "The parts of a plant, what plants need, and how they make their own food.",
      lessons: [
        { id: "titus-science-u3-l1", title: "The Parts of a Plant", objective: "Name the main parts of a plant and what each one does.", teach: "A plant has parts that each do a job. Roots hold the plant down and drink up water; the stem carries water up and holds the plant tall; leaves catch sunlight to make food; and flowers make seeds for new plants. Like a good fishing rig, every part has a purpose the Maker gave it.", memoryWork: "Roots drink water, stem holds it up, leaves make food, flowers make seeds." },
        { id: "titus-science-u3-l2", title: "What Plants Need to Grow", objective: "List the four things a plant needs to grow.", teach: "Plants are living things, so they need certain things to grow: sunlight, water, air, and soil (for nutrients). Take any one away and the plant will struggle. A sunflower in a dark closet turns yellow and dies because it cannot reach the light it was made to use.", memoryWork: "Plants need sunlight, water, air, and soil to grow." },
        { id: "titus-science-u3-l3", title: "Photosynthesis", objective: "Explain in simple terms how plants make their own food.", teach: "Plants make their own food in a process called photosynthesis. Leaves take in sunlight and air (carbon dioxide) and mix them with water from the roots to make sugar for food, and they give off oxygen we breathe. That is why plants are called producers: they produce the food that starts every food chain. It is a quiet miracle God built into every green leaf.", memoryWork: "Photosynthesis: leaves use sunlight, air, and water to make food and give off oxygen." },
        { id: "titus-science-u3-l4", title: "Seeds & How Plants Spread", objective: "Describe how a seed grows and how seeds travel.", teach: "Inside every seed is a tiny plant waiting to grow. When a seed gets water, warmth, and soil, it germinates (sprouts) and pushes out roots and a stem. Seeds travel to new places by wind (like a dandelion), by water, or by hitching a ride on an animal's fur. God gave plants clever ways to spread far from the parent plant.", memoryWork: "A seed germinates (sprouts) when it gets water, warmth, and soil." },
        { id: "titus-science-u3-l5", title: "Kinds of Plants", objective: "Sort plants into groups like trees, flowering plants, and conifers.", teach: "Plants come in kinds we can sort. Flowering plants make flowers and fruit (an apple tree, a sunflower). Conifers make seeds in cones and keep their needles all year (a pine tree). Non-flowering plants like ferns and moss grow in damp, shady places. Learning the kinds of plants helps you read the woods around a hunting stand.", memoryWork: "Conifers make seeds in cones; flowering plants make seeds in flowers and fruit." },
      ],
    },
    {
      id: "titus-science-u4",
      title: "Unit 4 · The Human Body",
      summary: "The main body systems God designed, from skeleton to senses.",
      lessons: [
        { id: "titus-science-u4-l1", title: "The Skeleton", objective: "Explain what the skeleton does and name a few key bones.", teach: "Your skeleton is the frame of bones inside you. It holds you up, lets you move, and protects your soft parts; the skull guards the brain and the ribs guard the heart and lungs. A grown person has 206 bones. God framed your body with wisdom, and the psalmist says we are 'fearfully and wonderfully made' (Psalm 139:14).", memoryWork: "The skeleton holds you up, lets you move, and protects your organs. An adult has 206 bones." },
        { id: "titus-science-u4-l2", title: "Muscles & Movement", objective: "Explain how muscles work with bones to move the body.", teach: "Muscles are the body parts that pull on your bones to make you move. They work in pairs: to bend your arm, one muscle pulls tight while another relaxes. Your heart is a special muscle that never stops, and muscles get stronger the more you use them, like from drawing a bow. Nothing about your movement is an accident; it was designed.", memoryWork: "Muscles pull on bones to move the body. The heart is a muscle that never rests." },
        { id: "titus-science-u4-l3", title: "The Heart & Blood", objective: "Describe how the heart pumps blood through the body.", teach: "Your heart is a muscle about the size of your fist that pumps blood all through your body. Blood carries oxygen and food to every part and takes away waste. It travels through tubes called blood vessels, and your heartbeat is the sound of the heart pumping. When you run hard chasing a covey of quail, your heart beats faster to send more oxygen to your muscles.", memoryWork: "The heart pumps blood, which carries oxygen and food to every part of the body." },
        { id: "titus-science-u4-l4", title: "Lungs & Breathing", objective: "Explain how the lungs bring oxygen into the body.", teach: "Your two lungs fill your chest and let you breathe. When you breathe in, the lungs pull in air and take the oxygen out of it; when you breathe out, they push out carbon dioxide your body doesn't need. This is the exact opposite of what plants do, and it is how you and the trees help each other. You breathe about 20 times a minute without ever thinking about it.", memoryWork: "Lungs take in oxygen when you breathe in and push out carbon dioxide when you breathe out." },
        { id: "titus-science-u4-l5", title: "The Five Senses", objective: "Name the five senses and the body part for each.", teach: "God gave you five senses to know the world: sight (eyes), hearing (ears), smell (nose), taste (tongue), and touch (skin). Out hunting, you use them all at once: eyes to spot a deer, ears to hear a snapped twig, nose to catch the wind. The brain gathers every signal and puts the whole picture together.", memoryWork: "Five senses: sight (eyes), hearing (ears), smell (nose), taste (tongue), touch (skin)." },
      ],
    },
    {
      id: "titus-science-u5",
      title: "Unit 5 · Weather, Seasons & Matter",
      summary: "The water cycle, weather, the four seasons, and the three states of matter.",
      lessons: [
        { id: "titus-science-u5-l1", title: "The Water Cycle", objective: "Describe the steps of the water cycle.", teach: "Water moves in a never-ending cycle. The sun heats water in lakes and oceans so it evaporates (rises as vapor); up high it cools and condenses into clouds; then it falls back down as precipitation (rain or snow); and it collects again in rivers and lakes. That same lake water you fish in has cycled through the sky more times than anyone can count.", memoryWork: "Water cycle: evaporation, condensation, precipitation, collection." },
        { id: "titus-science-u5-l2", title: "Weather & Clouds", objective: "Identify basic weather and what clouds tell us.", teach: "Weather is what the sky is doing right now: sunny, rainy, windy, or stormy. Clouds give clues about coming weather; big dark clouds often mean rain, while thin high clouds usually mean fair skies. Wind is moving air, and a good hunter watches the wind so his scent doesn't reach the deer. Learning to read the sky is an old outdoorsman's skill.", memoryWork: "Weather is what the sky is doing now. Dark, heavy clouds often mean rain is coming." },
        { id: "titus-science-u5-l3", title: "The Four Seasons", objective: "Name the four seasons and what changes in each.", teach: "The year turns through four seasons: spring (things grow and animals have young), summer (warm and long days), fall (leaves change and animals store food for winter), and winter (cold and short days). The seasons come from the tilt of the earth as it circles the sun. God promised that 'seedtime and harvest' would never cease (Genesis 8:22), and the seasons keep that promise every year.", memoryWork: "Four seasons: spring, summer, fall, winter." },
        { id: "titus-science-u5-l4", title: "The Three States of Matter", objective: "Name the three states of matter and give an example of each.", teach: "Matter is anything that takes up space, and it comes in three states: solid, liquid, and gas. A solid keeps its shape (an ice cube, a rock); a liquid flows and takes the shape of its container (water in a canteen); and a gas spreads out to fill any space (the air you breathe). The same water can be all three: ice, liquid water, and steam.", memoryWork: "Three states of matter: solid, liquid, gas." },
        { id: "titus-science-u5-l5", title: "Changing States", objective: "Explain how heating and cooling change matter from one state to another.", teach: "Heat and cold can change matter from one state to another. Add heat and a solid melts to a liquid (ice to water), and a liquid boils to a gas (water to steam). Take heat away and a gas condenses to a liquid, and a liquid freezes to a solid (water to ice). Nothing is destroyed; the same water just changes form.", memoryWork: "Heat melts and boils; cold condenses and freezes." },
        { id: "titus-science-u5-l6", title: "Solids, Liquids & Gases All Around", objective: "Sort everyday things by their state of matter.", teach: "Once you know the three states, you can sort the whole world. Your tackle box, boots, and a fishing rod are solids; the water in the lake and the oil in a motor are liquids; the air in your tires and the wind in the trees are gases. Practice naming the state of things you see every day until it is automatic.", memoryWork: "Solids hold their shape; liquids flow; gases fill all the space they can." },
      ],
    },
    {
      id: "titus-science-u6",
      title: "Unit 6 · Earth & Space",
      summary: "The sun, the moon, day and night, and why we have seasons.",
      lessons: [
        { id: "titus-science-u6-l1", title: "The Sun", objective: "Explain what the sun is and why it matters to life.", teach: "The sun is a giant star, a ball of burning gas, and it is the center of our solar system. It is far bigger than the earth even though it looks small because it is so far away. The sun gives us light, warmth, and the energy that starts every food chain. On the fourth day of creation God set the sun 'to rule the day' (Genesis 1:16).", memoryWork: "The sun is a star. It gives the earth light, warmth, and energy." },
        { id: "titus-science-u6-l2", title: "Day & Night", objective: "Explain why we have day and night.", teach: "The earth spins like a top, one full turn every 24 hours. The side facing the sun has daytime; the side turned away has nighttime. The sun does not really move across the sky; the earth's spinning just makes it look that way. That is why the best fishing is often at dawn and dusk, when the earth is turning toward or away from the light.", memoryWork: "The earth spins once every 24 hours, giving us day and night." },
        { id: "titus-science-u6-l3", title: "The Moon", objective: "Describe the moon and how it changes shape.", teach: "The moon is the earth's neighbor in space, and it circles the earth about once a month. The moon makes no light of its own; it only reflects the sun's light back to us. As it circles, we see different amounts lit up, called phases: new moon, crescent, half, and full moon. God set the moon 'to rule the night' (Genesis 1:16).", memoryWork: "The moon has no light of its own; it reflects the sun's light. Its shapes are called phases." },
        { id: "titus-science-u6-l4", title: "Why We Have Seasons", objective: "Explain that the earth's tilt causes the seasons.", teach: "The earth is tilted as it travels its year-long path around the sun. When your part of the earth tilts toward the sun, its rays are strong and you get summer; when it tilts away, the rays are weaker and you get winter. The tilt, not the distance from the sun, is what makes the seasons. This steady order is why hunters and farmers can count on fall and spring returning.", memoryWork: "The tilt of the earth as it circles the sun causes the four seasons." },
        { id: "titus-science-u6-l5", title: "The Heavens Declare God's Glory", objective: "Connect the order of creation to the Creator who made it.", teach: "From the mammal orders to the water cycle to the paths of the sun and moon, everything you studied this year runs on order and design. The Bible says 'The heavens declare the glory of God; and the firmament sheweth his handywork' (Psalm 19:1). A good scientist looks closely at the world and, seeing how carefully it is made, gives thanks to the One who made it.", memoryWork: "Psalm 19:1, 'The heavens declare the glory of God.'" },
      ],
    },
  ],
};
