import type { Course } from "./types";

// Titus, 3rd Grade Bible (grammar stage). MCA/Memoria "Christian Studies I" model:
// a chronological walk through redemptive history, Creation to new creation, told
// faithfully and always pointing to Christ. Grammar-stage goal is memorized Scripture,
// the storyline of the Bible in order, and the big arc: creation, fall, redemption,
// new creation. Confessional Reformed Baptist (1689). Scripture handled in context.
// Follows the structure of titus-math.ts.

export const TITUS_BIBLE: Course = {
  kidId: "titus",
  subject: "bible",
  subjectLabel: "Bible",
  emoji: "✝️",
  gradeLabel: "3rd Grade",
  stage: "grammar",
  overview:
    "A full 3rd-grade year walking through the whole Bible in order, the way God tells it: Creation, the Fall, the flood, the fathers of faith, the Exodus and the Law, the Promised Land, the kings, the prophets, exile and return, then Jesus the Messiah, His Cross and Resurrection, the early church, and the promise of a new creation. The grammar-stage goal is to memorize key verses, learn the storyline in order, and see how every part of the Old Testament points to Christ. The big arc to lock in: creation, fall, redemption, new creation.",
  units: [
    {
      id: "titus-bible-u1",
      title: "Unit 1 · Creation & the Fall",
      summary: "How God made a good world, how sin broke it, and the first promise of a Savior.",
      lessons: [
        { id: "titus-bible-u1-l1", title: "In the Beginning, God", objective: "Learn that God created everything out of nothing in six days and called it good.", teach: "Before anything else existed, God was already there. In six days He spoke the heavens, the earth, the light, the seas, the plants, the animals, and everything else into being, and it was all very good (Genesis 1). Nothing made God; God made everything. This is where the whole story starts, and it tells us the world belongs to Him.", memoryWork: "Genesis 1:1, \"In the beginning, God created the heavens and the earth.\"" },
        { id: "titus-bible-u1-l2", title: "Made in God's Image", objective: "Learn that God made people in His own image to know Him, work, and rest.", teach: "On the sixth day God made Adam and Eve in His own image, unlike anything else He made. He placed them in the garden of Eden to care for it, to walk with Him, and to enjoy Him. On the seventh day God rested, teaching us that work is good and rest is a gift. Being made in God's image means every person has real worth because they belong to Him.", memoryWork: "Genesis 1:27, \"God created man in his own image.\"" },
        { id: "titus-bible-u1-l3", title: "The Fall", objective: "Learn how Adam and Eve sinned, what it cost, and the first promise of a Redeemer.", teach: "God gave Adam and Eve one command, but the serpent tempted them and they disobeyed, choosing their own way over God's (Genesis 3). Sin brought shame, hard work, pain, and death into the good world, and it spread to all people ever since. Yet even as He judged, God gave the first promise of a Savior: one who would crush the serpent. From the very start, God planned to rescue.", memoryWork: "Genesis 3:15, God promised the offspring who would \"bruise your head.\"" },
        { id: "titus-bible-u1-l4", title: "Cain and Abel", objective: "Learn how sin grew after the Fall and that God still cares for sinners.", teach: "Adam and Eve's sons Cain and Abel both brought offerings to God, but Cain grew jealous and murdered his brother (Genesis 4). Sin was not a small mistake; it spread quickly and turned brother against brother. Even so, God kept speaking to Cain and kept working out His plan. This shows us that the world truly needed the Savior God had promised.", memoryWork: "Sin \"is crouching at the door\" (Genesis 4:7)." },
        { id: "titus-bible-u1-l5", title: "Noah and the Flood", objective: "Learn how God judged sin with the flood and saved Noah's family by grace.", teach: "The world became so full of evil that God sent a flood to judge it, but Noah found grace in God's eyes (Genesis 6 to 9). God told Noah to build an ark, and He saved Noah, his family, and the animals inside it while the waters covered the earth. Afterward God set a rainbow in the sky as a sign of His covenant promise. The flood shows both God's justice against sin and His mercy in rescuing His people.", memoryWork: "\"Noah found favor in the eyes of the LORD\" (Genesis 6:8)." },
        { id: "titus-bible-u1-l6", title: "The Tower of Babel", objective: "Learn how proud people were scattered and why the nations matter to God's plan.", teach: "The people gathered to build a tower to make a name for themselves instead of honoring God (Genesis 11). God confused their language and scattered them across the earth. This is why there are so many nations and tongues in the world. Remember it, because later God promises to bless all those nations through one family, the family of Abraham.", memoryWork: "Books of the Bible, the Law: Genesis, Exodus, Leviticus, Numbers, Deuteronomy." },
      ],
    },
    {
      id: "titus-bible-u2",
      title: "Unit 2 · The Fathers of Faith",
      summary: "God's covenant promise carried through Abraham, Isaac, Jacob, and Joseph.",
      lessons: [
        { id: "titus-bible-u2-l1", title: "God Calls Abraham", objective: "Learn God's covenant promise to Abraham to bless all the nations.", teach: "God called Abraham to leave his home and go to a land he had never seen, promising to make him a great nation and to bless all the families of the earth through him (Genesis 12). Abraham believed God, and God counted his faith as righteousness. This promise is the thread that runs all the way to Jesus, who came from Abraham's family. God keeps His promises even across many lifetimes.", memoryWork: "\"In you all the families of the earth shall be blessed\" (Genesis 12:3)." },
        { id: "titus-bible-u2-l2", title: "God Provides the Lamb", objective: "Learn how God tested Abraham and provided a substitute, pointing to Christ.", teach: "God tested Abraham by asking him to offer his son Isaac, and Abraham trusted that God would provide (Genesis 22). At the last moment God stopped him and gave a ram caught in a thicket to offer instead. Abraham named the place \"The LORD will provide.\" This account points ahead to the day God would provide His own Son as the Lamb who takes away sin.", memoryWork: "\"God will provide for himself the lamb\" (Genesis 22:8)." },
        { id: "titus-bible-u2-l3", title: "Jacob and the Promise", objective: "Learn how God kept His covenant with Isaac's son Jacob by grace, not merit.", teach: "The promise passed to Isaac, and then to his son Jacob, who was a schemer and far from perfect. Yet God met Jacob in a dream of a ladder reaching to heaven and promised to be with him (Genesis 28). God even renamed him Israel, and his twelve sons became the twelve tribes. God chose Jacob not because he earned it, but because of His own grace, the same grace that saves us.", memoryWork: "\"I am with you and will keep you wherever you go\" (Genesis 28:15)." },
        { id: "titus-bible-u2-l4", title: "Joseph in Egypt", objective: "Learn how God used Joseph's suffering to save many lives.", teach: "Joseph's jealous brothers sold him into slavery in Egypt, but God was with him through prison and hardship until he rose to rule under Pharaoh (Genesis 37 to 45). When famine came, Joseph saved his whole family, the very brothers who had wronged him. God turns even great evil into good for His people.", memoryWork: "\"You meant evil against me, but God meant it for good\" (Genesis 50:20)." },
      ],
    },
    {
      id: "titus-bible-u3",
      title: "Unit 3 · The Exodus & the Law",
      summary: "God rescues Israel from Egypt, gives His Law, and dwells with His people.",
      lessons: [
        { id: "titus-bible-u3-l1", title: "Moses and the Burning Bush", objective: "Learn how God called Moses to lead His people out of slavery.", teach: "Israel had grown into a great people but were slaves in Egypt, crying out under harsh masters. God appeared to Moses in a bush that burned but was not consumed and called him to set His people free (Exodus 3). God revealed His name, \"I AM,\" showing He is the eternal, unchanging God. He heard His people and came down to rescue them.", memoryWork: "\"I AM WHO I AM\" (Exodus 3:14)." },
        { id: "titus-bible-u3-l2", title: "The Passover", objective: "Learn how the blood of the lamb spared Israel, pointing to Christ.", teach: "Pharaoh refused to let Israel go, so God sent ten plagues on Egypt. In the last one, every family was spared only if the blood of a spotless lamb was painted on their doorframe, and death passed over those homes (Exodus 12). Israel walked out free that very night. Centuries later the apostle Paul calls Jesus \"our Passover lamb,\" whose blood saves us from death.", memoryWork: "\"When I see the blood, I will pass over you\" (Exodus 12:13)." },
        { id: "titus-bible-u3-l3", title: "Crossing the Red Sea", objective: "Learn how God delivered Israel through the sea and defeated Pharaoh's army.", teach: "With the sea in front and Pharaoh's chariots behind, Israel was trapped, but God told them to stand still and see His salvation (Exodus 14). He split the sea so they crossed on dry ground, then closed the waters over the army chasing them. Salvation was God's work, not Israel's. They could only trust Him and watch Him save.", memoryWork: "\"The LORD will fight for you, and you have only to be silent\" (Exodus 14:14)." },
        { id: "titus-bible-u3-l4", title: "The Ten Commandments", objective: "Learn that God gave His Law at Sinai to show how His people should live.", teach: "At Mount Sinai God gave Israel the Ten Commandments and His Law, teaching them to love Him first and to love their neighbor (Exodus 20). The Law is good and holy because it reflects God's own character. It also shows us we cannot keep it perfectly, which is why we need a Savior. The Law points us to Christ, who kept it in full for us.", memoryWork: "The first commandment: \"You shall have no other gods before me\" (Exodus 20:3)." },
        { id: "titus-bible-u3-l5", title: "The Tabernacle", objective: "Learn how God chose to dwell among His people through the tabernacle and sacrifices.", teach: "God gave careful plans for the tabernacle, a special tent where He would dwell in the midst of His people (Exodus 25 onward). Priests offered sacrifices there so that sinful people could come near a holy God. Every lamb and every drop of blood pointed forward to Jesus, the perfect sacrifice and the great High Priest. God has always wanted to live among His people.", memoryWork: "Books of the Bible, history: Joshua, Judges, Ruth, 1 and 2 Samuel, 1 and 2 Kings." },
      ],
    },
    {
      id: "titus-bible-u4",
      title: "Unit 4 · The Promised Land & the Kings",
      summary: "Israel enters the land, is ruled by judges, and God raises up David's line.",
      lessons: [
        { id: "titus-bible-u4-l1", title: "Joshua and Jericho", objective: "Learn how God gave Israel the Promised Land as He had promised.", teach: "After Moses died, God chose Joshua to lead Israel into the Promised Land. At Jericho the people marched around the city as God commanded, and on the seventh day the walls fell flat (Joshua 6). God even rescued Rahab, who trusted Him, and she later became part of Jesus' family line. The land was a gift God gave by His power, not something Israel won on their own.", memoryWork: "\"Be strong and courageous... for the LORD your God is with you\" (Joshua 1:9)." },
        { id: "titus-bible-u4-l2", title: "The Judges", objective: "Learn the cycle of sin and rescue in the time of the judges.", teach: "After Joshua, Israel kept turning away from God, so enemies oppressed them; then they cried out and God raised up judges like Gideon and Samson to rescue them (the book of Judges). But soon they would sin again, over and over. This cycle shows that people need more than a temporary rescuer; they need a King who saves forever. \"Everyone did what was right in his own eyes.\"", memoryWork: "\"There was no king in Israel. Everyone did what was right in his own eyes\" (Judges 21:25)." },
        { id: "titus-bible-u4-l3", title: "Ruth the Redeemed", objective: "Learn how God cared for Ruth through a kinsman-redeemer, pointing to Christ.", teach: "Ruth was a foreign widow who trusted the God of Israel and stayed loyal to her mother-in-law Naomi (the book of Ruth). Boaz, a kind relative, became her \"kinsman-redeemer,\" buying back her family's future and marrying her. Their great-grandson was King David, and from that line came Jesus. A redeemer buys back those in need, just as Christ redeems His people.", memoryWork: "\"Your people shall be my people, and your God my God\" (Ruth 1:16)." },
        { id: "titus-bible-u4-l4", title: "Samuel and the First King", objective: "Learn how Israel asked for a king and God gave Saul.", teach: "God called the boy Samuel to be a prophet, and Samuel served Him faithfully all his life (1 Samuel 3). When Israel demanded a king like the other nations, God gave them Saul, but Saul disobeyed and lost the throne. This teaches that a king who looks impressive on the outside is not enough. God was preparing a better king after His own heart.", memoryWork: "\"Speak, LORD, for your servant hears\" (1 Samuel 3:9)." },
        { id: "titus-bible-u4-l5", title: "David the Shepherd King", objective: "Learn how God chose David and promised him an everlasting kingdom.", teach: "God chose David, a shepherd boy, because He looks at the heart, not outward size or strength; young David trusted God and defeated the giant Goliath (1 Samuel 16 to 17). David became a king who loved the Lord, though he sinned and repented. God promised David that one of his descendants would reign forever (2 Samuel 7). That forever-King is Jesus, the Son of David.", memoryWork: "\"The LORD looks on the heart\" (1 Samuel 16:7)." },
        { id: "titus-bible-u4-l6", title: "Solomon and the Temple", objective: "Learn how Solomon built the temple and asked God for wisdom.", teach: "David's son Solomon became king and asked God for wisdom to lead the people, and God gave him wisdom and much more (1 Kings 3). Solomon built the temple in Jerusalem, a permanent house where God's presence dwelt with His people. Yet even wise Solomon later turned his heart away, reminding us no earthly king is perfect. Only Christ is the wise King who never fails.", memoryWork: "\"The fear of the LORD is the beginning of wisdom\" (Proverbs 9:10)." },
      ],
    },
    {
      id: "titus-bible-u5",
      title: "Unit 5 · Prophets, Exile & the Long Wait",
      summary: "The kingdom splits, prophets call the people back, and God keeps His promise through exile and return.",
      lessons: [
        { id: "titus-bible-u5-l1", title: "The Kingdom Divides", objective: "Learn how Israel split into two kingdoms after Solomon.", teach: "After Solomon, the kingdom split in two: Israel in the north and Judah in the south (1 Kings 12). Most of the kings led the people into idol worship and away from God. The nation grew weak because it forgot the Lord who had saved it. Still, God did not abandon His promise to send a Savior from David's line.", memoryWork: "Books of the Bible, the Gospels: Matthew, Mark, Luke, John." },
        { id: "titus-bible-u5-l2", title: "The Prophets Speak", objective: "Learn how God sent prophets to call His people back and to foretell the Messiah.", teach: "God sent prophets like Elijah, Isaiah, and Jeremiah to warn the people, call them to repent, and comfort them with promises (their books in the Old Testament). Elijah showed that the Lord alone is God, not Baal. Isaiah foretold a suffering Servant who would carry our sins hundreds of years before Jesus was born. The prophets kept pointing to the coming Messiah.", memoryWork: "\"He was pierced for our transgressions\" (Isaiah 53:5)." },
        { id: "titus-bible-u5-l3", title: "Exile in Babylon", objective: "Learn how God's people were carried into exile and how He kept them.", teach: "Because Judah kept rejecting God, He allowed Babylon to conquer Jerusalem and carry the people into exile far from home (2 Kings 25). Even there God was with His people, as we see when Daniel stayed faithful in the lions' den and refused to bow to any but the Lord (Daniel 6). Exile was a hard judgment, but God had promised to bring His people back. He is faithful even when we are not.", memoryWork: "\"My God sent his angel and shut the lions' mouths\" (Daniel 6:22)." },
        { id: "titus-bible-u5-l4", title: "The Return and the Long Wait", objective: "Learn how God brought His people home and how they waited for the promised King.", teach: "God kept His word and brought His people back to the land, where Ezra and Nehemiah led them to rebuild the temple and the walls of Jerusalem (Ezra and Nehemiah). Then came about four hundred years with no new word from God, a long, quiet wait. The whole Old Testament ends looking forward, longing for the promised Savior. And then, at just the right time, He came.", memoryWork: "\"The people who walked in darkness have seen a great light\" (Isaiah 9:2)." },
      ],
    },
    {
      id: "titus-bible-u6",
      title: "Unit 6 · Jesus the Messiah",
      summary: "The promised Savior comes: His birth, His life, His Cross, and His Resurrection.",
      lessons: [
        { id: "titus-bible-u6-l1", title: "The Word Became Flesh", objective: "Learn that Jesus, God the Son, was born to save His people.", teach: "At just the right time God sent His Son, born of the virgin Mary in Bethlehem, exactly as the prophets foretold (Luke 2, John 1). Jesus is fully God and fully man, the promised offspring who came to crush the serpent and rescue sinners. The angels announced good news of great joy to shepherds in the field. The long wait was over; the Savior had come.", memoryWork: "\"The Word became flesh and dwelt among us\" (John 1:14)." },
        { id: "titus-bible-u6-l2", title: "Jesus Begins His Work", objective: "Learn how Jesus was baptized, resisted temptation, and called disciples.", teach: "When Jesus was grown, John baptized Him, and the Father spoke from heaven, \"This is my beloved Son\" (Matthew 3). Where Adam and Israel had failed, Jesus faced temptation in the wilderness and obeyed God perfectly (Matthew 4). He called ordinary fishermen and others to follow Him as His disciples. He is the true and faithful Son who does everything the Father sent Him to do.", memoryWork: "\"This is my beloved Son, with whom I am well pleased\" (Matthew 3:17)." },
        { id: "titus-bible-u6-l3", title: "The Parables of the Kingdom", objective: "Learn how Jesus taught about God's kingdom through parables.", teach: "Jesus often taught in parables, short stories about everyday things that reveal the kingdom of God. He told of a sower scattering seed, a lost sheep the shepherd searches for, and a father who runs to welcome home his wayward son (Luke 15). These stories show that God seeks and saves the lost by grace. The kingdom of God grows quietly but surely, like a tiny seed becoming a great tree.", memoryWork: "\"For the Son of Man came to seek and to save the lost\" (Luke 19:10)." },
        { id: "titus-bible-u6-l4", title: "The Signs and Miracles", objective: "Learn how Jesus' miracles showed who He is.", teach: "Jesus healed the sick, calmed a raging storm, fed thousands with a boy's lunch, and even raised the dead (the Gospels). These miracles were signs proving that He is truly God, with power over sickness, nature, and death itself. They also showed His compassion for hurting people. Every sign pointed to Jesus as the promised Savior worthy of our trust.", memoryWork: "\"Even the wind and the sea obey him\" (Mark 4:41)." },
        { id: "titus-bible-u6-l5", title: "The Cross", objective: "Learn that Jesus died in the place of sinners to pay for their sin.", teach: "Though Jesus never sinned, He was arrested, mocked, and nailed to a cross to die (the Gospels). He did this willingly, taking the punishment His people deserved so they could be forgiven. This is the heart of the whole Bible: the true Lamb of God laid down His life for sinners like us. On the cross He cried, \"It is finished,\" because the work of salvation was complete.", memoryWork: "\"It is finished\" (John 19:30)." },
        { id: "titus-bible-u6-l6", title: "He Is Risen", objective: "Learn that Jesus rose from the dead, defeating sin and death.", teach: "On the third day the tomb was empty, and Jesus rose from the dead in victory over sin and death (Luke 24, 1 Corinthians 15). His resurrection proves that God accepted His sacrifice and that everyone who trusts in Him will also live. Death itself has been defeated. This is the best news in all the world, and it is true.", memoryWork: "\"He is not here, for he has risen\" (Matthew 28:6)." },
      ],
    },
    {
      id: "titus-bible-u7",
      title: "Unit 7 · The Church & the New Creation",
      summary: "The good news spreads to the nations, and God promises to make all things new.",
      lessons: [
        { id: "titus-bible-u7-l1", title: "Pentecost and the Church", objective: "Learn how the risen Jesus sent the Holy Spirit and started the church.", teach: "Before returning to heaven, Jesus told His followers to make disciples of all nations and promised to be with them always (Matthew 28, Acts 1). At Pentecost God poured out the Holy Spirit, and the church was born as thousands believed the good news (Acts 2). The same Spirit lives in every believer today. Now the blessing promised to Abraham was reaching the whole world.", memoryWork: "\"You will be my witnesses... to the end of the earth\" (Acts 1:8)." },
        { id: "titus-bible-u7-l2", title: "The Good News Spreads", objective: "Learn how the early church carried the gospel despite hardship.", teach: "The first Christians preached about Jesus boldly, even when they were arrested and persecuted (the book of Acts). Stephen was killed for his faith yet trusted Jesus to the end. Nothing could stop the good news; the more it was opposed, the more it spread. God builds His church, and no enemy can defeat it.", memoryWork: "Books of the Bible, first history of the church: Acts follows the four Gospels." },
        { id: "titus-bible-u7-l3", title: "Paul the Missionary", objective: "Learn how God saved Paul and used him to reach the nations.", teach: "Paul once hunted down Christians, but the risen Jesus met him on the road to Damascus and changed his heart completely (Acts 9). Paul then traveled far and wide planting churches and writing many of the letters in our New Testament. His life shows that God can save even the worst sinner by grace alone. No one is too far gone for God to rescue.", memoryWork: "\"By grace you have been saved through faith... it is the gift of God\" (Ephesians 2:8)." },
        { id: "titus-bible-u7-l4", title: "A New Heaven and a New Earth", objective: "Learn God's promise to make all things new when Christ returns.", teach: "The Bible ends with a promise: Jesus will return, and God will make a new heaven and a new earth where sin, tears, and death are gone forever (Revelation 21 to 22). God's people will live with Him, and He will wipe away every tear. This is where the whole story has been heading, from the garden to the new creation. Creation, fall, redemption, new creation: God finishes what He begins.", memoryWork: "\"Behold, I am making all things new\" (Revelation 21:5)." },
      ],
    },
  ],
};
