import type { Course } from "./types";

// Truma, 6th Grade Writing (grammar stage, TOP of the grammar stage per MCA/Memoria).
// This is a full year of classical composition in the progymnasmata tradition (Memoria
// Press "Classical Composition"): the writing process, strong sentences, the paragraph,
// narrative retelling, the fable and chreia stages, description, summary/précis, the
// five-paragraph essay, and an introduction to persuasion and rhetoric. Truma is a
// capable young scholar, so the depth is real: she learns to say true, good, and
// beautiful things clearly and well. Confessional Reformed Baptist (1689) worldview
// surfaces where it is natural, never bolted on.

export const TRUMA_WRITING: Course = {
  kidId: "truma",
  subject: "writing",
  subjectLabel: "Writing",
  emoji: "✍️",
  gradeLabel: "6th Grade",
  stage: "grammar",
  overview:
    "A full 6th-grade year of classical composition. Truma masters the writing process and the well-built sentence, then the paragraph (topic sentence, support, conclusion). She works the progymnasmata sequence the classical schools have used for centuries: retelling narratives, the fable, and the chreia, then description and the summary/précis. She builds up to the five-paragraph essay with real introductions, conclusions, and transitions, learns to revise and edit her own work, and finishes with an introduction to persuasion and rhetoric. Throughout, the aim is to write what is true, good, and beautiful, clearly and honestly.",
  units: [
    {
      id: "truma-writing-u1",
      title: "Unit 1 · The Writing Process & Strong Sentences",
      summary: "How good writing gets made, and how to build a strong, varied sentence.",
      lessons: [
        { id: "truma-writing-u1-l1", title: "The Writing Process", objective: "Name and use the five stages of the writing process.", teach: "Good writing is not one burst of inspiration; it is a process done in stages. First prewrite (gather ideas, brainstorm, outline), then draft (get it down without worrying it is perfect), then revise (improve the ideas and order), then edit (fix grammar, spelling, punctuation), then publish (share the clean final copy). A carpenter measures and cuts before he sands and finishes. Skipping straight to a 'perfect' first try is the most common reason writing goes badly.", memoryWork: "The writing process: Prewrite, Draft, Revise, Edit, Publish." },
        { id: "truma-writing-u1-l2", title: "The Complete Sentence", objective: "Write complete sentences with a subject and a predicate, and fix fragments.", teach: "A complete sentence expresses one whole thought: it has a subject (who or what it is about) and a predicate (what the subject is or does). 'The morning frost' is a fragment; it names something but does nothing. 'The morning frost covered the field' is a complete sentence, because now the subject 'frost' has a predicate 'covered the field.' If a group of words leaves you waiting for the rest, it is a fragment.", memoryWork: "A sentence needs a subject and a predicate, and expresses a complete thought." },
        { id: "truma-writing-u1-l3", title: "The Four Kinds of Sentences", objective: "Identify and write declarative, interrogative, imperative, and exclamatory sentences.", teach: "Sentences do four jobs. A declarative sentence states something and ends with a period ('God is faithful.'). An interrogative sentence asks and ends with a question mark ('Is the well deep?'). An imperative sentence commands or requests ('Read the passage carefully.'). An exclamatory sentence shows strong feeling and ends with an exclamation point ('What a harvest we had!'). Good writing mostly uses declaratives, saving the others for the right moment.", memoryWork: "Four sentence kinds: declarative (.), interrogative (?), imperative (command), exclamatory (!)." },
        { id: "truma-writing-u1-l4", title: "Sentence Variety", objective: "Combine ideas into simple, compound, and complex sentences.", teach: "Writing that is all short, choppy sentences sounds like a drum machine; writing that is all long sentences tires the reader. Vary them. A simple sentence has one main idea ('The rain fell.'). A compound sentence joins two equal ideas with a comma and a conjunction ('The rain fell, and the river rose.'). A complex sentence adds a dependent idea ('Because the rain fell, the river rose.'). Mix all three so your paragraphs have rhythm.", memoryWork: "Simple = one idea; compound = two equal ideas joined; complex = a main idea plus a dependent one." },
        { id: "truma-writing-u1-l5", title: "Precise Words", objective: "Replace weak, vague words with strong verbs and concrete nouns.", teach: "The right word does the work of ten weak ones. Prefer concrete nouns to vague ones ('sparrow' beats 'thing that flew') and strong verbs to limp ones ('sprinted,' 'trudged,' and 'crept' all beat 'went'). Cut empty fillers like 'very,' 'really,' and 'a lot.' Compare 'The dog went across the yard fast' with 'The hound bolted across the yard.' Fewer words, sharper picture. Since God made a world full of particular things, precise words honor what is really there.", memoryWork: "Strong writing uses concrete nouns and vivid verbs, not 'very' and 'stuff.'" },
      ],
    },
    {
      id: "truma-writing-u2",
      title: "Unit 2 · The Paragraph",
      summary: "Build a real paragraph: topic sentence, support, conclusion, unity.",
      lessons: [
        { id: "truma-writing-u2-l1", title: "The Topic Sentence", objective: "Write a clear topic sentence that states the paragraph's main idea.", teach: "A paragraph is a group of sentences about one idea, and the topic sentence announces that idea (usually first). It should be a clear claim, not just a fact: not 'Autumn' and not 'It was fall,' but 'Autumn is the best season for working outdoors.' Everything else in the paragraph must serve that sentence. A good topic sentence is like a signpost telling the reader exactly where this paragraph is headed.", memoryWork: "The topic sentence states the ONE main idea of the paragraph." },
        { id: "truma-writing-u2-l2", title: "Supporting Details", objective: "Support the topic sentence with reasons, facts, and examples.", teach: "A topic sentence makes a claim; the supporting sentences prove it. Support comes in three main forms: reasons (why it is true), facts (what is measurably so), and examples (a specific instance). For 'Autumn is the best season for working outdoors,' support might be: the air is cool enough to work all day (reason), temperatures drop from ninety to seventy (fact), and last October we cleared the whole field without stopping for heat (example). Aim for three solid supports.", memoryWork: "Support your topic sentence with reasons, facts, and examples." },
        { id: "truma-writing-u2-l3", title: "The Concluding Sentence", objective: "End a paragraph with a sentence that restates or wraps up the main idea.", teach: "A paragraph should not just stop; it should land. The concluding sentence restates the main idea in fresh words or draws it to a close, giving the reader a sense of completion. Do not simply copy the topic sentence, and do not add a brand-new idea. Close of our autumn paragraph: 'For steady, satisfying outdoor work, no season beats the cool clear days of fall.' Same idea, new words, a clean finish.", memoryWork: "The concluding sentence wraps up the main idea in fresh words; no new topics." },
        { id: "truma-writing-u2-l4", title: "Unity: One Idea per Paragraph", objective: "Keep every sentence in a paragraph tied to its topic sentence.", teach: "A paragraph has unity when every sentence serves the topic sentence. The moment a sentence wanders to a new subject, unity breaks and the reader gets lost. In a paragraph about why autumn is good for outdoor work, a sentence about your favorite Thanksgiving pie does not belong, however true it is. Test each sentence: 'Does this help prove my topic sentence?' If not, cut it or move it to its own paragraph.", memoryWork: "Unity = every sentence serves the topic sentence; one idea per paragraph." },
        { id: "truma-writing-u2-l5", title: "Coherence & Transitions", objective: "Order sentences logically and connect them with transition words.", teach: "Coherence means the sentences flow in a sensible order and are linked so the reader is never jolted. Arrange details in a clear order (time order, or order of importance), and use transition words to signal the connections: 'first,' 'next,' 'also,' 'for example,' 'because,' 'as a result,' 'finally.' Without them, sentences feel like a list; with them, they feel like a path. 'The air cools. Also, the light softens. As a result, long work feels lighter.'", memoryWork: "Transition words (first, next, also, because, as a result, finally) connect sentences smoothly." },
      ],
    },
    {
      id: "truma-writing-u3",
      title: "Unit 3 · Narrative, the Fable & the Chreia",
      summary: "Retell a story well, and work the first progymnasmata stages: fable and chreia.",
      lessons: [
        { id: "truma-writing-u3-l1", title: "What Narrative Is", objective: "Understand narrative as telling a story in order with a clear beginning, middle, and end.", teach: "Narrative writing tells what happened, in order. Every good narrative has a beginning (a setting and characters), a middle (events building to a problem), and an end (how it resolves). The oldest way classical students learned to write was by retelling stories they had read, so the skill of ordered storytelling would become second nature. Before you can make your own tale, you learn to carry someone else's faithfully.", memoryWork: "A narrative has a beginning, a middle, and an end, told in order." },
        { id: "truma-writing-u3-l2", title: "Retelling a Story Well", objective: "Retell a known story in your own words, keeping the sequence and key events.", teach: "Retelling is not memorizing word for word; it is telling the same story in your own words while keeping the true sequence and the important events. Keep what matters (who, what happened, how it ended); trim tiny details that do not move the story. A test of a good retelling: someone who never read the original could follow it. Practice by retelling a Bible narrative you know well, such as David and Goliath, in five or six sentences without skipping the turning point.", memoryWork: "A good retelling keeps the order and the key events, in your own words." },
        { id: "truma-writing-u3-l3", title: "The Fable", objective: "Recognize the fable as a short story that teaches a moral, the first progymnasmata stage.", teach: "For over two thousand years, classical students began composition with the fable, a very short story (often with animals) that teaches a lesson. Aesop's fables are the classic examples. A fable has few characters, one quick action, and a moral. In 'The Tortoise and the Hare,' the slow tortoise wins because he never stops, and the moral is 'slow and steady wins the race.' The fable is first because it teaches you to tell a whole story in the smallest space.", memoryWork: "A fable is a short story that teaches a moral; it is the first progymnasmata stage." },
        { id: "truma-writing-u3-l4", title: "Retelling & Expanding a Fable", objective: "Retell a fable and practice varying it (expand, condense, change the order).", teach: "The classical way to learn from a fable is to work it like clay: first retell it faithfully, then practice varying it. Expand it by adding vivid detail and dialogue; condense it to two sentences; or tell it starting from the end and looping back. Each version trains a different muscle. Retell 'The Ant and the Grasshopper' once in a single sentence, then again in a full rich paragraph with description. Same story, stretched and squeezed.", memoryWork: "Vary a fable three ways: retell it, expand it, and condense it." },
        { id: "truma-writing-u3-l5", title: "The Moral: Truth in a Story", objective: "State the moral of a story clearly and connect stories to what is true and good.", teach: "The point of a fable is its moral, the truth it drives home. Learn to state a moral in one clean sentence: not a vague 'be nice,' but a sharp lesson like 'Prepare in good times for hard times to come.' Stories are one of God's chief ways of teaching; even Jesus taught in parables, short stories that carry deep truth. A well-told story makes a true lesson stick where a bare command would slide off.", memoryWork: "The moral is the one-sentence truth a story teaches." },
        { id: "truma-writing-u3-l6", title: "The Chreia", objective: "Understand the chreia: a wise saying or deed of a notable person, the next progymnasmata stage.", teach: "After the fable comes the chreia, a brief, useful anecdote about a wise or famous person, either something they said or something they did. It is prized because it is memorable and instructive. Example: 'When asked how to become wise, the teacher answered, \"Fear the Lord, and listen more than you speak.\"' To work a chreia, you retell it, praise the person, explain why the saying is true, give an example, and add a supporting quotation. It trains you to reflect, not just report.", memoryWork: "A chreia is a short, useful saying or deed of a wise person." },
      ],
    },
    {
      id: "truma-writing-u4",
      title: "Unit 4 · Description & Summary",
      summary: "Paint with words, and boil a text down to its essence honestly.",
      lessons: [
        { id: "truma-writing-u4-l1", title: "Description with the Senses", objective: "Write vivid description using sight, sound, smell, touch, and taste.", teach: "Description makes a reader see, hear, and feel what you saw. The tool is the five senses: sight, sound, smell, touch, taste. Instead of 'the kitchen was nice,' write 'the kitchen smelled of cinnamon, and the kettle hissed on the stove.' Show, do not tell. A rule of thumb: name at least two different senses in any description, so the picture becomes real and not just visual.", memoryWork: "Describe with the five senses: sight, sound, smell, touch, taste. Show, don't tell." },
        { id: "truma-writing-u4-l2", title: "Describing a Person or Place", objective: "Organize a description in a clear spatial or logical order.", teach: "A good description is not a random pile of details; it moves in an order the reader can follow. Describe a place from far to near, or left to right, or top to bottom. Describe a person from overall impression to telling detail. Choose details that reveal character, not every fact: a grandfather's cracked, gentle hands say more than his exact height. Pick a dominant impression and let your details serve it.", memoryWork: "Order a description spatially (near to far, top to bottom) and pick details that reveal." },
        { id: "truma-writing-u4-l3", title: "The Summary (Précis)", objective: "Write a short, accurate summary that captures a text's main points.", teach: "A summary, or précis, restates the main idea and key points of something you read, briefly and in your own words. Leave out examples, repetition, and minor detail; keep the backbone. A summary of a chapter might be three or four sentences. The skill is judgment: knowing what is essential and what is decoration. Rule: a summary should be much shorter than the original yet still make complete sense on its own.", memoryWork: "A summary keeps the main points, drops the details, and is much shorter than the original." },
        { id: "truma-writing-u4-l4", title: "Outlining What You Read", objective: "Make an outline that shows a text's main ideas and supporting points.", teach: "An outline is the skeleton of a text or an essay: main ideas marked with Roman numerals (I, II, III) and their supports indented beneath with letters (A, B, C). Outlining what you read shows you how a writer built the piece; outlining before you write shows you your own plan before you commit to sentences. Outline a paragraph you admire and you will see its bones: the claim on top, the supports underneath.", memoryWork: "Outline form: I, II, III for main ideas; A, B, C for supporting points." },
        { id: "truma-writing-u4-l5", title: "Honest Writing: Paraphrase, Not Plagiarism", objective: "Restate others' ideas in your own words and give credit; never copy as your own.", teach: "To paraphrase is to put someone else's idea fully into your own words and sentence shape, not just to swap a word or two. To plagiarize is to pass another's words or ideas off as your own, which is a form of lying and stealing, and God's people are to be truthful (Exodus 20:15-16). When you use someone's exact words, use quotation marks and name them. Honest writing gives credit where it is due, cheerfully.", memoryWork: "Paraphrase = your own words. Plagiarism = stealing another's words. Always give credit." },
      ],
    },
    {
      id: "truma-writing-u5",
      title: "Unit 5 · The Five-Paragraph Essay",
      summary: "Build a full essay: thesis, body, introduction, conclusion, transitions.",
      lessons: [
        { id: "truma-writing-u5-l1", title: "What an Essay Is & the Thesis", objective: "Understand the essay's shape and write a clear thesis statement.", teach: "An essay is an ordered set of paragraphs that together prove one main point. That main point is the thesis, a single clear sentence stating what the whole essay will argue or explain. A thesis is a claim, not a topic: not 'This essay is about courage,' but 'True courage is doing right while afraid, not feeling no fear at all.' The rest of the essay exists to support that one sentence. Everything hangs on a sharp thesis.", memoryWork: "The thesis is the one-sentence main point the whole essay proves." },
        { id: "truma-writing-u5-l2", title: "The Five-Paragraph Structure", objective: "Lay out the classic five-paragraph essay: intro, three body paragraphs, conclusion.", teach: "The five-paragraph essay is the workhorse structure. Paragraph one is the introduction with the thesis. Paragraphs two, three, and four are the body, each developing one reason or point that supports the thesis. Paragraph five is the conclusion. Think of the thesis as a table and the three body paragraphs as three legs holding it up. Master this shape and you can write clearly about almost anything.", memoryWork: "Five-paragraph essay: introduction, three body paragraphs, conclusion." },
        { id: "truma-writing-u5-l3", title: "Body Paragraphs", objective: "Write body paragraphs that each prove one point supporting the thesis.", teach: "Each body paragraph is a small paragraph unit doing one job: proving one reason the thesis is true. It opens with a topic sentence that states that reason, gives support (reasons, facts, examples), and closes. The three body paragraphs should be ordered on purpose, often saving the strongest point for last. If your thesis is that courage is acting rightly while afraid, one body paragraph might prove it from Scripture, another from history, another from daily life.", memoryWork: "Each body paragraph proves ONE point that supports the thesis." },
        { id: "truma-writing-u5-l4", title: "Introductions & the Hook", objective: "Write an introduction that hooks the reader and leads to the thesis.", teach: "An introduction has a job: catch interest and deliver the thesis. Open with a hook, an interesting question, a striking fact, a short story, or a vivid image, then narrow down to the thesis at the paragraph's end. Do not start with 'In this essay I will tell you about.' Instead: 'A soldier who feels no fear is not brave; he is reckless. Real courage is quieter, and harder.' The reader is caught, and the thesis has arrived.", memoryWork: "Introduction = hook first, thesis last." },
        { id: "truma-writing-u5-l5", title: "Conclusions", objective: "Write a conclusion that restates the thesis and leaves the reader with something.", teach: "A conclusion draws the essay to a satisfying close. Restate the thesis in fresh words, briefly remind the reader of the main points, and end with a final thought that lingers, an application, a call, or a wider truth. Never introduce a new argument here, and never say 'In conclusion.' A strong ending on a courage essay might close by pointing to the ultimate courage of Christ, who set his face toward the cross though he knew its cost.", memoryWork: "Conclusion = restate the thesis, sum up, leave a final thought. No new arguments." },
        { id: "truma-writing-u5-l6", title: "Transitions Between Paragraphs", objective: "Use transitions to link paragraphs so the essay flows as one whole.", teach: "Just as transition words link sentences, transition phrases link paragraphs so the essay reads as one argument, not four islands. Begin body paragraphs with signals of order and relationship: 'First of all,' 'A second reason,' 'Even more important,' 'Finally.' To move into the conclusion, use 'In the end' or 'Taken together.' These bridges tell the reader where you are in the argument and where you are going next.", memoryWork: "Link paragraphs with transitions: First, Second, Even more important, Finally, In the end." },
      ],
    },
    {
      id: "truma-writing-u6",
      title: "Unit 6 · Revising, Editing & an Introduction to Rhetoric",
      summary: "Make good writing better, fix its mechanics, and begin the art of persuasion.",
      lessons: [
        { id: "truma-writing-u6-l1", title: "Revising for Content", objective: "Revise a draft to improve ideas, order, and clarity.", teach: "Revising means 're-seeing.' It is not fixing commas; it is improving the writing itself. Ask the big questions: Is my thesis clear? Does every paragraph support it? Is anything missing, out of order, or off topic? Where is a reader likely to get confused? Cut what does not serve the point, add what is missing, and reorder for the strongest flow. The best writers expect to revise; first drafts are for discovering, later drafts are for shaping.", memoryWork: "Revising fixes IDEAS and ORDER; it happens before editing." },
        { id: "truma-writing-u6-l2", title: "Editing & Proofreading", objective: "Edit a near-final draft for grammar, spelling, punctuation, and capitalization.", teach: "Editing is the last polish: catching errors in grammar, spelling, punctuation, and capitalization so nothing distracts from your ideas. Check one thing at a time, and read slowly, because your eye skips over familiar mistakes. Watch the usual suspects: sentence fragments, run-ons, its/it's, their/there/they're, and missing commas. A clean, careful final copy is a form of respect for your reader.", memoryWork: "Editing fixes MECHANICS: grammar, spelling, punctuation, capitalization." },
        { id: "truma-writing-u6-l3", title: "Reading Aloud & Peer Review", objective: "Improve writing by reading it aloud and receiving feedback well.", teach: "Two of the best editing tools are your own ears and another person's eyes. Reading your writing aloud exposes what your eyes miss: clumsy phrasing, missing words, sentences with no rhythm, if it trips your tongue, it will trip the reader. Peer review means asking someone to read and respond honestly. Receive feedback with humility, not defensiveness; a good critique is a gift, and even the hard parts help you grow.", memoryWork: "Read your work aloud, and welcome honest feedback as a gift." },
        { id: "truma-writing-u6-l4", title: "An Introduction to Persuasion", objective: "Write to persuade: state a claim and give ordered, convincing reasons.", teach: "Persuasive writing tries to convince the reader of a position. It states a clear claim (the thesis), then gives reasons and evidence in order of strength, and fairly answers the strongest objection instead of hiding from it. Persuasion is not manipulation; it is making a true case honestly and well. Example claim: 'Families should share one unhurried meal together every day.' Then give your best reasons, deal with the busy-schedule objection, and close with your strongest point.", memoryWork: "Persuasion: clear claim, ordered reasons, answer the objection, honestly." },
        { id: "truma-writing-u6-l5", title: "Ethos, Pathos, Logos", objective: "Recognize the three classical appeals of rhetoric and use them rightly.", teach: "Rhetoric, the art of speaking and writing persuasively, was one of the crowning classical subjects, and it rests on three appeals. Ethos is the appeal of character: the reader trusts a writer who is honest and fair. Pathos is the appeal to right emotion: stirring compassion or hope. Logos is the appeal to reason: sound logic and real evidence. The best persuasion uses all three in truth. Because a Christian speaks before God, ethos is not a trick to fake; it is real integrity, and logos must rest on what is actually true.", memoryWork: "The three appeals: Ethos (character), Pathos (emotion), Logos (logic)." },
      ],
    },
  ],
};
