import type { Course } from "./types";

// Truma, 6th Grade History (grammar stage). MCA/Memoria model: 6th grade is the
// TOP of the grammar stage, so this is a facts-and-dates medieval history year in
// the spirit of "Famous Men of the Middle Ages": the fall of Rome through the dawn
// of the Renaissance and Reformation, hung on a memorized timeline. Confessional
// Reformed Baptist frame: God is sovereign over the rise and fall of every kingdom,
// and the medieval church is told honestly, its faithfulness and its corruption,
// so the road to the Reformation makes sense. The grammar-stage goal is a firm grip
// on who did what, when, and why it mattered.

export const TRUMA_HISTORY: Course = {
  kidId: "truma",
  subject: "history",
  subjectLabel: "History",
  emoji: "🏛️",
  gradeLabel: "6th Grade",
  stage: "grammar",
  overview:
    "A full 6th-grade year in medieval history, from the fall of Rome to the dawn of the Renaissance and Reformation, in the style of Famous Men of the Middle Ages. Truma meets the great men and women, the decisive battles, and the turning-point ideas of a thousand years, and locks a timeline of key dates into memory. Throughout, we confess that God rules the rise and fall of nations, and we look honestly at the medieval church, both where it was faithful and where its corruption made the Reformation necessary.",
  units: [
    {
      id: "truma-history-u1",
      title: "Unit 1 · The Fall of Rome & the Early Church",
      summary: "How the Roman Empire declined and the church came of age within it.",
      lessons: [
        { id: "truma-history-u1-l1", title: "Constantine and the Cross", objective: "Explain how Constantine changed the standing of the Christian church.", teach: "In 312 the Roman general Constantine marched on Rome and, the story goes, saw a cross of light in the sky with the words 'In this sign conquer.' He won the Battle of the Milvian Bridge, and the next year his Edict of Milan made Christianity legal after nearly three centuries of persecution. In 325 he called the Council of Nicaea, where the bishops affirmed that Jesus is truly and fully God and gave the church the Nicene Creed. God used even a pagan emperor to give His hunted church rest, though earthly power would also bring the church new temptations.", memoryWork: "313, the Edict of Milan makes Christianity legal in the Roman Empire." },
        { id: "truma-history-u1-l2", title: "Augustine of Hippo", objective: "Describe who Augustine was and why the church still reads him.", teach: "Augustine was a brilliant, restless young man in North Africa who chased pleasure and false philosophies until God saved him at thirty-one; he told the story in his Confessions, praying that 'our hearts are restless until they rest in You.' As bishop of Hippo he defended the grace of God against Pelagius, who taught that people can save themselves, insisting instead that salvation is God's gift from first to last. When Rome was sacked he wrote The City of God, showing that God's eternal city outlasts every earthly empire. Reformed Christians treasure Augustine because he saw so clearly that we are saved by grace alone.", memoryWork: "354–430, Augustine of Hippo, author of the Confessions and The City of God." },
        { id: "truma-history-u1-l3", title: "Why Rome Fell", objective: "Identify the main reasons the Western Roman Empire declined.", teach: "Rome did not fall in a single day; it weakened from within for centuries. Heavy taxes crushed the farmers, the army came to depend on hired barbarian soldiers, corrupt emperors rose and fell in quick succession, and the empire simply grew too vast to defend. By the 400s the western half could no longer hold its borders against the tribes pressing in. Historians still argue over the causes, but Scripture reminds us that it is God who raises up kingdoms and brings them down.", memoryWork: "The Western Roman Empire declined slowly through the 300s and 400s." },
        { id: "truma-history-u1-l4", title: "The Barbarians Sack Rome", objective: "Recount the sack of Rome and why it shocked the world.", teach: "In 410 the Visigoths, led by their king Alaric, broke into the city of Rome and plundered it for three days. Rome had not fallen to a foreign enemy in almost eight hundred years, and the news stunned the whole Roman world; many wondered if the end of all things had come. It was this very event that moved Augustine, far away in North Africa, to write The City of God.", memoryWork: "410, the Visigoths under Alaric sack the city of Rome." },
        { id: "truma-history-u1-l5", title: "The Fall of the West & the Barbarian Kingdoms", objective: "Explain the end of the Western Empire in 476 and the kingdoms that replaced it.", teach: "In 476 a barbarian general named Odoacer removed the last western emperor, a boy called Romulus Augustulus, and no new emperor rose to take his place in the West. In Rome's place grew new kingdoms built by Germanic peoples: the Ostrogoths in Italy under Theodoric, the Visigoths in Spain, and the Franks in Gaul under Clovis, who in 496 became the first barbarian king to embrace catholic Christianity. Blending Roman and Germanic ways, these kingdoms became the seedbed of medieval Europe.", memoryWork: "476, the fall of the Western Roman Empire." },
      ],
    },
    {
      id: "truma-history-u2",
      title: "Unit 2 · The Christian East, Islam & the Frankish Kings",
      summary: "Byzantium endures, monks preserve learning, Islam rises, and the Franks lead the West.",
      lessons: [
        { id: "truma-history-u2-l1", title: "Justinian and the Byzantine Empire", objective: "Describe the eastern Roman Empire and the achievements of Justinian.", teach: "While the West fell, the eastern Roman Empire lived on for another thousand years; we call it the Byzantine Empire, with its capital at Constantinople. Its greatest emperor, Justinian, ruled from 527 to 565, reconquered parts of the lost West for a time, and built the breathtaking domed church of Hagia Sophia. His lawyers gathered centuries of Roman law into the Code of Justinian, which still shapes legal systems around the world today.", memoryWork: "527–565, Justinian rules the Byzantine Empire from Constantinople." },
        { id: "truma-history-u2-l2", title: "Benedict and the Monasteries", objective: "Explain how monasteries preserved learning after Rome fell.", teach: "Around 529 a monk named Benedict founded a monastery at Monte Cassino in Italy and wrote a Rule that ordered the monks' lives around prayer and honest work. Through the hard centuries after Rome, monasteries became islands of order where monks copied the Scriptures and ancient books by hand, keeping learning alive for the whole future of Europe. God preserved His written Word, and much of human knowledge with it, through these quiet praying communities.", memoryWork: "529, Benedict founds the monastery at Monte Cassino." },
        { id: "truma-history-u2-l3", title: "Muhammad and the Rise of Islam", objective: "Explain the rise of Islam and how it reshaped the medieval world.", teach: "In Arabia a merchant named Muhammad began, around 610, to preach a new religion called Islam, teaching that there is one god, Allah, and that he was Allah's prophet. His flight from Mecca to Medina in 622, called the Hijra, marks year one of the Muslim calendar. Within a century of his death in 632, his followers had conquered a vast empire stretching from Spain to India, and Islam replaced Christianity across much of North Africa and the Middle East. This is why so much of the medieval story is the meeting, and the clashing, of Christendom and Islam.", memoryWork: "622, the Hijra, Muhammad's flight to Medina; year one of the Muslim calendar." },
        { id: "truma-history-u2-l4", title: "Charles Martel and the Battle of Tours", objective: "Explain why the Battle of Tours was a turning point for Europe.", teach: "As Muslim armies pushed north out of Spain into France, a Frankish leader named Charles Martel, whose name means 'the Hammer,' met them near Tours in 732. His foot soldiers stood firm like a wall and turned back the invasion, halting the advance of Islam into western Europe. Many historians count Tours among the most important battles in all of history.", memoryWork: "732, Charles Martel wins the Battle of Tours." },
        { id: "truma-history-u2-l5", title: "Charlemagne", objective: "Describe Charlemagne's empire and his crowning as emperor.", teach: "Charles Martel's grandson, Charlemagne (Charles the Great), became king of the Franks and built the largest empire the West had seen since Rome, covering much of what is now France, Germany, and Italy. He loved learning, gathered scholars to his court, and started schools, a revival we call the Carolingian Renaissance. On Christmas Day in the year 800 the pope crowned him Emperor of the Romans, joining the old Roman idea to the new Christian kingdoms of the West.", memoryWork: "800, Charlemagne is crowned Emperor on Christmas Day." },
        { id: "truma-history-u2-l6", title: "Alfred the Great", objective: "Explain why Alfred is the only English king called 'the Great.'", teach: "In England, King Alfred of Wessex fought off wave after wave of Viking invaders, and after hiding in the marshes at his lowest point, he defeated them at the Battle of Edington in 878. Alfred was far more than a warrior; he was a devout Christian who translated books into English, built schools, and rooted his laws in Scripture. He remains the only king in English history ever called 'the Great.'", memoryWork: "871–899, the reign of Alfred the Great of England." },
      ],
    },
    {
      id: "truma-history-u3",
      title: "Unit 3 · Vikings, Feudalism & the Norman Conquest",
      summary: "Norse raiders, the feudal order, life on the manor, and 1066.",
      lessons: [
        { id: "truma-history-u3-l1", title: "The Vikings", objective: "Describe who the Vikings were and the mark they left on Europe.", teach: "Beginning in 793 with a raid on the monastery of Lindisfarne, fierce seafaring warriors from Scandinavia, the Vikings, struck the coasts of Europe in their long, swift ships. They raided, traded, and settled from Russia to Ireland, and one of them, Leif Erikson, likely reached North America around the year 1000, nearly five centuries before Columbus. In time the Vikings settled down and became Christians, and their descendants, the Normans, would go on to change history.", memoryWork: "793, the raid on Lindisfarne begins the Viking Age." },
        { id: "truma-history-u3-l2", title: "Feudalism", objective: "Explain the feudal system of land, loyalty, and service.", teach: "With no strong central government after Charlemagne's empire broke apart, a new system called feudalism grew up to give people protection. A king granted land, called a fief, to great lords in exchange for their loyalty and their soldiers; those lords became vassals who swore solemn oaths and supplied knights for war. It was a ladder of promises, land traded for service, running all the way from the king to the least knight.", memoryWork: "Feudalism: land (a fief) granted in exchange for loyalty and military service." },
        { id: "truma-history-u3-l3", title: "The Manor and the Peasants", objective: "Describe daily life on a medieval manor.", teach: "At the base of the feudal world sat the manor, a self-sufficient estate where most people, the peasants or serfs, lived and labored. Serfs farmed the lord's fields and their own narrow strips of land, could not leave without permission, and owed part of their harvest to the lord and a tithe to the church. Life was hard and short, measured by the turning seasons and the ringing of the church bell.", memoryWork: "The manor was a self-sufficient estate worked by peasants called serfs." },
        { id: "truma-history-u3-l4", title: "William the Conqueror & 1066", objective: "Explain the Norman Conquest and its effect on England.", teach: "When the English king died without a clear heir, William, Duke of Normandy, crossed the channel and defeated King Harold at the Battle of Hastings in 1066. Harold died in the fighting, said by tradition to have been struck in the eye by an arrow, and William was crowned king of England on Christmas Day. The Norman Conquest reshaped England's language, laws, and rulers, and William recorded who owned what in the great survey known as the Domesday Book of 1086.", memoryWork: "1066, the Battle of Hastings; William the Conqueror wins England." },
        { id: "truma-history-u3-l5", title: "Knights, Castles & Chivalry", objective: "Describe the world of the medieval knight.", teach: "The armored knight on horseback was the great warrior of the age, trained from boyhood first as a page, then as a squire, before being dubbed a knight. Lords built castles, at first of wood and later of stone, as both fortresses and homes, ringed with thick walls, moats, and towers. Knights were meant to follow a code called chivalry, protecting the weak and honoring the church, though many fell far short of that ideal.", memoryWork: "A boy served as a page, then a squire, before being knighted." },
      ],
    },
    {
      id: "truma-history-u4",
      title: "Unit 4 · Faith, Learning & Law in the High Middle Ages",
      summary: "The Crusades, cathedrals, the friars and universities, Aquinas, and the Magna Carta.",
      lessons: [
        { id: "truma-history-u4-l1", title: "The Crusades", objective: "Explain what the Crusades were and weigh them honestly.", teach: "In 1095 Pope Urban II called on Christian knights to march east and win back the Holy Land, above all Jerusalem, from Muslim rule; thousands answered, sewing crosses onto their clothes. The First Crusade captured Jerusalem in 1099, but across nearly two centuries the Crusades mixed real devotion with terrible bloodshed, including violence against Jews and even fellow Christians. They opened Europe to trade and learning from the East, yet they also show how quickly zeal turns to cruelty when the gospel is joined to the sword.", memoryWork: "1095, Pope Urban II calls the First Crusade." },
        { id: "truma-history-u4-l2", title: "Cathedrals: Faith in Stone", objective: "Describe the great cathedrals and the Gothic style.", teach: "In the high Middle Ages whole towns poured their wealth and skill into soaring stone cathedrals like Notre-Dame in Paris and the cathedral of Chartres. The new Gothic style used pointed arches, ribbed vaults, and flying buttresses to lift walls of colored glass toward heaven, and some took more than a century to complete. For a people who could not read, these buildings preached, telling the Bible's story in stone and stained glass.", memoryWork: "Gothic cathedrals used pointed arches, flying buttresses, and stained glass." },
        { id: "truma-history-u4-l3", title: "Friars and the First Universities", objective: "Explain the rise of the friars and the medieval universities.", teach: "Monks and nuns still filled the monasteries, keeping the hours of prayer, caring for the sick and poor, and copying manuscripts long before the printing press. New orders like the Franciscans, founded by Francis of Assisi, and the Dominicans sent friars out to preach among ordinary people. From the cathedral schools grew the first universities, such as Paris, Oxford, and Bologna, where scholars studied theology, law, and the ancient philosophers.", memoryWork: "The first universities, like Paris and Oxford, grew up in the 1100s and 1200s." },
        { id: "truma-history-u4-l4", title: "Thomas Aquinas", objective: "Describe Aquinas and how Reformed Christians regard him.", teach: "Thomas Aquinas was a Dominican friar and the greatest scholar of the Middle Ages, so quiet as a student that classmates nicknamed him 'the dumb ox,' though his teacher warned that this ox would one day bellow so loud the whole world would hear. In his enormous Summa Theologica he labored to join the reasoning of Aristotle to the truths of the Christian faith. Reformed Christians honor his brilliance while parting from him at key points, for the later Reformers would insist far more sharply on Scripture alone and grace alone.", memoryWork: "1225–1274, Thomas Aquinas, author of the Summa Theologica." },
        { id: "truma-history-u4-l5", title: "The Magna Carta", objective: "Explain the Magna Carta and why it still matters.", teach: "King John of England taxed his barons harshly and lost their trust, so in 1215 they forced him to set his seal to the Magna Carta, the 'Great Charter,' in a meadow at Runnymede. It declared that even the king stands under the law, and that free men cannot be imprisoned or robbed without lawful judgment. This idea, that no ruler is above the law, would echo down the centuries into English liberty and, much later, into the American founding.", memoryWork: "1215, King John seals the Magna Carta." },
      ],
    },
    {
      id: "truma-history-u5",
      title: "Unit 5 · The Late Middle Ages",
      summary: "Marco Polo, the Black Death, Joan of Arc, and the end of the feudal world.",
      lessons: [
        { id: "truma-history-u5-l1", title: "Marco Polo", objective: "Describe Marco Polo's journey and its effect on Europe.", teach: "In 1271 a young Venetian named Marco Polo set out with his father and uncle along the Silk Road to China, then ruled by the mighty Mongol emperor Kublai Khan. He served the Khan for years and returned home after roughly twenty-four years with tales of paper money, coal, and cities far grander than any in Europe. His book, dictated while he was a prisoner of war, filled Europeans with wonder about the East and later helped inspire explorers like Columbus.", memoryWork: "1271, Marco Polo sets out on his journey to China." },
        { id: "truma-history-u5-l2", title: "The Black Death", objective: "Explain the Black Death and how it reshaped Europe.", teach: "In 1347 a terrible plague, the Black Death, arrived in Europe aboard trading ships, spread by fleas riding on rats. In about four years it killed perhaps a third of all the people in Europe, tens of millions of souls, emptying whole villages while no one could stop it. The horror shook people's faith and cracked the old order, for with so few workers left, surviving peasants could demand better lives, and feudalism began to crumble.", memoryWork: "1347–1351, the Black Death kills roughly a third of Europe." },
        { id: "truma-history-u5-l3", title: "Joan of Arc", objective: "Recount the story of Joan of Arc.", teach: "During the long Hundred Years' War between England and France, a French peasant girl named Joan of Arc believed God had called her to rescue her country. In 1429, only about seventeen years old, she led French troops to lift the siege of Orleans and saw her king crowned. Captured and handed to the English, she was tried and burned at the stake in 1431 at just nineteen; centuries later the church declared her a saint.", memoryWork: "1429, Joan of Arc lifts the siege of Orleans." },
        { id: "truma-history-u5-l4", title: "The End of the Medieval World", objective: "Explain how the medieval age drew to a close.", teach: "The Hundred Years' War between England and France (1337 to 1453) dragged on longer than a hundred years and changed how wars were fought, as the English longbow cut down armored knights at battles like Agincourt. New weapons, above all gunpowder and cannon, made stone castles and mounted knights far less useful. Kings grew stronger, nations began to take shape, and the feudal age quietly came to an end.", memoryWork: "1337–1453, the Hundred Years' War between England and France." },
      ],
    },
    {
      id: "truma-history-u6",
      title: "Unit 6 · The Dawn of a New Age",
      summary: "The Renaissance, the printing press, the forerunners of reform, and the eve of the Reformation.",
      lessons: [
        { id: "truma-history-u6-l1", title: "The Renaissance", objective: "Describe the Renaissance and its return to the sources.", teach: "Beginning in the wealthy cities of Italy in the 1300s and 1400s, a 'rebirth' of interest in ancient Greek and Roman learning and art spread across Europe; we call it the Renaissance. Artists like Leonardo da Vinci and Michelangelo, and scholars who read the classics in their original languages, produced astonishing work. That same drive to go back to the original sources sent scholars to study the Bible afresh in its original Hebrew and Greek, which would help prepare the way for reform.", memoryWork: "The Renaissance was a rebirth of ancient learning, beginning in Italy in the 1300s and 1400s." },
        { id: "truma-history-u6-l2", title: "Gutenberg and the Printing Press", objective: "Explain how the printing press changed the world.", teach: "Around 1440 a German named Johann Gutenberg built a printing press with movable metal type, and by about 1455 he had printed a whole Bible. Before this, every book had to be copied by hand, so books were rare and costly and few people owned even one. This single invention let ideas, and above all the Scriptures, spread across Europe faster than ever before, an ordinary machine that God would use to change the world.", memoryWork: "c. 1455, Gutenberg prints the Bible with movable type." },
        { id: "truma-history-u6-l3", title: "Morning Stars of the Reformation", objective: "Describe Wycliffe and Hus as forerunners of the Reformation.", teach: "Long before Martin Luther, brave men saw the corruption in the medieval church, the selling of forgiveness, unbiblical teaching, and a Bible the common people could not read, and they called for reform. In England, John Wycliffe (died 1384) translated the Bible into English and was later called 'the Morning Star of the Reformation.' In Bohemia, Jan Hus preached many of the same truths and was burned at the stake in 1415, a martyr whose death lit a fire that would not go out.", memoryWork: "1415, Jan Hus is martyred; Wycliffe was called the Morning Star of the Reformation." },
        { id: "truma-history-u6-l4", title: "Toward the Reformation", objective: "Summarize why the medieval church needed reform and how the age ended.", teach: "By 1500 the medieval world was ending and a new age was breaking. The church of the Middle Ages had done much good, preserving the Scriptures, teaching the nations, and raising up many faithful believers, yet it had also drifted into grave error and stood in real need of reform. God, who had ruled every century from the fall of Rome onward, was preparing to recover the gospel of grace; in 1517 a monk named Martin Luther would post his Ninety-Five Theses in Germany, and the Reformation would begin. Here the story of the Middle Ages ends, and a new one starts.", memoryWork: "1517, Martin Luther posts the Ninety-Five Theses; the Reformation begins." },
      ],
    },
  ],
};
